### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by tmdakm** [Fody/Costura#1000]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] Blazor WASM
 - [ ] .NET Core

.net framework 4.7.2

## Component

XAML Editor

## Version of Library

  <package id="Costura.Fody" version="6.0.0-beta0000" targetFramework="net472" developmentDependency="true" />
  <package id="Fody" version="6.8.2" targetFramework="net472" developmentDependency="true" />

## Version of OS(s) listed above with issue

Windows 11/Windows 10/Wnidows 7

## Steps to Reproduce
1. Add Ui library of WPF(I tried iNKORE.UI.WPF.Modern And WPF-UI)
2. Add Costura.Fody and Fody
3. Open XAML Editor

## Expected Behavior

XAML Editor loaded normally

## Actual Behavior

It shows me XDG0003 Could not load file or assembly but can run and build project, only in xaml editor, I can use UI Library in C# code, but can't use it in XAML Editor.

![image](https://github.com/user-attachments/assets/a23cb3b4-4564-46e2-bffc-f19b44ead1f6)

**Comment by GeertvanHorrik** [comment]
This project is in maintenance mode. Please provide a fix (with unit tests) if you want this issue solved.

For now I will close this ticket, but feel free to re-open if you want to help out.
