### ISSUE TITLE
Microsoft "antivirus" detects executables packed by Fody as a "virus"

### ISSUE THREAD

**Issue by sensboston** [Fody/Costura#1008]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Microsoft "antivirus" detects executables packed by Fody as a "virus" (same as some other noname stupid "antiviruses"), see report
https://www.virustotal.com/gui/file/770252c7ef9e6baf75406288f875628bdaedc5aa5efc31e4dd0f59e82e68be43/detection

## API Changes
No API changes required (btw, package works like a charm, for a years!) but could you do something to stop this false positive from damn "Necro$oft", please!

## Intended Use Case
This false positive has had a very negative impact on my clients, I risk losing their trust 😢

**Comment by tom-englert** [comment]
If you have any idea what Fody could do about the behavior of Microsoft antivirus...

**Comment by sensboston** [comment]
@tom-englert, I'm very sorry but I don't 😞 What I do know: Costura.Fody is a very legit and extremely helpful package but Micro$oft "defender" is a most "popular" antivirus 'cause it's preinstalled to Windows.

Maybe, contributors/maintainers can try to contact (somwhow) Defender's QA team (it's an extremely hard task) and ask 'em to remove false positive signature... Sorry one more time!

**Comment by sensboston** [comment]
I just now thought that there is a reason for optimism: this false positive happened literally after the last (or penultimate) update. I think that very soon Microsoft will receive millions of requests from irritated users, since Costura.Fody is used by thousands, if not tens of thousands of developers.

@tom-englert, btw, could you please try to reproduce issue on your PC? (but install latest updates first)

**Comment by tom-englert** [comment]
Virus scanners use heuristics, so it's the unlucky combination of your code embedded as resource that triggers the virus warning, this is not a general "Costura" issue.
