### ISSUE TITLE
Feature Request: (Documentation/Utility) Ability to extract embedded reference assembly for troubleshooting

### ISSUE THREAD

**Issue by icnocop** [Fody/Costura#101]
Hi.

Thank you for Fody.Costura 1.3.3.

I'd like to request the ability to extract the embedded reference assembly for troubleshooting.

For example, I want to be able to extract the original reference assembly by using Telerik JustDecompile or Red Gate's .NET Reflector.

When opening the target assembly with Telerik JustDecompile, I can see the referenced assemblies as embedded resources, with the name costura.*.dll.zip for example.

I can then right-click on the entry and select "Save" and save the resource on my local disk as a separate file.

However, when trying to open the costura.*.dll.zip file using WinRAR for example, I get the following error:
`The archive is either in unknown format or damaged`

Any ideas?

Thank you.

**Comment by distantcam** [comment]
Try using  7-zip instead.

**Comment by icnocop** [comment]
Thank you distantcam,

I tried using 7-Zip 9.20 (2010-11-18) for 64-bit Windows x64 but I got the following error:
`Can not open file '...costura.*.dll.zip' as archive`

**Comment by distantcam** [comment]
Ah ok then. :(

They were originally designed to be openable, hence the zip.

Here's the code that unzips the resources. https://github.com/Fody/Costura/blob/master/Template/Common.cs#L178-L188

        if (fullname.EndsWith(".zip"))
        {
            using (var stream = executingAssembly.GetManifestResourceStream(fullname))
            using (var compressStream = new DeflateStream(stream, CompressionMode.Decompress))
            {
                var memStream = new MemoryStream();
                CopyTo(compressStream, memStream);
                memStream.Position = 0;
                return memStream;
            }
        }

It's just the standard `DeflateStream` in the .NET framework. You could make a quick console app to decompress the resources.

**Comment by distantcam** [comment]
As for including this as a feature of Costura. I'm gonna say yagni on it. If you're building something with Costura then you should already have the original references. If you want to debug Costura you already can. (https://github.com/Fody/Costura/wiki/Debugging) 

And if you still need to decompress resources from a Costura build you can do so with the code snippet above. But given the number of times this has come up I don't think it's worth creating a specific tool for this. If there's more demand in the future I'll reevaluate then.

**Comment by saitonakamura** [comment]
Got here looking for the same thing. It's a little bit different now (`.compressed` instead of `.zip`), but basically the same
https://github.com/Fody/Costura/blob/master/Costura.Template/Common.cs#L173

**Comment by imro2** [comment]
Took me way longer than I care to admin to figure this out. So hopefully this PowerShell script will help somebody:
```
$fileInPath = 'costura.compressed.dll.zip'
$fileOutPath = 'costura.decompressed.dll'

$bytes = [system.io.file]::ReadAllBytes($fileInPath)
$input = New-Object System.IO.MemoryStream( ,$bytes)

"Input stream length: '$($input.Length)'"

$output = New-Object System.IO.MemoryStream
$deflateStreem = New-Object System.IO.Compression.DeflateStream $input, ([System.IO.Compression.CompressionMode]::Decompress)
$deflateStreem.CopyTo($output)
$deflateStreem.Close()
$input.Close()

"Ouput stream length: '$($output.Length)'"

$fileStream = New-Object IO.FileStream $fileOutPath ,'Create','Write','Read'
$output.WriteTo($fileStream)
$fileStream.Close()
$output.Close()
```
