### ISSUE TITLE
Run Fody.Costura with Console/BuildTools

### ISSUE THREAD

**Issue by juRiii** [Fody/Costura#102]
Hi,

is there a way to run/execute fody.costura through console or build tools like finalbuilder?

**Comment by distantcam** [comment]
This is more a question for the Fody project, rather than Costura specifically.

Why aren't you using msbuild? What are you using instead?

**Comment by juRiii** [comment]
actually im using msbuild. basically, i dont want to have a merged .exe in every build process. 
i want to trigger this whole process of merging with a build script. in my case with finalbuilder.

**Comment by SimonCropp** [comment]
@juRiii if finalbuilder can execute an msbuild script then this should be possible

**Comment by juRiii** [comment]
i tried it and its possible, but it should be only possible in the build script.
so in visual studio in dev. time the files would not be merged.

but i think i can live with that, if its not possible otherwise.

**Comment by SimonCropp** [comment]
well glad that will work for you
