### ISSUE TITLE
Multiple copies of assemblies embedded

### ISSUE THREAD

**Issue by gharpur** [Fody/Costura#103]
Here's my scenario: I build an API which has 2 main DLLs (one references the other), and a number of utility EXEs which reference one or both of the API DLLs.  I am using Costura on both DLLs and all the EXEs, and want (say) A.exe, B.dll and C.dll to be visible on the disk, with all other utility DLLs being embedded in their respective assemblies.

B.dll references C.dll, so I've excluded C in B's FodyWeavers (I don't want C embedded with B).  However, unless I also explicitly exclude all the DLLs embedded by C, I get another copy of those DLLs automatically embedded in B.  It's possible to add those exclusions, but a real maintenance pain, because the FodyWeavers of each of the higher-level assemblies has to be kept in sync with all the DLLs being used at a lower level.

So... the question is: would it be possible for exclusions to be recursive, i.e. if I exclude a DLL, it should also automatically exclude all DLLs referenced by it?  Related to this, it would also be nice if Costura could detect that it was embedding a DLL which itself uses Costura, because it could then assume (by default) that there was no need to embed any of sub-DLLs.

**Comment by distantcam** [comment]
B references C. C references D. But B may also be using types from D so even if you exclude C, D is still a reference in B. So Costura embeds D into B.

So no, the exclusion cannot be recursive as this may break scenarios for other users. Also Costura should only be used at the top level on A, so recursion is pointless.

**Comment by gharpur** [comment]
OK. I understand there are cases where it might be undesirable behaviour, in which case it could be an option (although I'd still contend that in general if you exclude a DLL, you probably intend to exclude its sub-references too most of the time).

I also don't understand the 'recursion is pointless' statement.  In my scenario which I've outlined (which I accept may not be that common, but certainly isn't unique), if Costura were only used on A, then all the utility EXEs, which are currently about 20k would end up being 100s of Mb, and result in multiple pointless copies of the same DLLs on the install.

It's not a huge deal - it's only an annoyance at the moment to manually add all the exclusions, but it still feels like a useful enhancement to an already excellent package to me.

If it helps, here's another scenario:  Sam is using Costura, but knows that a software package containing a large set of assemblies totalling several Gb will always be pre-installed on the machine, so chooses to exclude them.  His own EXE only references assembly X.DLL within this package and he doesn't know (or care) which other assemblies X references in turn.  However, he finds that his EXE ends up being over a Gb in size (because of all of X's sub-references getting added) and now has to manually inspect his EXE to find out what has been included, and add in 50 more exclusions into his FodyWeavers file.  Why in this case would he not want (or expect) all of X.DLL's sub-references to be excluded, or at least have an easy way to make this happen?
