### ISSUE TITLE
WinFodyTarget not called on TeamCity

### ISSUE THREAD

**Issue by jbako-gn** [Fody/Costura#108]
MSBuild is being invoked via albacore 2.* task in rakefile.  Building via rake locally or using Visual Studio both invoke the WinFodyTarget after CoreCompile correctly.  Running the same rake target via TeamCity makes no attempt to call WinFodyTarget (goes straight from CoreCompile to _CopyFilesMarkedCopyLocal).

Are there extra steps required to enable the WinFodyTarget to be invoked when building via a TeamCity agent?  Local environment is using VS2013/MSBuild 12, while the TeamCity agent has MSBuild 12 but only .NET 4.0 - is there any dependency on .NET 4.5?

**Comment by distantcam** [comment]
Could you please turn on diagnostic logging on the build, and then paste the 2 logs (local and TeamCity) to this issue. Thanks.

**Comment by jbako-gn** [comment]
Visual Studio: http://1drv.ms/1DIy9Jn
Team City: http://1drv.ms/1awUTAk

**Comment by SimonCropp** [comment]
what version of Fody are you using?

**Comment by jbako-gn** [comment]
<package id="Costura.Fody" version="1.3.3.0" targetFramework="net45" />
  <package id="Fody" version="1.26.1" targetFramework="net45" developmentDependency="true" />

**Comment by SimonCropp** [comment]
try 1.28.3

**Comment by jbako-gn** [comment]
Updated, but no dice unfortunately - same build output as for, just a different version number for Fody.

**Comment by SimonCropp** [comment]
how can it be the same output if WinFodyTarget  doenst exist in the current version of fody?

**Comment by jbako-gn** [comment]
Because the problem is that msbuild on our TeamCity agent isn't even attempting to call the WinFodyTarget - it acts like it doesn't exist.  For what it's worth, it still works locally - both by building via VS 2013 or by invoking rake and having it call msbuild.  Even after updating Fody...

**Comment by jbako-gn** [comment]
I didn't catch the slight change in target name before - MSBuild via Visual Studio/rake local is indeed calling "FodyTarget" instead of "WinFodyTarget."  TeamCity makes no attempt to call either though.  Are there specific conditions that Fody looks for to enable MSBuild to find the custom targets in Fody.targets?  I'm trying to work my way through the various files, but I've limited experience beyond the basic MSBuild syntax and not quite sure how the Fody.targets work there way into the compile process.

**Comment by SimonCropp** [comment]
@distantcam so fody no longer has `NonWinFodyTarget` so does this make sense?

https://github.com/Fody/Costura/blob/master/Fody/NugetAssets/commands.psm1#L76

**Comment by jbako-gn** [comment]
I don't really have an explanation, but I just went through and cleaned out all of the references to Fody and Costura.Fody both locally and on the TeamCity agent.  I then re-added everything (very carefully) and made sure TeamCity was pulling down fresh copies of NuGet packages.  Starting again from scratch appears to have done something different than is now allowing TeamCity to find the WinFodyTarget (using 1.26.1 Fody) and embed resources properly.

This is a total guess, but likely something before caused TeamCity to not have/find the Fody package at all, so it never imported the Fody.targets file.

**Comment by SimonCropp** [comment]
Can you upload your csproj befor and after the change?

**Comment by jbako-gn** [comment]
There's no change from the original csproj from when I first installed the Costura.Fody package to this latest instance (using 1.26.1).  Cleaning out the TeamCity agent appears to be what did the trick specifically.

I'm pretty sure on TeamCity this check was just failing altogether initially:
Import Project="..\packages\Fody.1.26.1\build\Fody.targets" Condition="Exists('..\packages\Fody.1.26.1\build\Fody.targets')"

Something about pulling down the NuGet package the first time, doing clean+rebuilds and cleaning the agent, re-pulling packages, etc probably wiped the Fody package and never restored it.  Cleaning it all up let it download the Fody package properly again and things started working.

**Comment by SimonCropp** [comment]
Are you dusing the old nuget restore approach that called nuget.exe from withing csproj?

**Comment by jbako-gn** [comment]
Initially I was set up that way, but it's now being done by TeamCity explicitly.  That could be another thing that changed between the first time it was failing and now.
