### ISSUE TITLE
Fody has been upgraded to work with Rosalyn but this hasn't

### ISSUE THREAD

**Issue by claudekennilol** [Fody/Costura#110]
Fody has been upgraded to work with Rosalyn, but this is still using an old version of Fody.  Currently projects on a system that have vs2015 can't be built.

**Comment by distantcam** [comment]
Costura works fine with the latest version of Fody. NuGet has a bug where it will use the lowest dependency it finds, which is the older version of Fody.

**Comment by claudekennilol** [comment]
Hm, is there any way to force nuget to download the most recent version then?

**Comment by distantcam** [comment]
Not that I know of. @SimonCropp?

**Comment by SimonCropp** [comment]
Nope. The nuget team have consistently called this a feature. Basically every time u install a package that has dependencies u need to follow that with an update

**Comment by claudekennilol** [comment]
running "Update-Package Costura.Fody" tells me that the package already exists.  How do I update it?
@SimonCropp @distantcam

**Comment by SimonCropp** [comment]
Update-Package Fody

-----Original Message-----
