### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by hoctrokha** [Fody/Costura#112]
i have uninstall Costura in nugget, but there is an error when i build my app.
that error :
Fody: You don't seem to have configured any weavers. Try adding a Fody nuget package to your project. Have a look here http://nuget.org/packages?q=fody for the list of available packages. ModernUINavigationApp1

**Comment by distantcam** [comment]
Costura relies on another project called Fody. Try uninstalling the Fody NuGet too.

**Comment by hoctrokha** [comment]
thank you, the error is gone.
