### ISSUE TITLE
Load assembly only from embedded

### ISSUE THREAD

**Issue by phillashworth** [Fody/Costura#114]
I have an executable (abc.exe) which I am embedding in another assembly (def.exe) using Costura, the original abc.exe is then obfuscated and comprerssed and needs to reside in the same directory as def.exe.

My def.exe with embedded abc.exe works fine until it is placed in the same directory as abc.exe, when it fails to load the abc assembly. Any suggections on how I can ensure the embedded abc.exe is loaded first without trying to load the external abc.exe?

**Comment by distantcam** [comment]
Not without calling them different names (like InternalAbc.exe vs Abc.exe).

Because the external abc.exe is loaded by the framework there's no way to override it, just breaking it.

**Comment by phillashworth** [comment]
Thanks for the quick response, that gives me some ideas :)
