### ISSUE TITLE
ModuleWeaver must contain a public instance settable property named 'ModuleDefinition' of type 'Mono.Cecil.ModuleDefinition'

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Costura#115]
Trying to investigate. Will post updates here. As soon as I uncomment the Costura weaver, it works. Using Costura 1.3.3.

**Comment by GeertvanHorrik** [comment]
The latest build is pretty old (November 2014), but the public settable property is available since 2013.

**Comment by distantcam** [comment]
Maybe there's been a change in Cecil that Costura hasn't been updated to handle?

**Comment by GeertvanHorrik** [comment]
I didn't have this issues on other solutions, so checking why it's behaving like this.

**Comment by distantcam** [comment]
What version of Fody are you using?

**Comment by GeertvanHorrik** [comment]
1.29.3

**Comment by GeertvanHorrik** [comment]
btw, additional info:

* VS 2015 (professional)
* Fody 1.29.3
* Costura 1.3.3 (.0)

**Comment by GeertvanHorrik** [comment]
Note that I am using costura succesfully on other projects / solutions with VS 2015, so it must be a local thing. But not sure what it is...

**Comment by distantcam** [comment]
Have you tried quitting VS and restarting?

**Comment by GeertvanHorrik** [comment]
Yep. Also removed the assemblies + redownloaded them. But this is not a project I am working on (mostly other people), so have to investigate every possibility.

**Comment by distantcam** [comment]
So this is the error you're getting. https://github.com/Fody/Fody/blob/master/FodyIsolated/DelegateBuilders/DelegateBuilder.cs#L27

Maybe check the Costura library in ILSpy to make sure it hasn't been corrupted?

**Comment by GeertvanHorrik** [comment]
Good thinking, will do that. Thanks.

**Comment by GeertvanHorrik** [comment]
I have 2 other weavers as well:

* ModuleInit
* Catel

But disabling them does not affect anything. As soon as I disable Costura, it works. Checking if the assembly is corrupt without costura.

**Comment by GeertvanHorrik** [comment]
When I enable VerifyAssembly:

```
7>    Fody:   Verifying assembly
7>    Fody:   Finished verification in 466ms.
```

**Comment by GeertvanHorrik** [comment]
There was a *disabled* project referencing Costura 1.1.0 and Fody 1.20.0. Reloaded the project, updated it all, but the error still remains.

**Comment by GeertvanHorrik** [comment]
Going to check out the code and run against a debuggable version

**Comment by GeertvanHorrik** [comment]
Fresh clone of master:

```
2>  Fody (version 1.24.0.0) Executing
2>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Unknown custom metadata item kind: 6
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
2>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
2>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
2>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
2>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings, Int32& age, Guid& guid)
2>MSBUILD : error :    at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
2>MSBUILD : error :    at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
2>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
2>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
2>MSBUILD : error :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
2>MSBUILD : error :    at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
2>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
2>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
2>MSBUILD : error :    at InnerWeaver.ReadModule() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\ModuleReader.cs:line 23
2>MSBUILD : error :    at InnerWeaver.Execute() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\InnerWeaver.cs:line 28
2>MSBUILD : error : Source:
2>MSBUILD : error : Mono.Cecil.Pdb
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Void ReadCustomMetadata(Microsoft.Cci.Pdb.BitAccess)
2>MSBUILD : error : 
2>  	Finished Fody 7ms.
```

**Comment by GeertvanHorrik** [comment]
Debugging fody, it indeed breaks on Costura. There *is* a type, so checking why the delegate cannot be built.

**Comment by GeertvanHorrik** [comment]
When I change this line from this:

```
targetType.GetProperty(propertyName, BindingFlags.SetProperty | BindingFlags.Instance | BindingFlags.Public, null, typeof(T), new Type[] { }, null)
```

to

```
targetType.GetProperty(propertyName, BindingFlags.SetProperty | BindingFlags.Instance | BindingFlags.Public, null, null, new Type[] { }, null)
```

it works.

**Comment by GeertvanHorrik** [comment]
![image](https://cloud.githubusercontent.com/assets/1246444/9443834/ad30edfc-4a83-11e5-88c0-09965bd3c3a5.png)

**Comment by GeertvanHorrik** [comment]
It looks like Costura is using a custom build of Mono.Cecil, which is a different version.

**Comment by GeertvanHorrik** [comment]
So we need to fix something in Fody. Then we need to fix this in Costura:

![image](https://cloud.githubusercontent.com/assets/1246444/9444578/ee76a596-4a87-11e5-96cb-446fbfc0d383.png)

**Comment by GeertvanHorrik** [comment]
I think this is because the generated (compiled) IL templates are now behaving differently.

**Comment by GeertvanHorrik** [comment]
Trying to fix the IL cloning in a generic way, but it's horrible. Trying for 1 more hour, then giving up.

**Comment by GeertvanHorrik** [comment]
Bingo! Finally fixed it, and afterwards it's always easy to see how things need to be fixed. Since you don't know what members are required inside any body of a method, I first created all the type, fields and method signatures. Once that is done, I revisit all the methods and fill in the body instructions.
