### ISSUE TITLE
Trying to redirect mscorlib type Dictionary<string, boolean> but can't find it.

### ISSUE THREAD

**Issue by ngzero** [Fody/Costura#119]
Fody/Costura: Trying to redirect mscorlib type 'System.Collections.Generic.Dictionary`2<System.String,System.Boolean>', but can't find it, please contact the Costura team.

C# .NET 4.0 Project that only references Newtonsoft.Json and we want to embed the JSON-Librarie to prevent version issues. If we try to comiple the build process is aborted with the message written above.

Fody: An unhandled exception occurred:
Exception: The value is out of range.

![2015-09-01_15-09-30](https://cloud.githubusercontent.com/assets/3295801/9605234/ce643878-50bc-11e5-8172-3646e3b0fe8c.png)
![2015-09-01_15-22-51](https://cloud.githubusercontent.com/assets/3295801/9605331/5478e008-50bd-11e5-9cfb-46376252104a.png)

**Comment by rosshays** [comment]
Just ran into this same issue myself.

![capture2](https://cloud.githubusercontent.com/assets/826611/9611605/96bf2080-50ae-11e5-899a-3f71fae0de83.PNG)

**Comment by goldshtn** [comment]
Probably related to https://github.com/Fody/Costura/issues/118.

**Comment by SimonCropp** [comment]
try 1.3.5

**Comment by rosshays** [comment]
This issue was resolved for me by 1.3.5, thank you.
