### ISSUE TITLE
Value does not fall within the expected range

### ISSUE THREAD

**Issue by casinero** [Fody/Costura#122]
After adding Fody.Costura nuget package into my project, building the project produces following error, what should I do? (VS Community 2015 RTM)

1>------ Build started: Project: eicClientReset, Configuration: Debug x86 ------
1>    Fody: Fody (version 1.29.3.0) Executing
1>      Fody/Costura:   	Embedding 'D:\work\eicClientStuff\eicClientReset\packages\DotNetZip.Reduced.1.9.1.8\lib\net20\Ionic.Zip.Reduced.dll'
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Value does not fall within the expected range.
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at Mono.Cecil.Rocks.TypeReferenceRocks.MakeGenericInstanceType(TypeReference self, TypeReference[] arguments)
1>MSBUILD : error :    at Extensions.MakeHostInstanceGeneric(MethodReference self, TypeReference[] args) in C:\Code\Costura\Fody\Extensions.cs:line 22
1>MSBUILD : error :    at ModuleWeaver.Import(Object operand, TypeDefinition source, TypeDefinition target) in C:\Code\Costura\Fody\AssemblyLoaderImporter.cs:line 370
1>MSBUILD : error :    at ModuleWeaver.CloneInstruction(Instruction instruction, TypeDefinition source, TypeDefinition target) in C:\Code\Costura\Fody\AssemblyLoaderImporter.cs:line 298
1>MSBUILD : error :    at ModuleWeaver.CopyInstructions(MethodDefinition templateMethod, MethodDefinition newMethod, TypeDefinition source, TypeDefinition target) in C:\Code\Costura\Fody\AssemblyLoaderImporter.cs:line 283
1>MSBUILD : error :    at ModuleWeaver.CopyMethod(MethodDefinition sourceMethod, TypeDefinition source, TypeDefinition target, Boolean signatureOnly, Boolean makePrivate) in C:\Code\Costura\Fody\AssemblyLoaderImporter.cs:line 223
1>MSBUILD : error :    at ModuleWeaver.ImportAssemblyLoader(Boolean createTemporaryAssemblies) in C:\Code\Costura\Fody\AssemblyLoaderImporter.cs:line 59
1>MSBUILD : error :    at ModuleWeaver.Execute() in C:\Code\Costura\Fody\ModuleWeaver.cs:line 33
1>MSBUILD : error :    at lambda_method(Closure , Object )
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 164
1>MSBUILD : error :    at InnerWeaver.Execute() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 82
1>MSBUILD : error : Source:
1>MSBUILD : error : Mono.Cecil.Rocks
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Mono.Cecil.GenericInstanceType MakeGenericInstanceType(Mono.Cecil.TypeReference, Mono.Cecil.TypeReference[])
1>MSBUILD : error : 
1>    Fody:   Finished Fody 796ms.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by z0civic** [comment]
Happening to me too, same stack trace

**Comment by toddwprice** [comment]
Same here. Downgrading to 1.3.4 allow successful rebuild on my project.

**Comment by eikcam** [comment]
Same here.

**Comment by Ethenyl** [comment]
Same problem to report, going back to 1.3.4 solved the issue.

**Comment by GregWoods** [comment]
Thanks guys. 1.3.4 fixes it for me too

**Comment by distantcam** [comment]
Fixed in 2.0.0-beta0014
