### ISSUE TITLE
ResourceEmbedder tries to add checksum for already embedded resource.

### ISSUE THREAD

**Issue by mpb27** [Fody/Costura#123]
I have a crash at ResourceEmbedder.cs:94 when the embedder tries to add a duplicate checksum for an already embedded resource which was skipped by Embed() method call on line 91.

Checksums probably shouldn't be added for skipped resources?

**Comment by SimonCropp** [comment]
if this is still a problem in v2 can u please upload a minimal solution that reproduces the issue
