### ISSUE TITLE
Mix Mode assemblies are not compressed

### ISSUE THREAD

**Issue by BryantL** [Fody/Costura#124]
I have a 64bit mixed mode assembly that is the only assembly that I want to embed so my FodyWeavers.xml file contains:
```
<Weavers>
  <Costura>
    <IncludeAssemblies>
      MyAssembly
    </IncludeAssemblies>
    <Unmanaged64Assemblies>
      MyAssembly
    </Unmanaged64Assemblies>    
  </Costura>
</Weavers>
```
When I look inside the assembly I see one copy (prefixed with "costura") with that is compressed (suffixed with ".zip") and another (prefixed with "costura64") that is not compressed (no suffix).

As a secondary thing (possibly should have its own issue?) I don't believe the "costura" prefixed version should exist as it is not included if I do not include the "IncludedAssemblies" element (and therefore let all "copy local" assemblies be included). The "costura64" version is still not compressed in this scenario.

Using Costura.Fody 1.3.5.0

Bryant

**Comment by distantcam** [comment]
Fixed in 2.0.0-beta0014
