### ISSUE TITLE
StackOverflow Exception.

### ISSUE THREAD

**Issue by Seekeer** [Fody/Costura#125]
I've installed Costura.Fody nuget package and built my dll. Its size has been increased. But when I try to use this dll in other projects, I got StackOverflow exception. What am I doing wrong?

**Comment by distantcam** [comment]
Costura is not compatible with libraries. It should only be used with executables.

**Comment by GeertvanHorrik** [comment]
Why would the stackoverflow be related to Costura? Is there a repro?
