### ISSUE TITLE
AssemblyLoader.ResolveAssembly not thread safe

### ISSUE THREAD

**Issue by mdonoughe** [Fody/Costura#127]
Occasionally it seems ResolveAssembly will be called concurrently, which leads to concurrent access to the dictionaries in [Templates/ILTemplate.cs](https://github.com/Fody/Costura/blob/174d704827725bf3bf3cb750172d19a947f983ba/Template/ILTemplate.cs) which can cause infinite loops to occur within the Dictionary code: [High CPU in .NET app using a static Generic.Dictionary](http://blogs.msdn.com/b/tess/archive/2009/12/21/high-cpu-in-net-app-using-a-static-generic-dictionary.aspx). When this happens, you will get a stack trace like this:

- Dictionary<>.FindEntry
- AssemblyLoader.ResolveAssembly
- AppDomain.OnAssemblyResolveEvent

and the thread doing the assembly resolution will hang indefinitely.

**Comment by mdonoughe** [comment]
Specifically, this appears to be an issue with nullCache. The other dictionaries appear to be read-only after the static type initializer has run.

**Comment by distantcam** [comment]
Fixed in 2.0.0-beta0018
