### ISSUE TITLE
embedding files with password protected keyfile is not possible

### ISSUE THREAD

**Issue by BennyBread** [Fody/Costura#131]
Hi, I just found out that it is not possible to embedd assemblies to an executable which has an key file with password protection. I wrote an message there, because this was what gives me the solution to my problem:
https://github.com/Fody/ExtraConstraints/issues/5#issuecomment-160113995

I really think that this schould be mentioned on a obviously public place that it is not possible to do " what costura does" with password protected key files.

**Comment by distantcam** [comment]
The error message should be added to the main Fody project. Please submit a PR there.
