### ISSUE TITLE
Cleanup target does not work with VS2010

### ISSUE THREAD

**Issue by BennyBread** [Fody/Costura#132]
Hi, I installed the clean Target addon using Install-CleanReferencesTarget.

I'm using Costura.Fody.1.3.5.0. 

I get an error after build / embedding from the leanup command: (Sorry the output is german; thanks to our IT department)

This is the output (project name and dll names omitted):

---

```
Fody: Fody (version 1.29.3.0) Executing
  Fody/Costura:     Embedding '....Common.dll'
  Fody/Costura:     Embedding '...Control.dll'
  Fody/Costura:     Embedding '..EPPlus.dll'
  Fody/Costura:     Embedding '..Wpf.dll'
Fody:   Finished Fody 330ms.
```

  XXXXX -> ....Viewer.exe
    Fody:   Skipped Verifying assembly since it is disabled in configuration
    Fody:   Finished verification in 0ms.
...Viewer.csproj(486,5): error MSB4018: Unerwarteter Fehler bei der CosturaCleanup-Aufgabe.
...Viewer.csproj(486,5): error MSB4018: System.ArgumentException: Das Objekt mit dem Typ "Microsoft.Build.Execution.ProjectItemInstance+TaskItem" kann nicht in den Typ "Microsoft.Build.Framework.ITaskItem" konvertiert werden.
...Viewer.csproj(486,5): error MSB4018:    bei System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
...Viewer.csproj(486,5): error MSB4018:    bei System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
...Viewer.csproj(486,5): error MSB4018:    bei System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
...Viewer.csproj(486,5): error MSB4018:    bei System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
...Viewer.csproj(486,5): error MSB4018:    bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
...Viewer.csproj(486,5): error MSB4018:    bei System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
...Viewer.csproj(486,5): error MSB4018:    bei System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
...Viewer.csproj(486,5): error MSB4018:    bei Microsoft.Build.Execution.TaskFactoryWrapper.SetPropertyValue(ITask task, TaskPropertyInfo property, Object value)
...Viewer.csproj(486,5): error MSB4018:    bei Microsoft.Build.BackEnd.TaskExecutionHost.InternalSetTaskParameter(TaskPropertyInfo parameter, Object parameterValue)
...Viewer.csproj(486,21): error MSB4026: Der Config=FodyWeavers.xml-Parameter für die CosturaCleanup-Aufgabe ist ungültig.
...Viewer.csproj(486,5): error MSB4063: Die CosturaCleanup-Aufgabe konnte nicht mit den Eingabeparametern initialisiert werden. 

---

the executable runs, but the cleanup does nothing.

**Comment by SimonCropp** [comment]
sorry VS 2010 is not supported
