### ISSUE TITLE
Embedding native libraries across multiple platforms

### ISSUE THREAD

**Issue by SirusDoma** [Fody/Costura#133]
I just found out Fody today, and it was awesome!

I tried to install the nuget package on my project and try to embed `FreeType` library, it was working properly!

However I got question, is this gonna work with `.so` (linux) or `.dylib` (osx)?
for example, I previously written a cross platform game that uses [fmodex](http://fmod.org) and i have to split 3 distributions package to 3 major OS

- Windows: I ship my game binary (say, it's `game.exe`) and `fmodex.dll`
- Linux: I ship `game.exe` along with `libfmod.so` and `game.exe.config` to map the native library in Mono
- Mac: almost same like Linux, but I ship `libfmod.dylib`

So how I do that in Fody.Costura? 
Do I only need to copy those libraries into `costura32` / `costura64` folder?
I don't have Linux nor OSX environment, previously I use VM, but I'm no longer use VM and cannot test this.

Thanks in advance!

**Comment by distantcam** [comment]
Costura only support the Windows platform.
