### ISSUE TITLE
How can i merge Unmanaged dlls in Exe

### ISSUE THREAD

**Issue by mike123sxyocr** [Fody/Costura#134]
I try to merge some Unmanaged dlls in Exe like this.
![image](https://cloud.githubusercontent.com/assets/12912565/11608198/a858248a-9ba5-11e5-81fc-0d1fa80db790.png)

 But the  Exe file built does not seem to contain the Unmanaged dll i want to merge.
![image](https://cloud.githubusercontent.com/assets/12912565/11608214/ffe9cec4-9ba5-11e5-9645-192fe01130b7.png)

**Comment by distantcam** [comment]
Make sure the `Build Action` for the libraries are `Embedded Resource`.

![image](https://cloud.githubusercontent.com/assets/1298847/11608264/54d49b5a-9b9f-11e5-8722-24a89c4d2a93.png)

**Comment by mike123sxyocr** [comment]
thank  you。
i change the  Build Action from "Content" to "EmbeddedResource" , built Exe is like this
![image](https://cloud.githubusercontent.com/assets/12912565/11608601/5cef48c8-9bb1-11e5-9f01-393c1d856728.png)

when the Exe is be lanching,  is that a way to realse these dlls(assemblies) from Exe to a physical floder  be designated?

**Comment by zhanfuzhi** [comment]
楼上，我不会，可不可以留个联系方式，教教我，谢谢。

**Comment by zhanfuzhi** [comment]
你好，请问下，我也遇到了类似问题，可是操作不见效果，可否给看一下啊。

**Comment by distantcam** [comment]
@zhanfuzhi I'm sorry, I only speak English.

> when the Exe is be lanching, is that a way to realse these dlls(assemblies) from Exe to a physical floder be designated?

No. If that's what you need you're better off creating your own system.
