### ISSUE TITLE
Option to disable Fody Costura

### ISSUE THREAD

**Issue by SirusDoma** [Fody/Costura#135]
As being said in #57 we cannot use our assembly under mono runtime with fody costura.
So while its not supported, it may good idea to add an option to enable and disable fody upon build process.

Currently, im developing a cross platform game with fody costura, it is tedious work to remove the fody costura from nuget package to build to non windows platform and add it back again when im building to windows platform.

I tried to exclude assemblies, but still not working, it seems fody costura still there

**Comment by JessieArr** [comment]
I needed this as well, and was able to use this configuration as a workaround in my scenario:

<Costura IncludeAssemblies='' />

I agree that it would be nice to have a configuration option specifically designed to disable Costura temporarily for testing purposes though. I've been doing some benchmarks with various Costura configuration options (and with it disabled entirely) and having a quick way to disable it is useful for that, but that workaround was not immediately evident and may not work in all scenarios.

**Comment by SirusDoma** [comment]
@JessieArr 
Is the compiled assembly gonna works well in mono with that workaround?

**Comment by JessieArr** [comment]
I can't say, I'm not terribly familiar with how Mono differs from a Windows environment. But it is a pretty simple setting to test. Just make the change, build and test in your target environment to see if it will work for you. 

It just prevents Costura from embedding any of the assemblies referenced by your projects as resources, meaning that it will only be able to use what is on disk at runtime. For my use-case that's all that was required to do the testing I needed.

**Comment by distantcam** [comment]
If you have a mono and non-mono project, why not just uninstall Costura from the mono project?

This can be better solved by sorting out your build system.

**Comment by SirusDoma** [comment]
I'm using a single project which intended to run multiple platforms after build...
There is no "mono" and "non-mono" project, just one, because basically the program do the same thing with no platform / framework specific code
