### ISSUE TITLE
Whitelist for CreateTemporaryAssemblies

### ISSUE THREAD

**Issue by JessieArr** [Fody/Costura#137]
I have a use-case that would be suited well by the ability to create a whitelist of assemblies to be written to disk by CreateTemporaryAssemblies. A configuration setting such as "IncludeTemporaryAssemblies" which would accept an argument of assembly names to be copied to disk at runtime, rather than copying _all_ embedded assemblies to disk could be very useful.

More about my circumstance: My application uses the DevExpress tools for displaying and printing reports. DevExpress' print process runs in a separate AppDomain, and as a result fails when the DLLs managed by Costura do not exist on disk. But CreateTemporaryAssemblies results in about 150MB of embedded DLLs (many of which are DevExpress, and outside of my control) being copied to disk the first time the application starts, resulting in about a 10 second delay before the application splash screen is displayed, which is a very bad user experience.

In practice however, I only need a few of DevExpress' DLL dependencies to exist on disk at runtime, which could easily be enumerated in Fody's configuration file.

**Comment by SimonCropp** [comment]
u can include or exclude assemblies https://github.com/Fody/Costura#excludeassemblies
