### ISSUE TITLE
Costura doesn't handle non-english resource loading

### ISSUE THREAD

**Issue by distantcam** [Fody/Costura#138]
Had a bug where serializing an object on a German system caused an exception because Costura doesn't load the mscorlib resources properly.

**Comment by n00bje** [comment]
Are you talking about the "mscorlib recursive resource lookup" bug? I'm having issues when working with XML for DOCX generation. This issue doesn't occur when I disable Costura or when I use the default culture of en-US.

![image](https://user-images.githubusercontent.com/6150967/30157490-bc561188-93c2-11e7-9ef1-6b15efb37ad3.png)

**Comment by triumlabs** [comment]
Why this issue is closed? This problem still exists.
In my case, I try to use IsolatedStorageFile in a non en-US environment. When creating a file (via IsolatedStorageFile.OpenFile), LongPathFile.GetLength runs into an error and then this method tries to read culture specific error message. This is the point when the "mscorlib recursive resource lookup" problem occurs. This problem does not occur if thread culture is en-US or debugging the code in VS.

**Comment by SimonCropp** [comment]
@triumlabs raise a new issue and follow the issue template

**Comment by gellweiler** [comment]
If you don't care about the local culture settings simply adding the following to your Main method to set the culture to en-US will fix the issues:

`
            // Change the current culture to en-US.
            // this is done to prevent issues with Fody: https://stackoverflow.com/a/48880128, https://github.com/Fody/Costura/issues/138
            CultureInfo.CurrentCulture = new CultureInfo("en-US", false);
            CultureInfo.DefaultThreadCurrentCulture = CultureInfo.CurrentCulture;

            var culture = CultureInfo.GetCultureInfo("en-US");

            // this may fail sometimes: (see Drachenkatze's comment below)
            // var culture = new CultureInfo("en-US");

            //Culture for any thread
            CultureInfo.DefaultThreadCurrentCulture = culture;

            //Culture for UI in any thread
            CultureInfo.DefaultThreadCurrentUICulture = culture;

            //Culture for current thread (STA)
            //no need for: Application.CurrentCulture = culture;

            //Thread.CurrentThread.CurrentCulture == Application.CurrentCulture
            //no need for: Thread.CurrentThread.CurrentCulture = culture;

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());`
