### ISSUE TITLE
Q: Is it possible to specify an alternative directory for Costura?

### ISSUE THREAD

**Issue by dennisroche** [Fody/Costura#140]
Is it possible to specify an alternative directory for Costura to output to?

**Use Case:** I want to create two NuGet packages from a project. 

- one as a lib with dependencies defined in nuspec metadata.
- the other as a complete exe, generated with Costura.

**Comment by distantcam** [comment]
Costura is a plugin for the Fody system, which takes care of decompiling/recompiling the project output. 

Fody modifies the exe in the `IntermediatePath` (obj) after compile, but before the output is moved to the `OutputPath` (bin) folder.

So it is possible to change the output directory, especially if you're doing custom MSBuild stuff. How do you plan to get the project to output 2 things?

https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets is the MSBuild targets imported into the project. But they can be overridden.

**Comment by dennisroche** [comment]
Thanks @distantcam. 

I did managed to copy the intermediate file before what I thought `FodyTarget` modified it however the `AssemblyLoader` was already injected. This resulted in the non-costura assembly failing when loaded as it was looking for the embedded resources.
