### ISSUE TITLE
Ability to automatically extract embedded assemblies to the same location as the assembly instead of a temporary directory, and when the assembly is loaded

### ISSUE THREAD

**Issue by icnocop** [Fody/Costura#141]
I would like to request the ability to automatically extract embedded assemblies to the same location as the assembly instead of a temporary directory, and when the assembly is loaded.

This will help resolve issues in two places I've encountered:
1. ASP.NET
2. mstest

Both frameworks will copy the assemblies to a different temporary location where they are actually run.
However, ASP.NET will copy different assemblies to their own separate folders which may cause assembly loading to fail if the assembly expects the references to exist in the same directory.
Mstest will only copy the references that are directly referenced in the unit test project before running the unit tests and so if an assembly indirectly references another assembly, it will fail to find it.

For example, I have a unit test project that references EntityFramework.dll and EntityFramework.SqlServer.dll. But when the unit test is run, I get the following error: 
`Could not load type 'System.Data.Entity.Infrastructure.TableExistenceChecker' `
That type exists in `EntityFramework.SqlServer.dll` but that dll is not copied to the directory where the test is run because it is not directly referenced in code by the test project.
The same error occurs even if I use Costura.
Only if I add `[DeploymentItem("EntityFramework.SqlServer.dll"]` to my unit test, then it works without issues.
But imagine if I have a lot of unit test projects that reference a shared/common assembly that requires "EntityFramework.SqlServer.dll"?
Instead of having to add `[DeploymentItem("EntityFramework.SqlServer.dll"]` to each test project, I'd rather have Costura:
1. embed "EntityFramework.SqlServer.dll" in the referenced assembly
2. automatically extract "EntityFramework.SqlServer.dll" when the referenced assembly is loaded to the same directory where the referenced assembly is

This solves the issue, doesn't cause any code smells / spaghetti code, and the code is easier to maintain.

The only caveat I foresee is if the assembly doesn't have permission to create files in the same location as the assembly. In that case, I would expect the module initializer to just throw a detailed security exception if possible.

Maybe this configuration setting can be both a global and on a per assembly basis.

Thank you.

**Comment by distantcam** [comment]
Costura does not support libraries.

**Comment by awestroke** [comment]
I also have this problem, and I am confused by the response to this issue. Costura obviously supports embedding unmanaged DLLs, so why is this issue not taken seriously?
