### ISSUE TITLE
Config file too?

### ISSUE THREAD

**Issue by Sn3b** [Fody/Costura#142]
Is it possible to also embed the config file?

**Comment by distantcam** [comment]
No it's not possible. The mechanisms are completely different.

If you want to embed your config why not hard code the config?

**Comment by Sn3b** [comment]
Yes Indeed, that's what I started doing :)
Was just wondering if it was possible.

Thanks! :)

**Comment by SimonCropp** [comment]
yeah sorry this is about bundling dependencies not configuration. closing

**Comment by mistree** [comment]
> No it's not possible. The mechanisms are completely different.
> 
> If you want to embed your config why not hard code the config?
> 
> On Monday, 8 February 2016, Sebastien de Salvador [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > Is it possible to also embed the config file?
> > —
> > Reply to this email directly or view it on GitHub
> > #142.

because for some runtime related settings it's very hard to change it from code/undocumented. e.g <runtime><NetFx40_PInvokeStackResilience>
