### ISSUE TITLE
How to disable Costura.Fody in Debug mode?

### ISSUE THREAD

**Issue by Hooch180** [Fody/Costura#143]
I'm using Costura.Fody to embed all dlls into my application assembly.

Is there any way to disable Costura.Fody in Debug build mode? How to make Costura.Fody to work only in Release or custom build configuration?

**Comment by distantcam** [comment]
No there isn't. Sorry.

**Comment by Hooch180** [comment]
Ok...
So can this be added as suggestion to suggestion list?

**Comment by distantcam** [comment]
Why do you need this?

**Comment by MKArithmetica** [comment]
You can make different FodyWeavers configuration files for debug and release and then use a pre build event to copy the file, e.g.

if $(ConfigurationName) == Debug (
xcopy $(SolutionDir)FodyWeavers_debug.xml $(SolutionDir)FodyWeavers.xml* /Y
) ELSE (
xcopy $(SolutionDir)FodyWeavers_release.xml $(SolutionDir)FodyWeavers.xml* /Y
)

In the FodyWeavers_debug.xml you have to exclude all the assemblies.

**Comment by sManWorks** [comment]
Old question but since Google brings up this as a search result like how it brought me, here's a workaround : 

By default Costura.Fody package adds one line into your *.csproj file. Something like :
`<Import Project="..\packages\Costura.Fody.1.5.1\build\dotnet\Costura.Fody.targets" Condition="Exists('..\packages\Costura.Fody.1.5.1\build\dotnet\Costura.Fody.targets')" />`
Add a condition for configuration name like this :
`<Import Project="..\packages\Costura.Fody.1.5.1\build\dotnet\Costura.Fody.targets" Condition="'$(Configuration)' == 'Release' and Exists('..\packages\Costura.Fody.1.5.1\build\dotnet\Costura.Fody.targets')" />`

**Comment by AIBrain** [comment]
sManWorks, wouldn't that require changing each project when Fody or Costura is updated?

**Comment by masters3d** [comment]
I am having an issue where I can not tests because my tests can not be found. Has anybody seen this before?

**Comment by SimonCropp** [comment]
`  <DisableFody Condition="'$(Configuration)' == 'Debug'>true</DisableFody>`

**Comment by Logerfo** [comment]
@SimonCropp FTFY
```xml
<DisableFody Condition="'$(Configuration)' == 'Debug'">true</DisableFody>
```

**Comment by SimonCropp** [comment]
Doh. Thanks

**Comment by Logerfo** [comment]
@SimonCropp I have a project with two weavers: CryptStr and Costura. The `DisableFody` tag worked for CryptStr, that is, when building in debug, strings are not encrypted. But within the same project, Costura is weaving in debug builds. I'll be using the workaround @sManWorks suggested again for now.

**Comment by SimonCropp** [comment]
i will accept a PR to Fody that allows toggling of weavers by build config

**Comment by masters3d** [comment]
@SimonCropp sorry for the silly question but where do I add this? 
```<DisableFody Condition="'$(Configuration)' == 'Debug'">true</DisableFody>```

**Comment by SimonCropp** [comment]
@masters3d in the first `PropertyGroup` of your csproj

**Comment by SimonCropp** [comment]
@Bitz i dont think i understand the problem? can u elaborate?

**Comment by hanvyj** [comment]
@SimonCropp I'm facing the same issue. I'm using Fody with Costura to embed resources and get a nicely packaged exe. However, I want edit and continue while debugging.

If I add `<DisableFody Condition="'$(Configuration)' == 'Debug'">true</DisableFody>`, then the exe doesn't get the resources embedded but they're also not being copied into the output folder - so can't be found by the application.

**Comment by SimonCropp** [comment]
ok i will reopen this. if someone wants to work on a solution in a PR i am happy to review and merge.

if no one want to work on it and it is ignore, we can close it again in a few weeks

**Comment by SimonCropp** [comment]
happy to re-open if someone wants to work on it

**Comment by moh-hassan** [comment]
in SDK style project, vs 2017, I add Costura.Fody in Release only , and do test in debug.

         <ItemGroup Condition="$(TargetFramework.StartsWith('net4')) AND '$(Configuration)' == 'Release'">
            <PackageReference Include="Costura.Fody" Version="3.3.3" />
       </ItemGroup>

**Comment by AlBannaTechno** [comment]
> 
> 
> in SDK style project, vs 2017, I add Costura.Fody in Release only , and do test in debug.
> 
> ```
>      <ItemGroup Condition="$(TargetFramework.StartsWith('net4')) AND '$(Configuration)' == 'Release'">
>         <PackageReference Include="Costura.Fody" Version="3.3.3" />
>    </ItemGroup>
> ```

you can also, set the condition at the top of 
**projectName.csproj**
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\Costura.Fody.4.1.0\build\Costura.Fody.props" Condition="Exists('..\packages\Costura.Fody.4.1.0\build\Costura.Fody.props') AND '$(Configuration)' == 'Release'" />


```

**Comment by tom-englert** [comment]
@AlBannaTechno you have to embed the configuration in the project file, then you can make it conditional, too:
https://github.com/Fody/Home/blob/master/pages/configuration.md#an-msbuild-property-in-the-project-file

**Comment by HeHang0** [comment]
Edit csproj file, add node 'When'
``` xml
<Choose>
  <When Condition=" '$(Configuration)'=='Release' ">
    <ItemGroup>
      <PackageReference Include="Costura.Fody">
        <Version>5.7.0</Version>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
    </ItemGroup>
  </When>
</Choose>
```
