### ISSUE TITLE
Costura giving false errors?

### ISSUE THREAD

**Issue by Birdboat** [Fody/Costura#144]
Hi, I have two dependencies for my dll that I'm trying to embed, however, when ever I install Costura by Nuget. It gives a false error, whenever I remove Costura, the error goes away.
Any Ideas?

![Error](http://i.imgur.com/IxfBq6M.png)

The full is error is this: 
Severity	Code	Description	Project	File	Line	Suppression State
Error		C:\Users\birds\AppData\Local\Temp\tmp369\TS3PluginFramework.il(1187) : error : Undeclared identifier IL_000a
C:\Users\birds\Desktop\Projects\TS3PluginFramework\TS3PluginFramework\Exports_Funcs.cs(452) : error : syntax error at token ':' in:       IL_000a:  call       instance void* ['mscorlib']'System'.'IntPtr'::'ToPointer'()	TS3PluginFramework

**Comment by distantcam** [comment]
Is this using 1.3.3? Try downgrading to 1.3.2

**Comment by Birdboat** [comment]
Just tried that, same error

**Comment by distantcam** [comment]
When you downgrade make sure to exit Visual Studio so the fody plugins can be reloaded.

Otherwise, could you upload a repo somewhere?

**Comment by Birdboat** [comment]
Created it [here](https://github.com/Birdboat/TempError)

**Comment by distantcam** [comment]
The error is happening in another package, UnmanagedExports.

Also Costura doesn't support libraries.

**Comment by Birdboat** [comment]
But it runs fine while Costura isn't added, or do you mean Costura and UnmanagedExports are interfering with each other?

**Comment by distantcam** [comment]
Costura and UnmanagedExports are interfering with each other, and the error is happening in UnmanagedExports.

**Comment by Birdboat** [comment]
Ok, thanks

**Comment by akamyshanov** [comment]
When experienced such an issue, disabling PDB generation helped. Not sure if it's a possibility for you to do the same.
