### ISSUE TITLE
How I can embed exe file?

### ISSUE THREAD

**Issue by win32nipuh** [Fody/Costura#145]
I have an app Test.exe which  runs pocess internalTest.exe  this way:

```
          ProcessStartInfo prcInfo = new ProcessStartInfo(strpath)
            {
                CreateNoWindow = false,
                UseShellExecute = true,
                Verb = "runas",
                WindowStyle = ProcessWindowStyle.Normal
            };
            var p = Process.Start(prcInfo);
```
Now I need to provide 2 exe files  to user.

Is it possible to embed internalTest.exe and then run it?

**Comment by distantcam** [comment]
Yes. Just embed the exe as a resource, and when your program starts load the embedded exe from the resource and save it to disk. You don't need Costura for that, and Costura cannot help you.

**Comment by SAASTN** [comment]
> Yes. Just embed the exe as a resource, and when your program starts load the embedded exe from the resource and save it to disk. You don't need Costura for that, and Costura cannot help you.

What if internalTest.exe also references dlls that test.exe do? I know I can add Costura to internalTest, but I want both exe files use very same set of dlls. Is that possible?

**Comment by SimonCropp** [comment]
@SAASTN no
