### ISSUE TITLE
Not embedding roslyn libraries and files from Microsoft.CodeDom.Providers.DotNetCompilerPlatform nuget package

### ISSUE THREAD

**Issue by jakubsuchybio** [Fody/Costura#147]
Hi,
let me just say first. I Love your extension. So much cleaner solutions!

So, I have this project where I am manually compiling our game server via CSharpCodeProvider from Microsoft.CodeDom.Providers.DotNetCompilerPlatform, but it installs dependencies in executable's subfolder roslyn/some_stuff.

I traced it where it comes from and it's from:

```
packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.1\build\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props
```

These files are required by CSharpCodeProvider (I tried to remove them one by one and most of them are required)

They are not included into embedded resources, but would be awesome to have them there too.

Thanks.

**Comment by SimonCropp** [comment]
are they set to copy local?

**Comment by jakubsuchybio** [comment]
Well they are not present in solution. 
When I install "Microsoft.CodeDom.Providers.DotNetCompilerPlatform" nuget it has dependency "Microsoft.Net.Compilers".
When I compile, it includes a step from:
"packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.1\build\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props"
```xml
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="$(CscToolPath)\*">
      <Link>roslyn\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```
This will copy the contents of "packages/Microsoft.Net.Compilers.1.0.0/tools" into subfolder "roslyn" of executable dir of compiled program. Like this:
![image](https://cloud.githubusercontent.com/assets/6567287/14077000/2f9a90a0-f4e7-11e5-9f26-252091e5aafd.png)

And I don't know how to add them into embedding for your extension. Do I need to add them all manually to solution? Or How?

**Comment by SimonCropp** [comment]
if this is still a problem in v2 can u please upload a minimal solution that reproduces the issue
