### ISSUE TITLE
Adding log to Costura assembly 

### ISSUE THREAD

**Issue by saidgargouri** [Fody/Costura#151]
Hello, 

I tried to add same log (i used win32 message box to avoid adding additional lib) to Common.cs and Templates classe (I have exception and I try to understand what goes wrong ...)

I build the project and i replaced the generated assembly "Costura.Fody.dll" in the nuget directory of my project but i have a fody exception in  "var msCoreLibDefinition = AssemblyResolver.Resolve("mscorlib");"

Even with adding the Mono libs the problem persist.

have you any idea how can i use a modified version of Costura ?
other question have you an idea how to catch win32 exception in moduler initialisation (I dont want to have the aggressive win32 messageboxe)

Thank you

**Comment by SimonCropp** [comment]
if this is still an issue please share a small solution that illustrates what you are trying to achieve
