### ISSUE TITLE
problem with xml config files

### ISSUE THREAD

**Issue by rafatanic** [Fody/Costura#155]
I use nlog with costura.fody but nlog needs the xml file nlog.config
when i use costura.fody and i tried to use the .exe of the app outside the app folder
give me an error
there is a way to fix this?
tx

**Comment by SimonCropp** [comment]
either embed the logging config as a resource and load it at startup or configure nlog using code

**Comment by rafatanic** [comment]
sorry but how can i load it at starup? 
tx

**Comment by SimonCropp** [comment]
turns out u cant. https://github.com/NLog/NLog/issues/165  so u will have to configure it with code

**Comment by rafatanic** [comment]
tx for everything ;D

**Comment by SimonCropp** [comment]
sorry but costura is about merging .dlls. other static files and config is not a problem it is trying to solve

**Comment by brandon-zeeb-nw** [comment]
maybe costura should be about merging anything as an embedded resource, pays to observe the needs of your users.

**Comment by SimonCropp** [comment]
@brandon-zeeb-nw you are welcome to fork costura a receive that payment

**Comment by SimonCropp** [comment]
@brandon-zeeb-nw btw did you read this https://github.com/NLog/NLog/issues/165
