### ISSUE TITLE
Ability to disable Costura

### ISSUE THREAD

**Issue by screig** [Fody/Costura#157]
Hi

I would like the see the ability to be able to switch the packaging either on or off added in a future release. I have a wide set of consumers for some it is appropriate to give a packaged dll and some it is not.

Thanks
Sean

**Comment by SimonCropp** [comment]
> packaged dll 

Costura is targeting exes you should not be using it for dlls

**Comment by screig** [comment]
Is that not changing the goal posts a little?

> Details
> 
> This Task performs the following changes
> 
> Take all assemblies (and pdbs) that have been marked as "Copy Local" and embed them as resources in the target assembly.

Where an assembly is

**Comment by danatcofo** [comment]
I would like to be able to turn Costura on or off based on build targets.  i.e. DEBUG don't package, RELEASE package.  We have cases where shipping a packaged single exe is needed and cases where the dependent dlls will be shared between two side by side exe's.

**Comment by distantcam** [comment]
This is more of a Fody concern. Closing.

**Comment by screig** [comment]
could you explain that?

**Comment by distantcam** [comment]
Disabling specific plugins should be handled by fody, not by each plugin.
