### ISSUE TITLE
Costura embeds path to PDB despite IncludeDebugSymbols=False

### ISSUE THREAD

**Issue by pschord** [Fody/Costura#162]
I'm trying to make sure my generated EXE has absolutely no references to PDBs as they are usually full paths, which includes my folder names.

This is disclosing my information and I am unable to use this tool.

Running strings on the generated EXE shows

```
!This program cannot be run in DOS mode.
.text
`.rsrc
<SNIP>
RSDS
C:\Users\XXX\Documents\code\XXX.pdb
_CorExeMain
mscoree.dll
PADDINGXXPADDING
<EOF>
```

where XXX is sensitive. I am unable to remove this reference, despite running a release build with all debugging and PDB options turned off.

**Comment by apmorton** [comment]
just an FYI, this is nothing to do with costura, and isn't something costura could solve.

This is expected behavior, and is a fundamental part of the PE format - a workaround is to build your releases from a non-sensitive path.

**Comment by distantcam** [comment]
Thanks @apmorton for that info.

@pschord Even if you remove Costura the pdb path is still in the executable. Your options are build in a non-sensitive path or use an obfuscator that works with strings. Either way it's not a Costura problem.
