### ISSUE TITLE
RegAsm does not find merged assembly

### ISSUE THREAD

**Issue by koyote** [Fody/Costura#163]
I have been trying to to use Costura with a dll that is usually registered using Regasm.exe to make itself visible to COM clients.

This works fine with an assembly merged using IlMerge but with Costura I get the following error when registering:

`C:\> regasm.exe /codebase TheDll.dll /tlb`
`[...]`
`RegAsm : error RA0000 : Could not load file or assembly 'AnotherAssembly, Version=1.0, culture=neutral, PublicKeyToken=...' or one of its dependencies. The system cannot find the file specified.`

I have tried using the CreateTemporaryAssemblies option to no avail.

**Comment by domehead100** [comment]
A workaround might be to ensure that only you COM interfaces/classes are marked as COM visible.  Everything else should be either "internal" or explicitly given the [ComVisible(false)] attribute.  Then RegAsm will only look for your COM visible classes in the main assembly when reflecting to find COM stuff to include.  This worked for me for a local COM server exe.

**Comment by huffSamuel** [comment]
Marking only COM interfaces/classes as visible and ensuring everything else is `[ComVisible(false)]` did not work for me. I experienced the same issues as koyote

`RegAsm : error RA0000 " Could not load file or assembly 'OtherAssembly, version, ...' or one of its dependencies`

**Comment by distantcam** [comment]
Costura now supports a way of manually adding the hooks it needs to run properly. This call will need to be added to your startup code, as early as possible.

https://github.com/Fody/Costura#costurautility-link

**Comment by koyote** [comment]
Maybe I am missing something here but I am not sure how this is supposed to solve the issue above.
A COM library does not have any 'startup code' as it simply acts as a library dll with an exposed interface. Other software will call this interface using COM.

I tried adding the CosturaUtility code as static to all [ComVisible(true)] classes but it made no difference.

**Comment by jurajvt** [comment]
@koyote Have you solved this problem? I tried to make COM visible only one class, tried to put there `CosturaUtility.Initialize()`, no difference. Debug build on my machine from Visual Studio with **Register for COM interop** option enabled works normally. Problem is only with regasm on client machine.

**Comment by jurajvt** [comment]
@koyote 

1. I builded tlb with regasm on my machine, then moved output files to the client machine
2. I copied registry keys searched by assembly GUID and merge them on the client machine

This works for me.

**Comment by colin-sim** [comment]
Why is this issue closed? The problem still exists.

**Comment by harmonypiano** [comment]
I encountered this problem too. So I have to write my own regasm.exe, the key point is to call `Costura.AssemblyLoader.Attach()` so that all the embedded assemblies will be loaded, before you call `RegisterAssembly()`.

```
using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;
using System.Text;

namespace MyRegAsm
{
    class Program
    {
        static void Main(string[] args)
        {
            var assemblyName = args[0];
            var assemblyPath = Path.GetFullPath(assemblyName);
            var a = Assembly.LoadFrom(assemblyPath);
            var costura = a.GetType("Costura.AssemblyLoader");
            costura.GetMethod("Attach").Invoke(null, null);
            var r = new RegistrationServices();
            r.RegisterAssembly(a, AssemblyRegistrationFlags.SetCodeBase);
            var tlbName = Path.Combine(Path.GetDirectoryName(assemblyPath), Path.GetFileNameWithoutExtension(assemblyPath) + ".tlb");
            DoExportAndRegister(a, tlbName);
        }
        [Guid("00020406-0000-0000-C000-000000000046")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [ComVisible(false)]
        [ComImport]
        internal interface ICreateITypeLib
        {
            void CreateTypeInfo();
            void SetName();
            void SetVersion();
            void SetGuid();
            void SetDocString();
            void SetHelpFileName();
            void SetHelpContext();
            void SetLcid();
            void SetLibFlags();
            void SaveAllChanges();
        }
        [DllImport("oleaut32.dll", CharSet = CharSet.Unicode, PreserveSig = false)]
        private static extern void RegisterTypeLib(ITypeLib TypeLib, string szFullPath, string szHelpDirs);
        class NotifySink : ITypeLibExporterNotifySink
        {
            public void ReportEvent(ExporterEventKind eventKind, int eventCode, string eventMsg)
            {
            }

            public object ResolveRef(Assembly assembly)
            {
                string directoryName = Path.GetDirectoryName(assembly.Location);
                string name = assembly.GetName().Name;
                string text = Path.Combine(directoryName, name) + ".tlb";
                return DoExportAndRegister(assembly, text);
            }
        }
        internal static ITypeLib DoExportAndRegister(Assembly asm, string strTypeLibName)
        {
            ITypeLibConverter typeLibConverter = new TypeLibConverter();
            var notifySink = new NotifySink();
            ITypeLib typeLib = (ITypeLib)typeLibConverter.ConvertAssemblyToTypeLib(asm, strTypeLibName, TypeLibExporterFlags.None, notifySink);
            ICreateITypeLib createITypeLib = (ICreateITypeLib)typeLib;
            createITypeLib.SaveAllChanges();
            RegisterTypeLib(typeLib, strTypeLibName, Path.GetDirectoryName(strTypeLibName));
            return typeLib;
        }
    }
}

```

**Comment by domehead100** [comment]
Hi Folks,
Just saw this thread pop up again in e-mail.  We struggled with RegAsm quite a lot.  After initial success using the ComVisible attribute, more problems cropped up.

Our app was a COM server but also a WPF app.  Here are comments that I left in the our project at the time in a static constructor for our main window class.  It might help. 

The key point is that RegAsm executes in a different context than when the app is actually running, and you can use that to bail out early and stop RegAsm from reflecting on all dependent assemblies that it finds.

Hope this helps.

```cs
       static MainWindow2()
        {
            using (Logger.Profile())
            {
                // damn RegAsm will execute this code in a "reflection context" and then notice that MainWindow2
                // is a WPF object and then complain that it must be run in an STA thread, which RegAsm is not using
                // (it's apparently using an MTA thread), even though our custom entry point specifically creates an STA thread.
                // This hack prevents the MainWindow2 from even being instantiated in a "reflection context" because
                // in that case there is no Application.Current object.
                // This allows RegAsm to work, because it won't try and reflect on anything related to MainWindow2.
                if (Application.Current != null)
                    Instance = new MainWindow2();
                else
                {
                    EpicBridgeWbc.RunningInRegAsm = true;
                }
            }
        }
```

**Comment by LubosVoska** [comment]
I have same problem with Regsam. Adding  [ComVisible(true)] not working. Any idea how to solve this? @harmonypiano solution works fine but don't want to run this on all client machines. Just want to use regular regsam.
