### ISSUE TITLE
Incompatibility with Windows Services

### ISSUE THREAD

**Issue by JustArchi** [Fody/Costura#164]
It seems that binary which has been repacked using Fody/Costura is not possible to install via standard `InstallUtil.exe` utility being used for that purpose.

`System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types`

It seems the number of those exceptions is equal to number of missing libraries.

In order to reproduce the problem, repacked binary must be a valid Windows Service - https://msdn.microsoft.com/library/zt39148a(v=vs.110).aspx

Extra notice: binary repacked using `ILRepack` installs successfully.

**Comment by distantcam** [comment]
Costura relies on adding a hook to the app domain to help resolve assemblies when the merged assembly runs. There is now a way to add this hook manually.

https://github.com/Fody/Costura#costurautility-link

You will need to do this in the startup of the windows service.

**Comment by JustArchi** [comment]
Sadly this didn't work for me. I put Costura initializer as static class initializer in both Program and class inheriting from `Installer` but that didn't fix `InstallUtil.exe` not capable of installing repacked exe as valid Windows service.

> An exception occurred during the installation phase.
> System.InvalidOperationException: Unable to get installer types in ASF.exe.
> An internal exception occurred System.Reflection.ReflectionTypeLoadException with the following error message: Unable to load one or more requested types. For more information, download the LoaderExceptions property.

**Comment by TheMiller2015** [comment]
Hello, I', facing the same problem. Also tried to call the hook, but without any effect. I also got the same error message (ReflectionTypeLoadException). Can somebody tell me, in what way we have to use costura when creating a windows service - or are services unsupported? Thanks in advance!

**Comment by SimonCropp** [comment]
@TheMiller2015 this is a very old issue. please raise a new issue and follow the issue template

**Comment by ispysoftware** [comment]
is this supposed to work with windows services? ('cause it doesn't) The link above to #costurautility-link is broken

**Comment by SimonCropp** [comment]
yes it does work with windows services. you have likely found a bug or have something wrong with your setup. please raise a new issue and follow the issue template
