### ISSUE TITLE
Costura to clean up resource sub-directories

### ISSUE THREAD

**Issue by CraigN** [Fody/Costura#165]
I've installed the CleanReferences target and I notice that locale resource sub-directories for assemblies like FluentValidation are left behind. Can an option be added into Costura to do this in the CleanReferences target?

**Comment by Bounder** [comment]
I take it these directories are empty?
I had the same issue and after some searching on the web I came across the following script:

`  <Target Name="CleanEmptyDirs" AfterTargets="CleanReferenceCopyLocalPaths">
    <ItemGroup>
      <Directories Include="$([System.IO.Directory]::GetDirectories('$(OutDir)', '*', System.IO.SearchOption.AllDirectories))" />
      <Directories>
        <Files>$([System.IO.Directory]::GetFiles("%(Directories.Identity)", "*", System.IO.SearchOption.AllDirectories).get_Length())</Files>
      </Directories>
    </ItemGroup>
    <RemoveDir Directories="@(Directories)" Condition="%(Files)=='0'" />
  </Target>`

As you can see it runs after clean reference task and removes any subs that don't contain any file. Perhaps someone can make an installation command like clean refs for this script and add it to the project or make it a default part of the clean refs script.
