### ISSUE TITLE
How to specify bindingRedirect needed for embeded asemblies

### ISSUE THREAD

**Issue by MuiBienCarlota** [Fody/Costura#169]
I run into a problem where I use costura to simplify delivery of a small tools. My goal is to be able to provide a single tool.exe with no other file needed.

Using costura permits me to embed each needed externals assemblies. But this assemblies needs a tools.exe.config to resolve assembly version with bindingRedirect.

It works when using an external tool.exe.config with bindingRedirect but I miss my "simple delivery" goal and it's unlikely that end user may wish to change bindingRedirect about assemblies they are not supposed to know.

Do you have a way to embed these bindingRedirect into my exe?

I know ["sorry but costura is about merging .dlls. other static files and config is not a problem it is trying to solve"](https://github.com/Fody/Costura/issues/155#issuecomment-218764306) but this bindingRedirects are strongly linked to embeding assemblies. It could make sense to also embed them.

**Comment by SimonCropp** [comment]
if this is still a problem in v2 can u please upload a minimal solution that reproduces the issue
