### ISSUE TITLE
Cleanup Target deletes Excluded Assemblies

### ISSUE THREAD

**Issue by BennyBread** [Fody/Costura#172]
If you add ExcludedAssemblies to the FodyWeavers.xml file and the Cleanup Target is installed in the project the excluded Assemblies will be deleted on build from the output folder.

**Comment by Lakritzator** [comment]
As far as I understood the process, the "CleanReferencesTarget" deletes all assemblies marked with "Copy Local". Nothing else.

On top of that, it says in the documentation:

> Note that this does not handle ExcludeAssemblies or IncludeAssemblies options mentioned above. You will have to handle these explicitly.

Maybe you already knew, and this is a feature request :smile:

**Comment by distantcam** [comment]
As of 1.6 there's now a cleanup task that works properly with the Costura settings.
