### ISSUE TITLE
Costura forces PDB generation

### ISSUE THREAD

**Issue by Bilge** [Fody/Costura#174]
Costura forces a PDB to be generated and linked into the target executable even when [PDB generation has been explicitly disabled in the build options](http://stackoverflow.com/a/2371056/1041515). Costura must not override my preference to disable PDB generation.

**Comment by distantcam** [comment]
See discussion https://github.com/Fody/Fody/issues/278

**Comment by Bilge** [comment]
You could not be more wrong. Removing Fody immediately ceases generating
and linking the PDB. Ergo it is a fault with this software.

**Comment by distantcam** [comment]
Regardless, this isn't caused by Costura.
