### ISSUE TITLE
Costura.Fody Doesn't Work In Rider EAP

### ISSUE THREAD

**Issue by redxtech** [Fody/Costura#178]
This product works fine in Visual Studio, but when I try to use it in JetBrains Rider EAP, Fody doesn't include the required dlls in the compiled exe.
The other dlls I'm using are:
 - CsQuery
 - RestSharp
 - Newtonsoft.Json

I have tried adding this to the weavers file, but it doesn't do anything different:
```
<Costura>
	<IncludeAssemblies>
		CsQuery
		Newtonsoft.Json
		RestSharp
	</IncludeAssemblies>
</Costura>
```

Any solutions?

**Comment by distantcam** [comment]
Costura 1.4.1 should now work.
