### ISSUE TITLE
Order of options in FodyWeavers.xml

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [Fody/Costura#179]
In trying to not embedded the pdb's you are to use `<Costura IncludeDebugSymbols='false'/>`

So I have this: 

`<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <Costura>
     <PreloadOrder>
      IPManager
    </PreloadOrder>
    <Unmanaged32Assemblies>
      IPManager
    </Unmanaged32Assemblies>
   </Costura>
  <Costura IncludeDebugSymbols='false'/>
</Weavers>`

Should the IncludeDebugSymbols be in the single Costura tag? If I put it at the top it's ignored, At the bottom and it works but messes up the PreloadOrder.

**Comment by distantcam** [comment]
Yes there should only be 1 Costura tag.
