### ISSUE TITLE
System.Reflection.Assembly.GetExecutingAssembly().Location ERROR

### ISSUE THREAD

**Issue by pengzai123** [Fody/Costura#180]
System.Reflection.Assembly.GetExecutingAssembly().Location  is  ""

**Comment by moh-hassan** [comment]
I tried Costura.Fody using last stable version 1.3.3.0 from nuget in vs 2015 and it return valid value.

In main console application, I get:

GetExecutingAssembly, in main application:
 F:\Users\admin\Documents\Visual Studio 2015\Projects\Fody.Costura.Demo\Fody.Costura.Demo\bin\Debug\Fody.Costura.Demo.exe

In Referenced class library, I get:

GetExecutingAssembly, from within  Referencced lib :
 F:\Users\admin\Documents\Visual Studio 2015\Projects\Fody.Costura.Demo\Fody.Costura.Demo\bin\Debug\Costura.Lib.dll

Can you try using that version?

**Comment by Lakritzator** [comment]
I'm not sure if this is the right place to report this issue, the executing assembly might not be loaded by Costura.

In the documentation of the [Assembly.Location](https://msdn.microsoft.com/en-us/library/system.reflection.assembly.location(v=vs.110).aspx) property it says:

> If the assembly is loaded from a byte array, such as when using the Load(Byte[]) method overload, the value returned is an empty string ("").

This might explain it..
Anyway without more information, the maintainers of this project will probably not be able to help you. They might just say, this is correct.

You might want to add more information on when the, from your standpoint bug, is present. Like what platform you use, versions etc.

**Comment by distantcam** [comment]
@Lakritzator is right, if the assembly you're trying to load is embedded by Costura then there's no location for it.

**Comment by Lakritzator** [comment]
As a workaround, you can set CreateTemporaryAssemblies to true. But you wont like the location :smile:  

`<Costura CreateTemporaryAssemblies='true' />`

**Comment by yxw** [comment]
In my case, I use 
`AppDomain.CurrentDomain.BaseDirectory`
instead. 

This seems to be a more reliable way to get the application folder, according to [this](https://stackoverflow.com/questions/6041332/best-way-to-get-application-folder-path/35295609).
