### ISSUE TITLE
Fody/Costura Stopped working with VS 2017

### ISSUE THREAD

**Issue by DSutterfield** [Fody/Costura#181]
I get a Fody Unhandled Exception error when I try to compile a VB project under VS 2017.
In effect the error is "System can't find Microsoft.Build.Framework, Version 15.1.0.0". There is no error when compiling in VS 2015.

**Comment by thetruestarr1337** [comment]
Installed Vs 2017 and got the exact same issue!

**Comment by m910q** [comment]
Confirmed for my c# 4.5.2 project as well.

**Comment by thetruestarr1337** [comment]
I updated "Fody" to the newest Version NuGet offered me and this seems to fixed my project.

**Comment by DSutterfield** [comment]
I just ran and Update-Package from NuGet.  It appears to be working.

**Comment by Virgil-z** [comment]
i can confirm that `Update-Package costura.fody` fixed my issue.
