### ISSUE TITLE
Duplicate assembly keys loaded into nullCache in ILTemplate.cs

### ISSUE THREAD

**Issue by ryno1234** [Fody/Costura#182]
I have an intermittent issue that occurs in my application where I will receive an ArgumentException "An item with the same key has already been added.". It appears this is when adding the assembly name to the nullCache dictionary.

It seems this happens when multiple requests are occurring at the same time during app-startup (IIS). I can also replicate by recycling the app pool and requesting a particular URL multiple times at once using load testing software

**Comment by Lakritzator** [comment]
I have seen this issue once for an application I wrote, so I can concur this happened.
@ryno1234 already created #183 to solve this.

**Comment by distantcam** [comment]
Please try 1.4.0
