### ISSUE TITLE
Loading Costura executables using Reflection.Assembly.Load

### ISSUE THREAD

**Issue by rvazarkar** [Fody/Costura#185]
When loading a costura executable using Reflection, it appears the embedded resources are failing to load. I tried manually calling Costura.AssemblyLoader.Attach using reflection as folllows:

```GetType("Costura.AssemblyLoader").GetMethod("Attach").Invoke($Null, @());```

However, when I call my function for my own assembly afterwards, as follows:
```GetType('SharpHound.Program').GetMethod('Main').Invoke($Null, @(,$a))```

the assemblies are not loaded, leading to the following error:

```Exception calling "Invoke" with "2" argument(s): "Could not load file or assembly 'CommandLine, Version=1.9.71.2, Culture=neutral, PublicKeyToken=de6f01bd326f8c32' or one of its dependencies. The system cannot find the file specified."```

Is there an accepted method of loading Costura assemblies using Reflection?

**Comment by impoetk** [comment]
#86 has the code to achieve it
```
var assembly = Assembly.LoadFile(@"<path to your dll>");
var assemblyLoaderType = assembly.GetType("Costura.AssemblyLoader", false);
var attachMethod = assemblyLoaderType?.GetMethod("Attach", BindingFlags.Static | BindingFlags.Public);
attachMethod?.Invoke(null, new object[] { });
```
