### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Costura#186]
Fody Version 2 is out and you will need to do an update for your addin to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency range for Fody to be at least 2.0

 Please ping me if u need help

**Comment by a44281071** [comment]
Yes, Fody throw an exception:

> Fody: The weaver assembly 'Costura.Fody, Version=1.3.3.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.2.0.

Could not use costura in visual studio 2017.

**Comment by SimonCropp** [comment]
@a44281071 if you have time a PR that updates costura to fody 2 would be appreciated

**Comment by shravan2x** [comment]
@SimonCropp This completely breaks all projects that use Costura without any standing fix. In my humble opinion, care should have been taken to prevent this.

**Comment by shravan2x** [comment]
@SimonCropp Take a look at https://github.com/Fody/Costura/pull/187.

**Comment by distantcam** [comment]
Done in v.1.4.0
