### ISSUE TITLE
Cannot Compile: Costura expected to be executed

### ISSUE THREAD

**Issue by NickVD** [Fody/Costura#190]
I suddenly cannot compile my application, and receive the following error:

`Costura expected to be executed. You may also need to manually add '<Costura />' into your FodyWeavers.xml. eg <Weavers><Costura/></Weavers>. See https://github.com/Fody/Fody/wiki/SampleUsage`

That wiki page does not exist.  I installed it through the nu-get command, and it was working just fine for about an hour or so, but after an (unrelated) reboot, I can no longer compile due to the above error.

The content of my FodyWeavers.xml file is below:

`<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <Costura/>
</Weavers>`

**Comment by ptr1120** [comment]
Same problem at my side since version Costura.Fody.1.4.

**Comment by distantcam** [comment]
Please try 1.4.1.

**Comment by ptr1120** [comment]
With version 1.41 no problems anymore. Thanks.

**Comment by NickVD** [comment]
Same here, no issues any longer.

Thanks for the super quick response!
