### ISSUE TITLE
StackOverflowException with bindingRedirect on different version

### ISSUE THREAD

**Issue by Sellec** [Fody/Costura#191]
Checked with versions 2.x.x and 1.x.x.
I have Newtonsoft.Json 9.0.0 referenced with my library MyCustomLibrary and attached to compiled MyCustomLibrary.dll with Costura.Fody.
My application, which is references MyCustomLibrary.dll, have an **<dependentAssembly>** tag in app.config.
`      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
`
When i load my appliaction, my MyCustomLibrary tries to load Newtonsoft.Json 10.0.0.0 and ILTemplate.ResolveAssembly receives assembly full name for Newtonsoft.Json 10.0.0.0. It extracts only assembly name "Newtonsoft.Json", founds its own attached "Newtonsoft.Json" (but version 9.0.0.0). Version are not compared and then it starts new cycle...

**Comment by SimonCropp** [comment]
if this still occurs in v2 can u upload a small solution that reproduces the issue
