### ISSUE TITLE
Cannot build when executing assembly has strong name

### ISSUE THREAD

**Issue by Janek91** [Fody/Costura#194]
Hi,
I'm encountering such error when building WPF application which has been signed:
`2>      Fody/Costura:   Finished 'Costura' in 1557ms `
`2>  `
`2>    Fody:   Adding weaving info`
`2>    Fody:   Finished in 7ms `
`2>  `
`2>    Fody: Using strong name key from KeyFilePath 'C:\[PATH_TO_PROJECT]\Key.pfx'.`
`2>    Fody:   Writing assembly to 'C:\[PATH_TO_PROJECT]\obj\Debug\Application.exe'.`
`2>MSBUILD : error : Fody: An unhandled exception occurred:`
`2>MSBUILD : error : Exception:`
`2>MSBUILD : error : Unable to obtain public key for StrongNameKeyPair.`
`2>MSBUILD : error : StackTrace:`
`2>MSBUILD : error :    at System.Reflection.StrongNameKeyPair.ComputePublicKey()`
`2>MSBUILD : error :    at System.Reflection.StrongNameKeyPair.get_PublicKey()`
`2>MSBUILD : error :    at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable'1 stream, WriterParameters parameters)`
`2>MSBUILD : error :    at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable'1 stream, WriterParameters parameters)`
`2>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)`
`2>MSBUILD : error :    at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18`
`2>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 88`
`2>MSBUILD : error : Source:`
`2>MSBUILD : error : mscorlib`
`2>MSBUILD : error : TargetSite:`
`2>MSBUILD : error : Byte[] ComputePublicKey()`
`2>MSBUILD : error : `
`2>    Fody:   Finished Fody 2019ms.`
`2>`
`2>Build FAILED.`
Am I doing something wrong, or is it a bug?

**Comment by distantcam** [comment]
What version of Fody & Costura were you using? This might be a Fody issue.

**Comment by distantcam** [comment]
I think this is a Fody issue. Make sure Fody is at the latest version, and let us know if you keep having problems.

**Comment by Janek91** [comment]
In fact it was related to that issue:
https://github.com/Fody/ExtraConstraints/issues/5
I've used .pfx key file - password protected, and using .snk key file - without password, everything went ok.
