### ISSUE TITLE
Request: Please add installation instructions in README.md

### ISSUE THREAD

**Issue by lwchkg** [Fody/Costura#195]
Thanks for the great project. I'm able to pack Roslyn in a single EXE file with Costura, so it's a life saver.

BTW, just proposing to add some installation instructions to README.md, so life can be easier before the actual installation. The instructions could look like this:

1. Install Costura with nuget:  `PM> Install-Package Costura.Fody`
2. Clean the project.
3. Build the project. No configuration is necessary if your assemblies are managed.
4. If some of your assemblies are not managed, see sections "Unmanaged32Assemblies & Unmanaged64Assemblies" for configuration options.

**Comment by distantcam** [comment]
There is instructions in the readme for installation, and further instructions for dealing with unmanaged assemblies.

I'm not sure what else to add. If you have any ideas on how to improve the documentation, please send in a pull request. Thanks.
