### ISSUE TITLE
Release Build fails

### ISSUE THREAD

**Issue by BennyBread** [Fody/Costura#198]
Hi, I'm using VS2017 Pro, and Compiling an WinForms Project using .Net 4.5.1

My Release version fails to build due to some exception:

`2>------ Erstellen gestartet: Projekt: TexControl, Konfiguration: Release Any CPU ------
2>    Fody: Fody (version 2.0.7.0) Executing
2>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Der Vorgang ist aufgrund des aktuellen Zustands des Objekts ungültig.
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    bei Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
2>MSBUILD : error :    bei Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
2>MSBUILD : error :    bei Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
2>MSBUILD : error :    bei Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
2>MSBUILD : error :    bei InnerWeaver.ReadModule() in C:\projects\fody\FodyIsolated\ModuleReader.cs:Zeile 32.
2>MSBUILD : error :    bei InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:Zeile 82.
2>MSBUILD : error : Source:
2>MSBUILD : error : Mono.Cecil
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Void ReadSymbols(Mono.Cecil.Cil.ISymbolReader)
2>MSBUILD : error : 
2>    Fody:   Finished Fody 3ms.
========== Erstellen: 1 erfolgreich, 1 fehlerhaft, 1 aktuell, 0 übersprungen ==========
`

But when I compile a Debug Version this works fine: 

`3>------ Neues Erstellen gestartet: Projekt: TexControl, Konfiguration: Debug Any CPU ------
3>    Fody: Fody (version 2.0.7.0) Executing
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\Crc32.NET.1.0.2\lib\net20\Crc32.NET.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\Units.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\EPPlus.4.1.0\lib\net40\EPPlus.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\PdfSharp.1.32.3057.0\lib\net20\PdfSharp.Charting.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\PdfSharp.1.32.3057.0\lib\net20\PdfSharp.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\SciChart.4.2.3.10049\lib\net45\SciChart.Charting.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\SciChart.4.2.3.10049\lib\net45\SciChart.Core.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\SciChart.4.2.3.10049\lib\net45\SciChart.Data.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\SciChart.4.2.3.10049\lib\net45\SciChart.Drawing.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\PdfSharp.1.32.3057.0\lib\net20\de\PdfSharp.resources.dll'
3>      Fody/Costura:   	Embedding 'D:\work\Viewer\packages\PdfSharp.1.32.3057.0\lib\net20\de\PdfSharp.Charting.resources.dll'
3>    Fody:   Finished Fody 694ms.
3>  TexControl -> D:\work\Release.dll
3>    Fody:   Skipped Verifying assembly since it is disabled in configuration
3>    Fody:   Finished verification in 0ms.
========== Alles neu erstellen: 3 erfolgreich, 0 fehlerhaft, 0 übersprungen ==========`

I have no special settings for Release/Debug. It was working with some older version of costura it worked.
I even looked inside the csproj-file and checked if there is an error but it seems everything is right there:
...
```
<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <PropertyGroup>
    <PostBuildEvent>rem if $(ConfigurationName) == "Release" (xcopy /Y $(TargetFileName) "V:\TexControl\")</PostBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <PostBuildEvent>xcopy /Y $(TargetFileName) "V:\TexControl\"</PostBuildEvent>
  </PropertyGroup>
<Import Project="..\packages\Fody.2.0.7\build\dotnet\Fody.targets" Condition="Exists('..\packages\Fody.2.0.7\build\dotnet\Fody.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>Dieses Projekt verweist auf mindestens ein NuGet-Paket, das auf diesem Computer fehlt. Verwenden Sie die Wiederherstellung von NuGet-Paketen, um die fehlenden Dateien herunterzuladen. Weitere Informationen finden Sie unter "http://go.microsoft.com/fwlink/?LinkID=322105". Die fehlende Datei ist "{0}".</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Fody.2.0.7\build\dotnet\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Fody.2.0.7\build\dotnet\Fody.targets'))" />
  </Target>  <PropertyGroup>
    <PreBuildEvent>
    </PreBuildEvent>
  </PropertyGroup>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
```

I have no clue why release build fails...

**Comment by erkantaylan** [comment]
Same happens to me too, vs2017 pro, .net 4.0 WPF project

```Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Operation is not valid due to the current state of the object.
StackTrace:
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at InnerWeaver.ReadModule() in C:\projects\fody\FodyIsolated\ModuleReader.cs:line 32
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
Mono.Cecil
TargetSite:
Void ReadSymbols(Mono.Cecil.Cil.ISymbolReader)	
```

**Comment by distantcam** [comment]
I can confirm this is a Fody issue. Opened Fody/Fody#333 and closing this.

**Comment by distantcam** [comment]
@BennyBread @erkantaylan as a quick fix, could you please try deleting your `obj` folders?

**Comment by BennyBread** [comment]
@distantcam Deleting the obj folder solved the issue for me. Thank you very much! The "Clean" command of VS didn't do the job.
