### ISSUE TITLE
Debug information missing

### ISSUE THREAD

**Issue by stefanloerwald** [Fody/Costura#201]
When using 
```
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <Costura />
</Weavers>
```
as FodyWeavers.xml, debug information will be lost.

This happens with Fody 2.0.8, Costura 1.4.1, .NET 4.5.2 and Visual Studio 2015.
It was working fine with Fody 1.29.4, Costura 1.3.3.0.

I don't know what info you might need besides this, so feel free to ask me.

**Comment by SimonCropp** [comment]
if this is still a problem in v2 can u upload a small solution that repoduces the issue.
