### ISSUE TITLE
Option to retain .dlls

### ISSUE THREAD

**Issue by shravan2x** [Fody/Costura#202]
After a recent Costura Upgrade, .dll files are no longer present in the output directory. This is problematic because (since Costura does not support Mono+Linux), the dll files can no longer be copied over easily.

Please add an option to retain the .dll files post-compilation.

**Comment by distantcam** [comment]
Just curious, if you're compiling for Mono+Linux, why are you using Costura?

**Comment by shravan2x** [comment]
I compile once, but use the result on both .NET+Windows and Mono+Linux. I distribute a standalone product to clients (and use Costura for this) and need the .dlls for a hosted solution on Linux.

Ideally, Costura would support Mono+Linux and I would not care for the .dlls, but in the absence of that feature, I need the .dlls left in the folder so I can easily copy them over.

**Comment by ghiboz** [comment]
same issue, after the compiling I use [ConfuserEX ](https://yck1509.github.io/ConfuserEx/)to crypt the assembly and with the 1.5 doesn't work...

**Comment by Lakritzator** [comment]
I have a few use cases where I need to disable Costura in the FodyWeavers.xml. With the 1.5 update the DLL's are automatically deleted, we needed to install the task manually before, but this even happens when Costura is disabled.

It would be nice to be able to specify this in the configuration...

**Comment by distantcam** [comment]
How are you disabling Costura?

**Comment by Lakritzator** [comment]
@distantcam Commenting it out in the FodyWeavers.xml

**Comment by distantcam** [comment]
There is now a config to disable the cleanup task in 1.5.1. https://github.com/Fody/Costura#disablecleanup

Also the cleanup task no longer runs if Costura doesn't run.

**Comment by Lakritzator** [comment]
Works like a charm!
