### ISSUE TITLE
Whitespace not being stripped in FodyWeavers.xml

### ISSUE THREAD

**Issue by jonreis** [Fody/Costura#204]
I'm using Fody v2.0.10 and Costura.Fody v1.5.0.

This used to work:

```
 <Weavers>
   <Costura IncludeDebugSymbols='false'>
     <IncludeAssemblies>
         Topshelf
 </IncludeAssemblies>
```

but now I get the error: 

`Severity	Error Fody/Costura: Assembly '         Topshelf' cannot be found (not even as CopyLocal='false')`

Note the space in the name. If I change the xml to remove the whitespace, it works fine.

```
<Weavers>
   <Costura IncludeDebugSymbols='false'>
     <IncludeAssemblies>Topshelf</IncludeAssemblies>
```

	
Not sure if this is a Fody issue or Costura?

**Comment by distantcam** [comment]
Yep, this is a Costura issue.

Fixed in 1.5.1. Thanks for the report.
