### ISSUE TITLE
Support composition

### ISSUE THREAD

**Issue by Lakritzator** [Fody/Costura#205]
I try to keep my applications, at least most of the times, modular. This means that I try to refrain from direct dependencies. By using MEF (Managed Extension Framework) via my own project Dapplo.Addons, which was written to replace the extremely bad plugin architecture of Greenshot, these modules are loaded "on demand". To make the application easier to distribute, having one executable with 40dlls ,I started using Costura which works very nice.

I had to make some small changes to Dapplo.Addons, as Costura only loads the assemblies when they are resolved, now I can specify which modules I want to have loaded.

The last issue that remains, is that to get the assembly into the resulting .exe I still need to reference them from my project. To prevent accidental code references, this is exactly what I do not want.

Is there currently some kind of solution for this, for example a command I can start which will add the assemblies later?

P.S.
The project Dapplo.Addons still lacks documentation, although it's generated via docfx I still didn't publish this yet.

**Comment by distantcam** [comment]
Oh boy. This is supported by Costura, but it's a very undocumented feature, and not easy to set up. I need to deal with that at some point.

So, what you have to do is add the assemblies you want loaded by Costura as embedded resources. Then, for each resource you're going to have to edit your project file and add a `LogicalName` node to the item, and make sure that name starts with `costura`.

```
<ItemGroup>
    <EmbeddedResource Include="SomeLib.dll">
        <LogicalName>costura.SomeLib.dll</LogicalName>
    </EmbeddedResource>
</ItemGroup>
```

**Comment by Lakritzator** [comment]
No problem, I know that problem... you don't want to know how many features Greenshot has, which no one knows about due to the lack of documentation.

I should have thought up this solution myself, as I already figured out how to load embedded dlls via costura via undocumented classes...

Anyway, I got it working but there are some disadvantages to this:

1. No compression (ofcourse I can add something for this)
2. Dependencies are not processed, now this is a lot harder to solve...

For now, thanks for the quick feedback, although not perfect this solves the issue for now.

**Comment by Lakritzator** [comment]
I started to document this a bit for my project... although far from complete, and I didn't really proof-read it...
http://www.dapplo.net/documentation/Dapplo.Addons/articles/costura.html

Don't look at the rest of the site, I will recreate it as soon as I have most basic components for Greenshot "ready" and work on my first other application is progressing.

**Comment by Lakritzator** [comment]
Just giving some feedback on the current status:

Using the workaround is not so simple as I thought, if the component uses DLL's which the main application doesn't have these need to be added too. This would work by using something like:

`<ItemGroup>
        <EmbeddedResource Include="..\project\bin\$(Configuration)\*.dll">
            <Link>costura.%(Filename)%(Extension)</Link>
        </EmbeddedResource>
    </ItemGroup>
`
Now, if 2 components use the same DLL(s) an error "Resource identifier '<your DLL>' has already been used in this assembly." is raised.

So I started using a mixed modus, load the components from a subdirectory... this causes DLL hell. I didn't figue out from where the DLL's are loaded, or if they are loaded twice, but the main issue is that I get very weird errors which I can identify as typeof(a) != typeof(a) errors (which would suggest a DLL is loaded double).

I currently couldn't check what is actually loaded, due to missing admin rights on my developer PC (don't ask) but the main issue is that we cannot control the DLL loading in detail. There is no simple way of overriding the DLL resolving (resolvers are only called when something can NOT be found).

I need to think of a good solution for making fool-proof addons... (for Greenshot and some other projects)

**Comment by Lakritzator** [comment]
Update:
The "simples" solution was to change "copy local" to false on all the DLL's references of the addon which were already in the container application.

P.S.
I was even thinking about using costura for the addon's dll, but I don't know how to enable the costura resolver on assemblies which are loaded...

**Comment by Lakritzator** [comment]
Another update:
Removing & installing nuget packages resets "Copy local" to true, so after this my workaround doesn't work. This is starting to get really annoying.

**Comment by distantcam** [comment]
lol this is why the current solution is an undocumented feature. There are many many _many_ problems with it.

**Comment by Lakritzator** [comment]
I will see where this gets me, I will find some kind of solution even if I have to write it myself!

Just to make things clear:

I removed the EmbeddedResource solution in favor of loading the files from the file-system via Dapplo.Addons. When I set "copy local" to false, costura nicely loads the embedded assemblies and everything works.

Than I did a nuget update, and started the application... back to being broken.

**Comment by Lakritzator** [comment]
@distantcam did someone already try to change the code, so everything loads in a different AppDomain? while setting this up you can disable assembly loading and have better control. I just don't know what side effects this has, it might be a solution.

**Comment by distantcam** [comment]
@Lakritzator As far as I know, yes you can set up an app domain without assembly probing. But unfortunately you don't have that control over the first AppDomain that is used to start your application.

**Comment by Lakritzator** [comment]
@distantcam Yes, but wouldn't it be possible to create a new AppDomain from the Module Initializer, and start the application in there, let the old one just sit there (potentially blocked)?

**Comment by Lakritzator** [comment]
Update for this issue:
I currently have a "dirty" workaround, as the problem should only happen in development this is acceptable. The workaround is to, as soon as possible, delete all files from the addon-directories which are already embedded by costura.

This should actually not be needed, or atleast do something, in "production" as the addons should be packaged correctly by a cake script.

I am still interested in seeing if there is a better way, to get more control over the assembly loading.

**Comment by SimonCropp** [comment]
closing this since it is a really bad idea
