### ISSUE TITLE
Issue merging unmanaged Dlls

### ISSUE THREAD

**Issue by wbuck** [Fody/Costura#206]
Currently, I have a C++/CLI wrapper project which references some OpenCV dlls. The wrapper project is then referenced by a C# library I created.
The wrapper gets correctly merged within my C# library but the OpenCV dlls are not getting merged (because they're not referenced directly by my C# proj with copy local set to true).

I put all of the OpenCV files into a costura64 folder and added the Unmanaged64Assemblies element with all the required OpenCV dlls listed into the weavers xml to no avail. 

Any help would be greatly appreciated.

**Comment by GeertvanHorrik** [comment]
I get this as well since today, might have to do with updating Costura.

Currently using this config:

```
    <Unmanaged32Assemblies>
      SQLite.Interop
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      SQLite.Interop
    </Unmanaged64Assemblies>
```

Result:

1. Files are not being embedded
2. PE verification fails

Will try to investigate and post progress here.

**Comment by GeertvanHorrik** [comment]
So embedding works now (had to make sure type was set to embedded resource). Will check why PE Verify fails.

**Comment by GeertvanHorrik** [comment]
Since my issue is a bit different, I've created a separate one at #209

@wbuck make sure that you use the configuration as described above and that the file type is set to Embedded Resource.

**Comment by wbuck** [comment]
@GeertvanHorrik Should I be placing my OpenCv libraries into a 

> costura64

 folder located in the root of my project?

**Comment by GeertvanHorrik** [comment]
Are they all unmanaged? You should only list the *unmanaged* in the Unmanaged sections. The other ones (referenced or not) should just go into <IncludeAssemblies>

**Comment by GeertvanHorrik** [comment]
And I always drag & drop the files from the lib folder into the right Costura folder holding the ALT key. Then you get a linked file in your sln and you only have to keep your lib up-to-date.

**Comment by dguder** [comment]
@wbuck If  your solution works it is ok. 
But my proposal is following:
For native (unreferenced) libraries:  use `costura32 `and `costura64` folders and embed the files as resources.
For your wrapper: Add it to the  `Unmanaged32Assemblies `and/or `Unmanaged64Assemblies` section in the weaver file.

Just my 2 ¢

**Comment by mmanna3** [comment]
I have a related issue using Emgu.CV (an OpenCV wrapper).

I added Costura32 and Costura64 folders with all my dlls in them. They are all marked as **Embedded Resource**.
![fody github](https://user-images.githubusercontent.com/23342135/35259295-cf163b30-ffe3-11e7-86b2-04e3313973ef.png)

I also completed the **Unmanaged32Assembliesand** and **Unmanaged64Assemblies** tags in the weaver file.

```
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
	<Costura>
		<Unmanaged32Assemblies>
			concrt140
			cvextern
			msvcp140
			opencv_ffmpeg330
			vcruntime140
		</Unmanaged32Assemblies>
		<Unmanaged64Assemblies>
			concrt140
			cvextern
			msvcp140
			opencv_ffmpeg330_64
			vcruntime140
		</Unmanaged64Assemblies>
	</Costura>
</Weavers>
```

My code works. But it generates an .exe file which size is 100 mb and two folders named **x64** and **x86**. The size of the folders is almost 100 mb, too. So my application occupies double the space it should. 

I tried deleting the two folders, but it doesn't work.

What can I do to solve this?

Thanks in advance!

**Comment by GeertvanHorrik** [comment]
Make sure that CopyLocal=False for the references + embedded resources.

**Comment by mmanna3** [comment]
Hi GeertvanHorrik. 

The CopyLocal was set to False and the issue continued. 
I gave up and went for another approach.

Thanks anyway.

**Comment by StefH** [comment]
@mmanna3 

If you are still interested in a solution, I did solve this by making the inclusion from the `costura32` and `costura64` conditional.

Like in de csproj:
``` xml
<ItemGroup Condition="'$(Platform)' == 'x86'">
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x86\libcrypto-1_1.dll">
      <Link>costura32\libcrypto-1_1.dll</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x86\libcurl.dll">
      <Link>costura32\libcurl.dll</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x86\libssh2.dll">
      <Link>costura32\libssh2.dll</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x86\libssl-1_1.dll">
      <Link>costura32\libssl-1_1.dll</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x86\MediaInfo.dll">
      <Link>costura32\MediaInfo.dll</Link>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup Condition="'$(Platform)' == 'x64'">
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x64\libcrypto-1_1-x64.dll">
      <Link>costura64\libcrypto-1_1-x64.dll</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x64\libcurl.dll">
      <Link>costura64\libcurl.dll</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x64\libssh2.dll">
      <Link>costura64\libssh2.dll</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x64\libssl-1_1-x64.dll">
      <Link>costura64\libssl-1_1-x64.dll</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\packages\MediaInfo.Native.17.12\build\native\x64\MediaInfo.dll">
      <Link>costura64\MediaInfo.dll</Link>
    </EmbeddedResource>
  </ItemGroup>
```
