### ISSUE TITLE
Problem with mono

### ISSUE THREAD

**Issue by Kn1fe** [Fody/Costura#207]
When im try start progman under mono i have this error, without costura all is good

`Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'MySql.Data, Ve                                                                                                                                                             rsion=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' or one of its d                                                                                                                                                             ependencies.
File name: 'MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc                                                                                                                                                             88969c44d'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not lo                                                                                                                                                             ad file or assembly 'MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToke                                                                                                                                                             n=c5687fc88969c44d' or one of its dependencies.
File name: 'MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc                                                                                                                                                             88969c44d`

**Comment by distantcam** [comment]
As of 1.6.0 there's now a manual initialization which will help with mono.

[CosturaUtility](https://github.com/Fody/Costura#costurautility-link)

**Comment by Aaron1011** [comment]
Fixed in https://github.com/mono/mono/pull/13242
