### ISSUE TITLE
Path of Assemblies In Exceptions

### ISSUE THREAD

**Issue by Zabalba** [Fody/Costura#211]
Not sure if this was already answered, but is there anyway to omit the path of where the assembly was complied into the project when an exception is thrown? Without embedding the assemblies, when an exception is thrown the path of exception is relative to the current path application. With Costura, should an exception occur when the binaries are ran on a different machine (or even on a different path from where it was complied) the path provided by the exception would not be accurate. 

ex without Costura:  "Exception at [FunctionPath](NodeStatus newstatus, String details) in [Project]\[Class].cs:line 147

ex with Costura: "Exception at [FunctionPath](NodeStatus newstatus, String details) in [DiskPathAtCompile]\[Project]\[Class].cs:line 147

**Comment by SimonCropp** [comment]
no this currently not supported
