### ISSUE TITLE
Allow execution of same assembly multiple times

### ISSUE THREAD

**Issue by zivillian** [Fody/Costura#212]
Currently I'm getting the following exception, when I try to start the same assembly a second time:

> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.UnauthorizedAccessException: Access to the path 'C:\Windows\TEMP\Costura\<HASH>\64\name.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Costura.AssemblyLoader.CalculateChecksum(String filename)
   at Costura.AssemblyLoader.InternalPreloadUnmanagedLibraries(String tempBasePath, IEnumerable`1 libs, Dictionary`2 checksums)
   at Costura.AssemblyLoader.PreloadUnmanagedLibraries(String hash, String tempBasePath, IEnumerable`1 libs, Dictionary`2 checksums)
   at Costura.AssemblyLoader.Attach()
   at .cctor()

The bug lies in [Common.cs#L63](https://github.com/Fody/Costura/blob/19d91eed17075a64285fd28e27cba992a8c0ff39/src/Costura.Template/Common.cs#L63) - the `FileShare.ReadWrite` requires write access which is not available if the dll is already loaded into another process.

Since the dll is only read in `CalculateChecksum` there should be no problem setting this to `FileShare.Read`. If the checksum matches everything would be fine, otherwise the process would fail a few lines later trying to delete the wrong dll (which would be correct since there is nothing we can do about this).

**Comment by distantcam** [comment]
Good catch! I'll try to get to this on the weekend.

**Comment by distantcam** [comment]
Could you please try 1.6.2?

**Comment by zivillian** [comment]
Sadly this hasn't fixed my problem. After further investigation I found that the root cause is a filesystem permission problem.

I'm using Costura inside a web application which is deployed multiple times on the same serrver (don't ask why). The application is running with an anonymous AppPool Identity. When the module loader extracts the binaries, the permission a set to only allow the current Identity to read the file. When the second web application tries to read the file it get's the above UnauthorizedAccessException.

I'm not sure what can be done about this. Maybe it would be possible to grant the required permission to Everyone when extracting the binaries.

As a workaround I've tried to set the appropriate permission, but was not able to get the second application working.

**Comment by distantcam** [comment]
Is it possible to not create the temporary assemblies? Using Costura in it's default mode.

**Comment by zivillian** [comment]
I don't think so, I'm trying to load an unmanaged library. Maybe I've missed something, but I tried creating a new project with only the binaries in costura32 & costura64 and it's using the temp folder.

**Comment by zivillian** [comment]
I finally found a way to manually set the required permissions. The solution was to grant Read Permissions on the folder `C:\Windows\Temp\Costura` to the `IIS_IUSRS` group.
