### ISSUE TITLE
Costura fails Travis CI build

### ISSUE THREAD

**Issue by juvlarN** [Fody/Costura#213]
I'm setting up Travis CI for my project on Github.
It looks like Costura fails the build. 
The project I want to build is this:
https://github.com/juvlarN/vibranceGUI

Entire build log available here: 
https://travis-ci.org/juvlarN/vibranceGUI/jobs/241277492
(the copy&pasted error log was awfully formatted and barely readable here on Github, so I will just link to the entire build log instead) 

Is there anything I'm missing? I tried some different build configurations but can't get it working. You can see the Build History in the travis-ci.org link along with the configurations I used for that build.

**Comment by SimonCropp** [comment]
i suspect this was dues to an old version of cecil. try v2 of costura and reopen if this is still an issue
