### ISSUE TITLE
Fody: Value cannot be null, Parameter name: instruction

### ISSUE THREAD

**Issue by dkekesi** [Fody/Costura#214]
I am getting this error when trying to embedall CopyLocal assemblies:

1>------ Rebuild All started: Project: eWay.CommonControls, Configuration: Release x86 ------
1>    Fody: Fody (version 2.1.0.0) Executing
1>      Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
1>      Fody/Costura:   	Embedding 'c:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.dll'
1>      Fody/Costura:   	Embedding 'c:\xxxxxxxxxxxxxxxxxxxxxxxxxxxx.dll'
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Value cannot be null.
1>MSBUILD : error : Parameter name: instruction
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at Mono.Cecil.Cil.InstructionOffset..ctor(Instruction instruction)
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadScope(ScopeDebugInformation scope)
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadScopes(Collection`1 scopes)
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadScope(ScopeDebugInformation scope)
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadDebugInfo()
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
1>MSBUILD : error :    at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
1>MSBUILD : error :    at Mono.Cecil.MethodDefinition.get_Body()
1>MSBUILD : error :    at ModuleWeaver.FindInitializeCalls() in C:\projects\costura\src\Costura\CallAttach.cs:line 35
1>MSBUILD : error :    at ModuleWeaver.CallAttach(Configuration config) in C:\projects\costura\src\Costura\CallAttach.cs:line 9
1>MSBUILD : error :    at ModuleWeaver.Execute() in C:\projects\costura\src\Costura\ModuleWeaver.cs:line 37
1>MSBUILD : error :    at lambda_method(Closure , Object )
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 181
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 86
1>MSBUILD : error : Source:
1>MSBUILD : error : Mono.Cecil
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void .ctor(Mono.Cecil.Cil.Instruction)
1>MSBUILD : error : 
1>    Fody:   Finished Fody 966ms.

The FodyWeavers.xml looks like this:
`<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <Costura />
</Weavers>`

**Comment by SimonCropp** [comment]
this should be fixed in v2
