### ISSUE TITLE
How to control the final icon of the generated assembly?

### ISSUE THREAD

**Issue by marcbarry** [Fody/Costura#215]
Using Costura to collapse a project of managed and unmanaged code as a console application. The console application without Costura has a custom icon, but once built with Costura the custom icon is lost.

**Comment by SimonCropp** [comment]
can u upload a small solution that reproduces the issue.

Also i suggests attempting to diagnose/fix the issue yourself

**Comment by marcbarry** [comment]
trying to reproduce now, but can't - it works as expected so closing
