### ISSUE TITLE
Loaded assemblies throw exceptions with Costura above version 1.4.1

### ISSUE THREAD

**Issue by pimpace** [Fody/Costura#217]
Hey

I don't know what exactly causes this issue, but I use NLog with costura, and above 1.4.1 NLog throws exception that "path is not of a right form" which means NLog's assembly while loading from memory "cannot see" its own path. I've tried all version up to latest. (1.6.2)

First I thought Nlog got this bug, but tested all the things.

I don't know what proper bug report/logs/etc could I offer as I don't know where could I search the causes.
Is there any significant change how Costura loads up assemblies in newer versions?

I use this FodyWeavers.xml config for embed these dlls:

```
<?xml version="1.0" encoding="utf-8"?>
<Weavers VerifyAssembly="false">
    <Costura IncludeDebugSymbols="false">
        <IncludeAssemblies>
            NLog
            NLog.Windows.Forms
        </IncludeAssemblies>
    </Costura>
</Weavers>
```

Maybe you can point to where should I start to gather bug reports. Which log/file you need, how could I provide you a better help to find this anomaly.

Thanks in advice!

**Comment by SimonCropp** [comment]
if this is still an issue in v2 please upload a small solution that repoduces the issue
