### ISSUE TITLE
Readme doc is out of date

### ISSUE THREAD

**Issue by aateeque** [Fody/Costura#218]
Just started using Costura and looks like Readme.md is quite out of date.  Root node should be `<Weavers>` to begin with...where should I look for the latest config (code or doc)?

**Comment by dguder** [comment]
IMHO: The docu is not outdated. The root node is related to the parent project [Fody](https://github.com/Fody/Fody). The docu only shows what can be configured at its child node named `Costura`. 

Default `FodyWeavers.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <Costura />
</Weavers>
```

@SimonCropp @distantcam  This default might be added to readme.md (as seen at [Fody/NullGuard](https://github.com/Fody/NullGuard#configuration))

**Comment by SimonCropp** [comment]
@dguder correct. care to submit a PR?

**Comment by dguder** [comment]
@SimonCropp I created one but only within my fork. 
So PR could be found in #269 now.
