### ISSUE TITLE
Costura doesn't cleanup merged assemblies

### ISSUE THREAD

**Issue by aateeque** [Fody/Costura#219]
Is there a config that needs to be enabled for this? I expect all the merged assemblies to be deleted from the output directory

**Comment by n00bje** [comment]
There used to be a section in the readme about this, but it got deleted. I don't know why so this might not work anymore: https://github.com/Fody/Costura/commit/c1eed801259ba3c623665c97cb22a50f004e9c8b#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by nadcraker** [comment]
How does this relate to the DisableCleanup config option?

**Comment by nadcraker** [comment]
They are not the .config and .pdb files. They are 3 DLLs that appear to be merged into my main .exe file, but for some reason are still hanging around.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
