### ISSUE TITLE
[Question] - PackageReference - does it work?

### ISSUE THREAD

**Issue by dazinator** [Fody/Costura#223]
I have added Fody and Costura to my project and followed the README, but my `<PackageReference>`s are not being woven into my output assembly. Is this supported?

**Comment by SimonCropp** [comment]
yes it is supported. if it is not working for you please upload a minimal solution that reproduces the problem

**Comment by ffMathy** [comment]
This does not work indeed. A minimal solution is very simple.

1. Make a new project.
2. Refer to Costura.Fody from that project.
3. Right click the project's References in Visual Studio and click "Convert to PackageReference".
4. The target files are removed and Costura won't work.

**Comment by ffMathy** [comment]
How about you just confirm the above steps which take the same time as downloading a repro and show me some trust? 👼

**Comment by SimonCropp** [comment]
in that case happy to accept a PR that fixes the issue

**Comment by SimonCropp** [comment]
@ffMathy out of curisouty are you using `packagereference` in an old csproj format?

https://github.com/Fody/Fody#project-formats

> not supported...Projects mixing the old .csproj format with new <PackageReference> nodes.

**Comment by afrixx** [comment]
Why not? I'm also using old csproj format and PackageReferences. Is there a solution for Fody in the meantime?
Thanks!

**Comment by tom-englert** [comment]
@afrixx that works great, since Fody 4 this is no longer a problem.
