### ISSUE TITLE
How to pack a "xxx.dll"

### ISSUE THREAD

**Issue by zwcm2007** [Fody/Costura#224]
My problem is that I have a third dll named "Leadtools.PdfEngine.dll" which cannot be added to project for reference, but my program depends on it on running. So How can I pack this dll in the output exe ? Thanks

**Comment by dguder** [comment]
Hi,

I suppose this is a native code library so you can add it as resource. 
See main readme Section [Native Libraries](
https://github.com/Fody/Costura#native-libraries-and-preloadorder)

hth

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
