### ISSUE TITLE
Does Costura supported netstandard1.4

### ISSUE THREAD

**Issue by benzsuankularb** [Fody/Costura#225]
Fody itself already supported netstandard1.4.
How about Costura?

**Comment by distantcam** [comment]
I can't remember where I discussed this before. So, supporting netstandard or netcore requires certain AppDomain abilities which are currently missing in netstandard1.4. Checking the diff for netstandard2 it looks like what Costura needs is there but I haven't tried it out yet.

Here's the specific APIs Costura needs (not exhaustive)

- https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyresolve?view=netstandard-2.0
- https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.getassemblies?view=netstandard-2.0
- https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.load?view=netstandard-2.0
- https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.loadfrom?view=netstandard-2.0

**Comment by distantcam** [comment]
Anyway, it won't be possible to support netstandard 1.4 because the required API is not there. Check issue #227 for netstandard 2.0 support.
