### ISSUE TITLE
Embedded unmanaged DLLs are not used properly

### ISSUE THREAD

**Issue by gthvidsten** [Fody/Costura#226]
I'm using [WPF-MediaKit](https://github.com/Sascha-L/WPF-MediaKit) in my application. This uses two unmanaged DLL files named `EVRPresenter32.dll` and `EVRPresenter64.dll`.
These files are added to my project as embedded resources as you can see in the following screenshot from VS2017:

![dllinsolution](https://user-images.githubusercontent.com/8248605/28995032-1fa220fa-79de-11e7-8e48-3c57304202f3.png)

My `FodyWeavers.xml` file looks like this:

    <?xml version="1.0" encoding="utf-8" ?>
    <Weavers>
      <Costura>
        <Unmanaged32Assemblies>
          EVRPresenter32
        </Unmanaged32Assemblies>
        <Unmanaged64Assemblies>
          EVRPresenter64
        </Unmanaged64Assemblies>
      </Costura>
    </Weavers>

These files are then embedded into my EXE file, and I can see them as resources when I use DotPeek to look at the contents of the EXE file:

![embeddedinexe](https://user-images.githubusercontent.com/8248605/28995042-5ff7a634-79de-11e7-84a9-565b4a3f4a0c.PNG)

However, when putting the EXE file in a separate folder from the output folder and running it, these unmanaged DLL files are not loaded properly (and WPF-MediaKit does not work properly). If I copy the two DLL files from the output folder to this separate folder the DLL files get loaded (and WPF-MediaKit works as expected).

![outputfolder](https://user-images.githubusercontent.com/8248605/28995090-7f5b0204-79df-11e7-8f99-8529c6937641.PNG)

So, it seems like the files are embedded correctly, but are not loaded. Is there anything I can do to get these DLL files to load properly, or is it simply a bug in Fody / Costura?

**Comment by dguder** [comment]
Hi, 
it looks like that you are mixing two different things. 
- Embedding as resource is for (pure) "native libraries" such as `msvcr120.dll`
- Using `Unmanaged32Assemblies` is for mixed mode (`CLI/C++`) assemblies
 
So you should use only one or the other "configuration" for your `EVRPresenter??.dll` files
See main [readme](https://github.com/Fody/Costura#unmanaged32assemblies--unmanaged64assemblies)

hth

**Comment by gthvidsten** [comment]
What would be the correct build action for the files in `costura32` and `costura64` folders for this to work properly? I used to have the same problem with the `sqlite3.dll` file which did not work with whatever is the default action, but when I changed that to an "Embedded resource", as well as having it in the `FodyWeavers.xml` file it started working.

**Comment by tripleacoder** [comment]
I too have the same problem. 
It used to work, but I am now getting "Could not load file or assembly..." errors.
The compiled file has the embedded dll's.

**Comment by Axe-Usa** [comment]
you can use other resource embedder.

**Comment by screig** [comment]
I am doing a similar thing 

![capture4](https://user-images.githubusercontent.com/4292074/36839767-e0c3d29c-1d3a-11e8-8494-77f39b913caf.PNG)

where my weavers file looks like this

<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <Costura>
    <PreloadOrder>
      Swigged_Cpp_Library
    </PreloadOrder>  
</Costura>
</Weavers>

the output window prints this out 

1>------ Rebuild All started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>    Fody: Fody (version 1.0.0.0) Executing
1>      Fody/Costura:   	**No reference to 'Costura.dll' found. References not modified.**
1>    Fody:   Finished Fody 48ms.
1>  ClassLibrary1 -> C:\LocalFolder\_CODE\ClassLibrary1\ClassLibrary1\bin\Debug\ClassLibrary1.dll
1>    Fody:   Skipped Verifying assembly since it is disabled in configuration
1>    Fody:   Finished verification in 0ms.

**Comment by SimonCropp** [comment]
that message is irrelevant to your scenario

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue

**Comment by gthvidsten** [comment]
@SimonCropp It would be nice to have a conclusive answer to my question on [Aug 19](https://github.com/Fody/Costura/issues/226#issuecomment-323489983) before you close it, though. It does seem that embedding DLLs are not working quite as expected.

**Comment by SimonCropp** [comment]
@gthvidsten happy for anyone to post an outcome they have discovered, or submit a PR that fixes any but they discover

**Comment by KeirLoire** [comment]
Had this exact problem with SSCE (SQL Server Compact Edition), spent hours how to make the native DLLs loaded with Costura Fody.

SSCE package has native DLLs (Unmanaged Assemblies):
![image](https://user-images.githubusercontent.com/16032725/187281154-56758b9d-94df-4441-a557-23ee5768a461.png)

And a Managed Assembly (which is dependent on the Unmanaged Assemblies):
![image](https://user-images.githubusercontent.com/16032725/187282007-64473dd6-02f3-40a5-9c01-43be9b8ce099.png)

## How did I make it work?
I just simply put the native DLLs into a costura32 folder with the following properties:
**Build Action:** Embedded Resources
**Copy to Output Directory:** Do not copy
![image](https://user-images.githubusercontent.com/16032725/187282569-20f4501e-83be-48a0-8bb0-f119ddf87939.png)

Then I put the managed assembly into the Unmanaged32Assemblies under FodyWeavers.xml
![image](https://user-images.githubusercontent.com/16032725/187282993-d748b889-375d-43ee-a9e5-be0803ddb869.png)

After building it into a single file, it finally works! 🥳It now finds the native DLLs fine from `%TEMP%\Costura\`

I was going nuts when I was putting the native DLLs into Unmanaged32Assemblies and spent countless hours trying to make it work.

This is the error that always occurred:
```
Unable to load the native components of SQL Server Compact corresponding to the ADO.NET provider of version 8876. Install the correct version of SQL Server Compact. Refer to KB article 974247 for more details.

Unhandled Exception: System.Data.SqlServerCe.SqlCeException: Native components of SQL Server Compact engine are not loaded. Please reinstall Microsoft SQL Server Compact.
   at System.Data.SqlServerCe.NativeMethods.ThrowIfNativeLibraryNotLoaded()
   at System.Data.SqlServerCe.SqlCeConnection.Dispose(Boolean disposing)
   at System.Data.SqlServerCe.SqlCeConnection.Finalize()
```
