### ISSUE TITLE
netstandard2.0 support

### ISSUE THREAD

**Issue by fsmirne** [Fody/Costura#227]
I'm trying to compile my app, which was just updated to netstandard2.0 and I'm getting the following error message:

Error		Fody: Only compat with desktop .net

Are you guys planning to support netstandard2.0 in the near future?
Thanks!

**Comment by fsmirne** [comment]
Also, I get the following warning during compilation:

Warning	NU1701	Package 'Costura.Fody 1.6.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by Megasware128** [comment]
The warning is normal. All .NET Framework packages you reference in a .NET Standard project generates a warning. This is by design. See "Reusing an existing .NET Framework library": https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/

**Comment by fsmirne** [comment]
I understand the warning, but I still cannot compile it when targeting asp.net core 2.0.
When targeting it, I get the original error as described in my original report:

**Fody: Only compat with desktop .net**

**Comment by jahmai** [comment]
PostSharp support for netstandard has been terrible, was hoping Fody would be different but sadly appears not :(

**Comment by shaunbowe** [comment]
I am having the same issue. Are there are any plans to offer support for .net standard 2.0?

**Comment by SimonCropp** [comment]
will accept a PR for this

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
