### ISSUE TITLE
Another better compression proposal

### ISSUE THREAD

**Issue by dimzon** [Fody/Costura#229]
1) Combine all assemblies into simple file (TAR like) first before compression. This step can dramatically reduce overall compressed size. Also this helps to not generate complex IL code with SHA1 constant hashes etc. You can save them (hashes, cpu arch for unmanaged) directly into this container. Also you can add unmanaged assembiles to this container in proper order. This allow to write generic code-just iterate container in proper order and load.

2) Optionally use 100% managed 7-z SDK LZMA encoder/decoder (stripped down compiled LZMA decoder is only 40kb IL code but LZMA compression can reduce final size a lot so this is "win" strategy)

**Comment by dimzon** [comment]
I made some research - stripped down compiled LZMA decompressor (public domain code) takes only 11kb (4kb gzipped/deflated). This decompresor is compatible with XZ archiver.

**Comment by SimonCropp** [comment]
sorry but i dont think the extra complexity in using a dif compression is worth it
