### ISSUE TITLE
Unmanaged Resource DLL location

### ISSUE THREAD

**Issue by secovel** [Fody/Costura#231]
I have a project using Fody/Costura.  It runs on Window 7/10/2003 server/2012 server/2016 server.  It uses Kafka which is based on a native C library librdkafka.dll.

Embedding the C DLLs is working fine (Thanks!), except we started using Pivotal Cloud Foundry.  Pivotal runs on Windows 2012, which doesn't have real support for containers.   Pivotal has some sort of quasi-container mostly involving Hostable Web Core.

Ok, getting to the problem.  When Costura extracts the C DLLs, it uses Path.GetTempPath + "Costura" + md5Hash.  On Pivotal this resolves to a folder where the files can be dropped, but they can't be over-written.  The folder is a global folder, it is not in a container file system (bad). 

The result is that the first time the code runs, it works fine.  If the service is restarted Costura tries to drop the files again, and it fails due to permissions, and the app dies.  If I recompile the app and run it again, it works, probably due to the md5Hash changing (var md5Hash = "To be replaced at compile time";).

What i need is **one** of the following:  
1. Control over where that file gets dropped (so I can control the permissions).
2. Costura to check if the file exists before dropping it, and not trying to overwrite it 
3. The folder "md5hash" to be generated at run-time not compile time.

3 Seems bad because it has the potential to fill the disk.
2 Might be ok because if the C DLL version changed, the whole app most likely would get recompiled.
1 is probably the best.  If it could use an environment variable to specify where to put the base-path this could be controlled by the application.  If the environment variable is set, use %whateveryoucallit% + Costura + md5hash , otherwise revert to the Temp + Costura + md5Hash.

Thanks

**Comment by secovel** [comment]
Changing the code in ILTemplateWithUnmanagedHandler to the following works on PCF and non PCF:

```
        //Create a unique Temp directory for the application path.
        var md5Hash = "To be replaced at compile time";
        var baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
        tempBasePath = Path.Combine(baseDirectory, md5Hash);
```
Is there a reason you were dumping the DLLs in the temp folder instead of the folder where the app is running?  Any thoughts on changing it to the above?

**Comment by tom-englert** [comment]
@secovel users usually have no write access to the folder where the app is running, so changing this would make the problem even worse.

**Comment by secovel** [comment]
Depends on your use-case I guess.  Having it configurable would allow multiple use-cases.  Having multiple users try to write to Temp would cause the same issue I reported.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
