### ISSUE TITLE
Costura won't pack

### ISSUE THREAD

**Issue by nguillermin** [Fody/Costura#232]
Apologies if this is a very basic question, but I'm trying to use gRPC with Costura and I get these files left out.

![image](https://user-images.githubusercontent.com/2622768/31564721-f57ddd20-b031-11e7-8f35-1777c4727b47.png)

How do I include these in the exe? Are these unmanaged assemblies?

**Comment by SimonCropp** [comment]
can u provide a minimal solution that reproduces the issue
