### ISSUE TITLE
Fody exception on release build in VS 2017

### ISSUE THREAD

**Issue by ChrisLeighton** [Fody/Costura#235]
I get the following call stack when compiling in VS2017 -

`5>    Fody: Fody (version 1.29.2.0) Executing
5>MSBUILD : error : Fody: An unhandled exception occurred:
5>MSBUILD : error : Exception:
5>MSBUILD : error : Operation is not valid due to the current state of the object.
5>MSBUILD : error : StackTrace:
5>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
5>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
5>MSBUILD : error :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
5>MSBUILD : error :    at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
5>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
5>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
5>MSBUILD : error :    at InnerWeaver.ReadModule() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\ModuleReader.cs:line 14
5>MSBUILD : error :    at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 79
5>MSBUILD : error : Source:
5>MSBUILD : error : Mono.Cecil
5>MSBUILD : error : TargetSite:
5>MSBUILD : error : Void ProcessDebugHeader()
5>MSBUILD : error : 
5>    Fody:   Finished Fody 6ms.
`

The cause is a missing DebugSymbols entry in the csproj file 

`  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
    **<DebugSymbols>false</DebugSymbols>**
  </PropertyGroup>`

You can add manually or force an add by -

1. Going to Project Properties -> Build -> Advanced... and set 'Debugging Information' to anything other than 'none'
2. Click 'OK'
3. Go back in and set back to 'none'

Can I suggest that, rather than adding RTFM into attribute comments, the author adds some exception handling and FTFS

**Comment by bp2008** [comment]
I got the same error message "Operation is not valid due to the current state of the object" when I set **Project Properties > Build > Advanced > Debugging information** to "Embedded".  There is no error if I set it to "Pdb-only", as is the default.

**Comment by SimonCropp** [comment]
does this occur with v2.4.4 of fody?
