### ISSUE TITLE
The target "FodyTarget" does not exist in the project

### ISSUE THREAD

**Issue by mestiso** [Fody/Costura#236]
ERROR: The target "FodyTarget" does not exist in the project

I get that error message when trying to build on VS 2015 with Costura v1.6.2 and Fody 2.1.3.

I can build without any problem using the same Costura version but with Fody 2.0.0 so something has happened since then.

**Comment by SimonCropp** [comment]
can u upload a minimal solution that reproduces this problem

**Comment by timothyparez** [comment]
Having the same issue

**Comment by vladano** [comment]
I got the same error when installed version 2.0.0 inside .NET 4 target framework.
Then I uninstall version 2.0.0 and install version 1.6.2 and now it's working.

**Comment by SimonCropp** [comment]
Upload a repro

**Comment by stellarbear** [comment]
Same error. Unforunately project is too big to upload

**Comment by YauhenPyl** [comment]
Got this error also: [repo](https://github.com/eapyl/crossRadio)

**Comment by bbeda** [comment]
Hi guys. I had the same issue but got it sorted. It looks like Nuget doesn't install the Fody dependency (I feel like I am missing something here) so I did it manually.
1. Install Fody
2. Add the FodyWavers.xml file

This worked fine for me

**Comment by n8allan** [comment]
Why is this closed?  Still get this error after adding Costura.Fody Nuget package and there appears to be a reproduction provided above.

**Comment by 0x25b3** [comment]
Just had this issue on ,NET 4.5 with the latest Costura.Fody 2.0.1. Turns out the Fody package was not installed automatically. After going back to 1.6.2, the Fody package appeard, it started building and I upgraded both packages to the latest version.

**Comment by SimonCropp** [comment]
@n8allan i look at that repro and it doesnt seem to be using costura. 

so if anyone else can supply a minimal repro i will look into it.

**Comment by McTopaz** [comment]
I have this problem also.

I'm using C#, Visual Studio 2015, NET-framework 4.5.2 and downloaded Costura V2.0.1 (released 2018-05-12) as a NuGET packet. 

I have made a simple solution with a class library and a Console application. The console applications has the Library's DLL-file as reference. When I installed Costura there was no any _FodyWeaver.xml_ added. So I added the FodyWeaver.xml myself. Still same problem.

I have attached my solution in this response. Just download and open the attached ZIP-file and copy the directory _TestFody_ into _C:\_. Open the solution file in Visual Studio 2015 and compile it. The problem should occur.

[TestFody.zip](https://github.com/Fody/Costura/files/2101751/TestFody.zip)

**Comment by SimonCropp** [comment]
@McTopaz can u update to the newest version of fody

**Comment by JerrodV** [comment]
I ran into this same issue yesterday (6/28/2018). Unfortunately I was not able to get the reference to show up (.Net 4.5.2). In a last attempt I installed both Fody 3.1.3 and Costure.Fody 3.1.0. The references still did not show up but the project built and the dlls were weaved into the exe as expected. Note that I also had to add the FodyWeavers.xml as described above. Hope this helps someone.

**Comment by DimitriWeb** [comment]
@JerrodV  thank you, that worked like a charm. What is the difference between Fody and Costura.Fody ? Couldn't get a clue that I had to install Fody in the Costura.Fody doc.

**Comment by JerrodV** [comment]
I really don't know what the difference is. I've used this in the past and the Costura library was not yet available. Since I'd gotten it to work without that previously, I just tried adding it and it worked. For all I know you don't even need the Costura library.

**Comment by softwarehero** [comment]
Whatever ... the Fody "product" is faulty ... as your bloggers have
discussed extensively ... with no resolution.

Fody is a waste of time.

The other solution ... you do not need "Fody" to embed DLLs ... the other
solution I linked to is superior ... or at least ... that is my opinion
after trying Fody ... having all the same problems with it everyone
discussed ... and found this other superior alternative.

Github huh ?

Stuart McColl
www.stuartmccoll.com

On Wed, Jul 18, 2018 at 11:08 AM, Benjamin Bartels <notifications@github.com

**Comment by 0x25b3** [comment]
What problems would that be? I've checked the files in the Codeproject link and I can not find any malware in the binaries and the embedded MyApp.System.Data.SQLite.dll and MyApp.System.Windows.Forms.Ribbon35.dll (didn't look too deep though) which makes you and your web page even less credible (are you from the 80s?). If there at least was some malware, we'd know what you was up to. Can any "blogger" help me out here?

**Comment by 0x25b3** [comment]
Stu, first off this is still not a blog. Secondly, most problems (like the one in this issue) are solved (hence this issue is closed). If you wasn't able to get it to work despite all the helpful information, it's your own problem. If you are not even able to name a single problem you're having (and open another issue), I'd say you should stick to your 80s tech (like used on your web page) and leave us alone. We've already got our "better answer" right here.

**Comment by BobbyCannon** [comment]
@SimonCropp just wanted to drop in and say keep up the great work. Costura as a great FREE awesome project and thank you for your work. 

@softwarehero (stu), Costura is a great project and it's creators and maintainers are awesome. You should be more respectful and appreciative. Don't want to use the software then fine but your comments are not welcome nor desired.

**Comment by softwarehero** [comment]
You guys are hilarious ... you're hiding a superior solution from people
who need it and want it.

Why don't you just share the superior solution with the group ?

I've learned an awful lot today.

Code Project - "For those who code".  Github - "For the those in should
have joined the Circus."

Stu

**Comment by softwarehero** [comment]
Keep it coming ... you guys are funny as all hell.

And I thought Github had anything to do with programming ... it's a
comedian and circus act !

A better method comes up to embed DLL references into C# EXE ... and you
guys do everything possible except make it known to those who need it.  Now
you're spending your time attacking me personally ... rather than just say
"Yes ... agreed ... there is a better method" which would have promoted
good and better programming in the Github community.

Stu

**Comment by JoshuaHatfield** [comment]
This might not reference some of the older issues, but when I was just having the problem now, I was using Costura 3.x which only works with .net 4.6+. My project is 4.5.2, and downgrading to 2.0.1 resolved my issue, but I did have to manually insert the FodyWeavers.xml file per above.

**Comment by StingyJack** [comment]
I had this problem too, and it was because NuGet installed Costura.Fody, but did not also install Fody or create the weavers xml file. Easy to fix but unexpected for sure.

The project type is net452, nuget didnt tell me anything about 3.x being restricted to net462

**Comment by McTopaz** [comment]
@StingyJack "The project type is net452, nuget didnt tell me anything about 3.x being restricted to net462"

Ah!
Is that why I couldn't update PropertyChanged.Fody and Fody?
My project is compiled in .NET V4.5.2 using PropertyChanged.Fody V2.5.9 with Fody 3.1.4.

When I yesterday tried to upgrade PropertyChanged.Fody and Fody to V2.5.12 and V3.2.7 respectivly, it failed claiming the PropertyChanged.DLL couldn't be used.
I guess the PropertyChanged DLL was for .NET 4.6.2.

**Comment by SimonCropp** [comment]
PropertyChanged still supports 4.5.2 https://www.nuget.org/packages/PropertyChanged.Fody/ 

in what manner did "it failed claiming the PropertyChanged.DLL couldn't be used."
