### ISSUE TITLE
ReflectionOnlyLoad throws exception when using Costura

### ISSUE THREAD

**Issue by TimDoesCode** [Fody/Costura#237]
I've got a project that embeds several DLLs using Fody Costuras most recent Nuget version. I am using CreateTemporaryAssembly='true', all other options are the default.

I am now trying to get a list of all referenced assemblies using Assembly.ReflectionOnlyLoad() and Assembly.GetReferencedAssemblies(). When I try to load one of the embedded assemblies using Assembly.ReflectionOnlyLoad(), it fails with a FileNotFoundException. If I turn Costura off, everything works fine.

```
Assembly root = Assembly.GetEntryAssembly();
AssemblyName[] names = root.GetReferencedAssemblies();
foreach(AssemblyName n in names)
{
  try
  {
    Assembly sub = Assembly.ReflectionOnlyLoad(n.FullName);
  }
  catch(Exception e)
  {
    //If Costura is turned on, a FileNotFoundException is thrown when one of the embedded 
    //assemblies is loaded. Unknown if CreateTemporaryAssembly='true' makes any difference.
  }
}
```

**Comment by SimonCropp** [comment]
can u upload a minimal solution that reproduces the issue

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
