### ISSUE TITLE
Include/Exclude using wildcard

### ISSUE THREAD

**Issue by tpluscode** [Fody/Costura#239]
It would be nice if instead of a list of assemblies it was possible to define the inclusion/exclusion rules using wildcards or regular expressions

``` xml
<ExcludeAssemblies>
   System.*
   ^Nancy
</ExcludeAssemblies>
```

**Comment by SimonCropp** [comment]
happy to accept a PR for this

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
