### ISSUE TITLE
Different assemblies versions on the same folder of EXE

### ISSUE THREAD

**Issue by diegoaraujolima** [Fody/Costura#242]
My application that use Costura is a app that update the others applications and DLL. Because this, it's use the Costura to embed yours assemblies and not depend the same DLLs that others applications. But i have a DLL (RestSharp) that is present on this application (with Costura) and in the same directory (because the other applications depends). When the my application starts, loads the assemblies from directory and nots from embed. I know because the version of dlls os different. How force to load from embed assembly and not from directory?

**Comment by rauenzi** [comment]
I would like to know this as well I am experiencing a similar issue and it's a fatal error for my system.

**Comment by SimonCropp** [comment]
costura plugs into the assembly load event. this event wont fire if u have that assembly in the same directory. so i dont think this can be fixed.

**Comment by rauenzi** [comment]
Not even if version numbers are different? There's no way to force a specific version?

**Comment by SimonCropp** [comment]
@rauenzi i dont know. have you tried to fix this yourself, so it works are you describe?

**Comment by rauenzi** [comment]
I did attempt it, unfortunately it did not work. I ended up recompiling the later version of the dll with a new name in order to force it to load that version.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
