### ISSUE TITLE
Could not load file or assembly 'Costura.Fody.dll'

### ISSUE THREAD

**Issue by ghiboz** [Fody/Costura#247]
hi all!
since the latest update with paket I got this error:
```
4>    Fody: Fody (version 1.0.0.0) Executing
4>MSBUILD : error : Fody: An unhandled exception occurred:
4>MSBUILD : error : Exception:
4>MSBUILD : error : Could not load file or assembly 'Costura.Fody.dll' or one of its dependencies. The system cannot find the file specified.
4>MSBUILD : error : StackTrace:
4>MSBUILD : error :    at System.Reflection.AssemblyName.nGetFileInformation(String s)
4>MSBUILD : error :    at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
4>MSBUILD : error :    at AssemblyVersionReader.GetAssemblyVersion(String path)
4>MSBUILD : error :    at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
4>MSBUILD : error :    at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
4>MSBUILD : error :    at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
4>MSBUILD : error :    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
4>MSBUILD : error :    at AddinFinder.FindAddinAssembly(String packageName)
4>MSBUILD : error :    at Processor.FindAssemblyPath(String weaverName)
4>MSBUILD : error :    at Processor.ProcessConfig(WeaverEntry weaverConfig)
4>MSBUILD : error :    at Processor.ConfigureWhenWeaversFound()
4>MSBUILD : error :    at Processor.FindWeavers()
4>MSBUILD : error :    at Processor.Inner()
4>MSBUILD : error :    at Processor.Execute()
4>MSBUILD : error : Source:
4>MSBUILD : error : mscorlib
4>MSBUILD : error : TargetSite:
4>MSBUILD : error : System.Reflection.AssemblyName nGetFileInformation(System.String)
4>MSBUILD : error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
4>MSBUILD : error : 
4>    Fody:   Finished Fody 66ms.
```
I tried to use an old version but the issue is still present... 
I tried to force the dll to load, but the issue is still present.. I think that I forgot some dll used by `costura.fody.dll`
thanks in advance!

**Comment by Axe-Usa** [comment]
you got to solve the problem?

**Comment by KevinYeti** [comment]
@Axe-Usa 
hi , I was writing my own Fody addins and I got this problem too. 
you have any idea ? 
I noticed the log : 
    Fody: Fody (version 1.0.0.0) Executing...

Is this normal ? Is this mean anything ? maybe the install.ps1 was not executed ?

**Comment by ghiboz** [comment]
@Axe-Usa I'm using `Fody = 2.2.1`, no way with the new version

**Comment by KevinYeti** [comment]
@ghiboz version 2.2.1 not work for me

**Comment by SimonCropp** [comment]
can u try with the latests fody

**Comment by ghiboz** [comment]
same thing:

> 4>    Fody: Fody (version 2.3.23.0) Executing
> 4>MSBUILD : error : Fody: Could not find a weaver named 'Costura'.
> 4>MSBUILD : error : If you have nuget package restore turned on you probably need to do a build to > download the weavers.
> 4>MSBUILD : error : Alternatively you may have added a weaver to your 'FodyWeavers.xml' and forgot > to add the appropriate NuGet package.
> 4>MSBUILD : error : Perhaps you need to run 'Install-Package Costura.Fody'. This url may provide more > information http://nuget.org/packages/Costura.Fody/ .
> 4>    Fody:   Finished Fody 64ms.
> ========== Rebuild All: 3 succeeded, 1 failed, 0 skipped ==========

**Comment by SimonCropp** [comment]
fixed in v2

**Comment by mojtabahakimian** [comment]
https://stackoverflow.com/questions/70520766/could-not-load-file-or-assembly-or-one-of-its-dependencies-the-system-cannot-fi
