### ISSUE TITLE
Reloaded library state does not change

### ISSUE THREAD

**Issue by sefai** [Fody/Costura#250]
Hi all, 

Thank you for this great tool. It does help me a lot, but today I discovered an unexpected behavior, at least for me. 

I am using the [Pkcs11Interop](https://github.com/Pkcs11Interop/Pkcs11Interop) library in my winforms project and using Costura to embed a native dll for each pkcs11 token that my application supports. In order to get some pkcs11 token related changes you need to reload the native library through Pkcs11Interop's Pkcs11 class constructor which uses LoadLibrary function internally. 

I was not getting the expected results, then I removed a native library from costura64 folder and put it besides my executable and suddenly I started getting the state changes about the pkcs11 token. 

I tried to understand how it was handled within Costura with no luck. It seems Costura is managing a cache and this cache gets in every LoadLibrary call from the pkcs11interop. I couldn't find a way to change this behavior. Can this be controlled by a config option?

Regards,

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
