### ISSUE TITLE
"The path is not of a legal form." after Windows update

### ISSUE THREAD

**Issue by reverse28** [Fody/Costura#251]
Hi. After the last update of windows 10 there is a problem with "The path is not of a legal form". this problem exists both for new projects and for the apps I created previously, this problem Costura or in my project? this never happened before and everything worked perfectly
![ftdi-1](https://user-images.githubusercontent.com/35262706/34722950-df64b51e-f559-11e7-8a45-87ec645392b4.jpg)

**Comment by reverse28** [comment]
The problem resolved itself after upgrading to the following builds (with 16299.125 to 16299.192).  the question is closed

**Comment by elitest** [comment]
Strange as I'm also getting this.  Builds fine on my dev machine, but I get this error on my clean "test" machine.

**Comment by reverse28** [comment]
Check the Windows version on your test-machine and the OS Build, I have this issue only on windows versions 1709 and OS Build 16299.125
![1](https://user-images.githubusercontent.com/35262706/34930704-e83b0e28-f9db-11e7-8616-6c85d0f1f031.jpg)

**Comment by SimonCropp** [comment]
so do we write this off as a windows bug?

**Comment by wstaelens** [comment]
Is this a bug in fody costura or in windows ? (windows 1903 build 18362.295)

**Comment by SimonCropp** [comment]
@wstaelens give you can reproduce it, can you have a go at submitting a fix?

**Comment by wstaelens** [comment]
@simoncropp working with an older version of fody costura, which I can't upgrade atm. Just figured out that ` typeof(ResLocator).Assembly.Location;` was giving me an empty string `""` and then I saw this post. But it was not clear if it was a bug in fody costura or if it was a bug in Windows/.Net Framework?

**Comment by wstaelens** [comment]
Update: I've just seen this: https://github.com/Fody/Costura/issues/180 

https://github.com/Fody/Costura/issues/180#issuecomment-296081701 
looks like it might be something normal.

**Comment by SimonCropp** [comment]
@wstaelens yeah that correct. you cant use Assembly.Location when loading a assembly via a stream
