### ISSUE TITLE
Common.cs replace custom CopyTo method

### ISSUE THREAD

**Issue by wstaelens** [Fody/Costura#252]
Can the CopyTo method in Common be replaced by the .NET implementation to copy a stream to another stream?
Recent versions of .NET have a CopyTo and CopyToAsync, so no custom code would be needed for this.

https://github.com/Fody/Costura/blob/91914d2f7d2c9f8efdd5e7a550b03f047e04ace0/src/Costura.Template/Common.cs#L182

**Comment by SimonCropp** [comment]
sounds good. want to submit a PR?

**Comment by wstaelens** [comment]
sorry, don't have time for it, just added it here.

**Comment by SimonCropp** [comment]
in that case i will close this until u have time
