### ISSUE TITLE
PDB files and cleanup

### ISSUE THREAD

**Issue by uecasm** [Fody/Costura#256]
With:

    <Costura />

It will embed all local dependencies and their PDB files, and remove both from the output directory.

With:

    <Costura IncludeDebugSymbols="false" DisableCleanup="true" />

It will embed all local dependencies without the PDB files, and remove nothing.

With:

    <Costura IncludeDebugSymbols="false" />

It will embed all local dependencies without the PDB files, and remove both the DLLs and the PDBs from the output directory.  However debugging still works because the DLLs appear to load the PDBs from the intermediate directory if they're missing from the output directory.

1. Why does cleanup remove the PDB files when they're not being embedded?
2. Why are the PDB files embedded by default when they're not needed for debugging?  I've always thought you're not supposed to ship those with releases anyway.
3. Is there some way to have different settings for these between debug and release builds?

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
