### ISSUE TITLE
Cleanup is case sensitive

### ISSUE THREAD

**Issue by uecasm** [Fody/Costura#257]
When compiling with Visual Studio, with:

    <Costura ExcludeAssemblies="test" />

And a file on disk actually called `Test.dll` (note difference in case), then Costura 1.6.2 will (correctly) not embed the assembly but also (incorrectly) delete it.

If the setting is changed to "Test" then it works as expected.

Either both should be case-sensitive or neither should be; a mix of the two is problematic.

(Also, why does this use pipe-delimited values when semicolon-delimited values are more typical?  Newline delimitation is also unusual for XML files, since they can be lost unless you explicitly request whitespace preservation.)

**Comment by SimonCropp** [comment]
happy to accept a PR for this

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
