### ISSUE TITLE
OracleVM and Fody / Costura lying in shared folder

### ISSUE THREAD

**Issue by Battroid** [Fody/Costura#259]
Hi there,

I assume I only have a beginners Problem . I've been using Fody / Costura for an XLL on a local machine, worked fine. Now I have an Oracle virtual machine and my Project lies on a drive that is "mapped" into the vm via "Shared Folders". It's called D_DRIVE and is used with D:.

My XLL compile always worked fine, now it doesn't anymore. I started a new Project and tried to add Fody / Costura via install-package. I get this:

Die Datei "D:\TEST.NET\packages\Costura.Fody.1.6.2\tools\install.ps1" kann nicht geladen werden. Die Datei "D:\TEST.NET\packages\Costura.Fody.1.6.2\tools\install.ps1" i
st nicht digital signiert. Das Skript wird auf dem System nicht ausgeführt. Weitere Informationen erhalten Sie mit "get-help about_signing"..
Bei Zeile:1 Zeichen:2
+ & <<<<  'D:\TEST.NET\packages\Costura.Fody.1.6.2\tools\install.ps1' $__rootPath $__toolsPath $__package $__project
    + CategoryInfo          : NotSpecified: (:) [], PSSecurityException
    + FullyQualifiedErrorId : RuntimeException
 

When I compile I get this:

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Unerwarteter Fehler bei der Fody.WeavingTask-Aufgabe.
System.TypeInitializationException: Der Typeninitialisierer für "ContainsTypeChecker" hat eine Ausnahme verursacht. ---> System.IO.FileLoadException: Die Datei oder Assembly "file:///D:\TEST.NET\packages\Fody.2.0.0\FodyIsolated.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515) ---> System.NotSupportedException: Es wurde versucht, eine Assembly von einer Netzwerkadresse zu laden, was in früheren Versionen von .NET Framework zum Ausführen der Assembly als Sandkastenassembly geführt hätte. In dieser Version von .NET Framework wird die CAS-Richtlinie standardmäßig nicht aktiviert, dieser Ladevorgang kann daher gefährlich sein. Wenn Sie nicht beabsichtigen, durch diesen Ladevorgang eine Sandkastenassembly zu erstellen, aktivieren Sie den loadFromRemoteSources-Schalter. Weitere Informationen finden Sie unter "http://go.microsoft.com/fwlink/?LinkId=155569".

   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   bei System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   bei System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   bei System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   bei System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
   bei System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   bei System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   bei System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   bei System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   bei ContainsTypeChecker..cctor() in C:\projects\fody\Fody\ContainsTypeChecker.cs:Zeile 18.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei ContainsTypeChecker..ctor()
   bei Processor..ctor() in C:\projects\fody\Fody\Processor.cs:Zeile 29.
   bei Fody.WeavingTask.Execute() in C:\projects\fody\Fody\WeavingTask.cs:Zeile 44.
   bei Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   bei Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Excel-Sheet-QA			

I searched the net and found some stuff but nothing helped:

App.config

  <runtime>
    <loadFromRemoteSources enabled="true"/>
  </runtime>

Windows Shell security stuff... Whatever. It doesn't work.

I am lost a bit. Any advice what I can do to get the Project compiled?

Thanks in advance
Norman

**Comment by SimonCropp** [comment]
fody does not support network drives https://github.com/Fody/Fody/wiki/BuildingFromANetworkShare
