### ISSUE TITLE
Costura.Fody 2.0.0 FodyWeavers.xml not found

### ISSUE THREAD

**Issue by marb99** [Fody/Costura#270]
hi...

I use this  in Package Manager "Install-Package Costura.Fody -Version 2.0.0"

and I can't found in my project folder or solution the FodyWeavers.xml

when compiling gives this error.

I use VS 2017

![capturar](https://user-images.githubusercontent.com/7856897/38393691-86806e80-3923-11e8-9c3f-1a809832fb78.PNG)

In Costura.Fody -Version 1.6.2 works fine

**Comment by SimonCropp** [comment]
MIcrosoft is dropping support for nugets being able to add those files. So u need to do it manually https://github.com/Fody/Fody

**Comment by marb99** [comment]
ok, thanks ;)
