### ISSUE TITLE
In latest version DisableCleanup seems to defaut to true not false.

### ISSUE THREAD

**Issue by scottgal** [Fody/Costura#271]
Since updating to 2.0.0 noticed that the <Costura DisableCleanup='' /> defaults to true instead of false as previously. 
No huge issue but the front page documentation is  wrong as a result.

**Comment by SimonCropp** [comment]
yeah i think this should still be `false` but default. i will fix it

**Comment by masters3d** [comment]
I think perhaps the issue here the [double negative](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap). Perhaps it should be named `EnableCleanup` instead

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
