### ISSUE TITLE
Unsupported FodyWeavers.xml at solution level

### ISSUE THREAD

**Issue by chrs84** [Fody/Costura#272]
FodyWeavers.xml is not found at solution directory.

This has already been fixed here:
https://github.com/Fody/Fody/issues/363

Here is the correct version: https://github.com/Fody/Fody/blob/master/Fody/ConfigFileFinder.cs

However Costura still throws an error in that case: https://github.com/Fody/Costura/blob/master/Costura.Tasks/ConfigFileFinder.cs

**Comment by SimonCropp** [comment]
Can u submit a pr

**Comment by chrs84** [comment]
can you please copy the file I linked?

**Comment by SimonCropp** [comment]
Anyone else want to fix this?

**Comment by MaxxWyndham** [comment]
I've raised PR #277 
Hope this helps.

**Comment by SimonCropp** [comment]
@MaxxWyndham thanks
