### ISSUE TITLE
Cleanup modes

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Costura#273]
At the moment we have 2 options:

- Clean up
- Don't clean up

However, in combination with assembly verification, non of the options really works (you either get false positives on missing assemblies or don't get anything for missing assemblies).

My idea is to support 3 modes and make the current method obsolete:

- None => same as current disablecleanup=true
- AllExceptEmbedded => clean up all *except* the assemblies embedded by costura
- All => same as current disablecleanup=false (default)

This allows anyone that uses this to successfully combine assembly verification and costura without optionally missing assemblies that should have been included.

And as always I am happy to PR.

**Comment by SimonCropp** [comment]
@GeertvanHorrik happy to defer to you on this decision

**Comment by SimonCropp** [comment]
@GeertvanHorrik will close for now. let me know if u get the time to do this
