### ISSUE TITLE
Programmatically install all assemblies to disk

### ISSUE THREAD

**Issue by ffMathy** [Fody/Costura#274]
How can I (at runtime) install all my assemblies to disk from the embedded resources?

I need this because I want to register something into the GAC from the disk.

**Comment by SimonCropp** [comment]
it sounds like you should be writing an installer. not using costura

**Comment by ffMathy** [comment]
That's the thing. The executable is "portable" per se, it will install itself.

**Comment by SimonCropp** [comment]
sorry this is not a scenario costura is trying to solve
