### ISSUE TITLE
Could not find a weaver named "Costura"

### ISSUE THREAD

**Issue by kyriacosmichael** [Fody/Costura#276]
I am posting the issue here, however it is not related to Costura but to any Fody weaver.

Issue: Fody cannot find Costura weaver (or any other weavers) 
if a custom repository path is specified in
c:\Users\\{user}\AppData\Roaming\NuGet\NuGet.Config

Steps to reproduce.
1. Add custom repositoryPath in %appdata%\NuGet\NuGet.Config
```
<configuration>
    <config>
    <add key="repositoryPath" value="x:\packages" />
  </config>
  ...
```

2. Create a test solution
e.g. c:\projects\Solution1\Solution1.sln
Add a test project
e.g. c:\projects\Solution1\Project1.csproj

3. Install Costura.Fody 2.0.0.0
   Add weaver like
```
<Weavers>
  <Costura></Costura>
</Weavers>
```

Notice that Costura.Fody.2.0.0 is now located in
  x:\packages\Costura.Fody.2.0.0\
and not in 
  c:\projects\Solution1\packages\Costura.Fody.2.0.0\

4.  Rebuild solution
  expected result: to build OK
  actual result: Could not find a weaver named "Costura"
  workaround:
  a) copy folder x:\packages\Costura.Fody.2.0.0\ to c:\projects\Solution1\packages\Costura.Fody.2.0.0\
  b) now it builds OK

**Comment by SimonCropp** [comment]
can u try moving to the new csproj system

**Comment by kyriacosmichael** [comment]
Hi Simon.
I am not sure what the new csproj system is. What is it please?

**Comment by SimonCropp** [comment]
@kyriacosmichael https://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/

**Comment by kyriacosmichael** [comment]
With the new csproj file format it works OK.
Any chance we can have this fixed for the standard csproj format.
The problem started with a release of Fody around 7-8 months ago.

--

Here is my sample csproj for .Net Framework 4.7.1
<Project Sdk="Microsoft.NET.Sdk">  

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="2.0.1" />
    <PackageReference Include="Fody" Version="3.0.3" />
    <PackageReference Include="WriteableBitmapEx" Version="1.5.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationCore" />
  </ItemGroup>

</Project>

**Comment by kyriacosmichael** [comment]
I just noticed that with the new format it executes costura even if it is not specified in FodyWeavers.xml

e.g. 
```
<?xml version="1.0" encoding="utf-8"?>
<Weavers> 
</Weavers>
```

rebuild:
1>  Fody: Fody (version 3.0.3.0) Executing
1>    Fody/Costura:   	Embedding 'C:\Users\user\.nuget\packages\costura.fody\2.0.1\lib\net452\Costura.dll'

**Comment by SimonCropp** [comment]
@kyriacosmichael can u upload a small solution that reproduces the issue

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
