### ISSUE TITLE
Upgrade broke Fody/Costura

### ISSUE THREAD

**Issue by bigretromike** [Fody/Costura#278]
I used Fody/Cosutra combo with great success. But for some reason after upgrading both (and changing computer). The .exe that I compile dont work because it can't find Newtonsoft.Json.dll from Newtonsoft.Json.11.0.2. Fody log that he include it inside .exe with success but .exe crash with FileNotFound about dll.
Is Newtonsoft.Json.11.0.2 broken with Fody/Costura or is there any way to debug why it don't work ?

**Comment by Exeton** [comment]
I have the same issue after readding Fody/Costura to my project

**Comment by SimonCropp** [comment]
can u confirm you have ` <Costura />` in your `FodyWeavers.xml` https://github.com/Fody/Costura#configuration-options-link

and if you do have this, and it is still not working, can you upload a small solution that reproduces the issue.

**Comment by SimonCropp** [comment]
@bigretromike  also is there a reason you completely ignored the issue template https://github.com/Fody/Costura/blob/master/.github/issue_template.md  ?

**Comment by SimonCropp** [comment]
`Reference Include="Costura, Version=1.6.2.0, `

that looks like a nuget byg

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
