### ISSUE TITLE
Dotnet core 2.0 console app with Visual Studio 2017 and self contained exe does not weave

### ISSUE THREAD

**Issue by BartNetJS** [Fody/Costura#281]
I've just created a dotnet core 2.0 console app and published it as a self contained exe.
But the dll's are not weaved into the exe.

**Comment by BobbyCannon** [comment]
I'm pretty sure that Costura doesn't support .NET Core.

**Comment by SimonCropp** [comment]
i wont have time to look into this. if u want to it fixed you will need to submit a PR .

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
