### ISSUE TITLE
Handling deps.json file in .NET Core applications

### ISSUE THREAD

**Issue by carntzen92** [Fody/Costura#282]
I originally posted this question here: https://stackoverflow.com/q/50648023/2957232

Essentially, if you add Fody/Costura to a .NET Core application and include assemblies to be embedded, the referenced assemblies are still mentioned in the [app].deps.json manifest. Therefore, even though the assemblies are embedded, dotnet still looks into [app].deps.json and throws an error because this assembly obviously is no longer in the output directory. Manually editing [app].deps.json to remove any mention of the embedded file(s) and rerunning the Core application cause it to run as expected.
Manually editing this file after each build is costs, and a simple tool in the post-build step could handle this, but is it possible to get this functionality into Costura?

I have also attached a simple .net core app and .net standard library that replicates the issue. 
The code is meant to display "Hello, World!", but calling "dotnet FodyTestApp.dll" will throw an error of "_An assembly specified in the application dependencies manifest (FodyTestApp.deps.json) was not found_". Manually removing the sectionsin this file mentioning TestLibrary fixes the problem and causes the application to run as expected, displaying "Hello, World!".
[FodyTestApp.zip](https://github.com/Fody/Costura/files/2063756/FodyTestApp.zip)

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue

**Comment by viveleltsi** [comment]
I have the same issue
