### ISSUE TITLE
Can't Obfuscate with Costura Embbeding Bunifu DLL

### ISSUE THREAD

**Issue by b1scoito** [Fody/Costura#287]
Hello, i'm trying to obfuscate a file with Costura.Fody embbed, and i got this error on ConfuserEx. 

- [ERROR] Failed to resolve dependency of 'asd.exe'.
- Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Bunifu_UI_v1.5.3, Version=1.5.3.0, Culture=neutral, PublicKeyToken=null
-    at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in E:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:line 113
-    at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 264

**Comment by SimonCropp** [comment]
That stack trace looks like a bug in the obfuscator. Have u raised it with them?
