### ISSUE TITLE
Use Visual Studio 2017 complie Costura 1.6.2 Failed

### ISSUE THREAD

**Issue by CoelWu** [Fody/Costura#288]
Complete as many of the following as possible

 * [ ] Uploaded a minimal solution that reproduces the problem with the fewest moving pieces. Preferably a public GitHub repository.
 * [ ] Submitted a PR (https://help.github.com/articles/about-pull-requests/) with a failing unit test.
 * [ ] Submitted a PR (https://help.github.com/articles/about-pull-requests/) with a fix.
 
Want to see Fody survive and evolve
![qq 20180630103905](https://user-images.githubusercontent.com/39617891/42120677-e2933ac4-7c51-11e8-914c-44e234d44b01.png)
? Consider supporting the collective: https://opencollective.com/fody/donate

**Comment by SimonCropp** [comment]
try removing gitversion

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
