### ISSUE TITLE
When trying to embed a CLR assembly into C# project:  Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.)

### ISSUE THREAD

**Issue by savagepanda** [Fody/Costura#289]
I have a C# project.
I have a C++ CLR project, which wraps some  native calls.

I add reference of CLR project into the C# object.
when I enable fody, I get this error during runtime:

Unable to load File or assembly...
Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.)

I currently got it working by disable including this specific assembly via the FodyWeavers.xml file, and it works fine.
i.e. 
```
<Costura >
    <ExcludeAssemblies>
      MyAssembly
    </ExcludeAssemblies>
  </Costura>
```

but ideally I want it to also embed this assembly.  Any idea why it's not working?

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
