### ISSUE TITLE
Include unreferenced build-generated dll

### ISSUE THREAD

**Issue by waxingsatirical** [Fody/Costura#290]
With aspnetcore web application the views are pre-compiled at build time into a {project name}.Views.dll

This is not referenced by the project, and I can't add it as Native Library because it doesn't exist until build time.

Any thoughts?

**Comment by waxingsatirical** [comment]
Well it's not actually much of a problem, I've just added it from the obj directory into embedded resources. Which does work. Trouble is that Mvc does not use the AppDomain.CurrentDomain to load the x.View.dll, it uses Assembly.LoadFile so back to square one.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
