### ISSUE TITLE
"An item with the same key has already been added"

### ISSUE THREAD

**Issue by AgentFire** [Fody/Costura#292]
Minimal solution that reproduces the problem with the fewest moving pieces. https://github.com/AgentFire/Costura-Bug-Example-1

Description:

1. Pure, new VS2017 "Console App" project, .net 4.7.
2. Added NuGet packages: **Costura.Fody** (Fody included), [**fastJSON**](https://github.com/mgholam/fastJSON)
3. At the very start, the Fody throws dictionary-add exception "_An item with the same key has already been added_".

Problem:

**dnSpy** revealed that **Costura** generates two equal statements instead of one, for some reason:

![](https://i.snag.gy/iq0wta.jpg)

The issue currently exists when exactly the **fastJSON** package is used. However, there might be more candidates to ruin your evening.

Although there is only one `fastJSON.dll` file in the bin folder when the Costura is turned off.

**Comment by SimonCropp** [comment]
@AgentFire  mixing the old .csproj format with new <PackageReference> nodes is not supported 

https://github.com/Fody/Fody#project-formats

**Comment by AgentFire** [comment]
Hm but it does work with dozens of other nuget packages in the very same project.
All I did is just clicked "Migrate" on project references.
I'm guessing that's now allowed for Costura.
Or is there any other way?

**Comment by SimonCropp** [comment]
unfortunately the migrate feature in VS only does the package references. it does not do a full project migration to the new sdk style of project system. you need to do that by hand.

**Comment by AgentFire** [comment]
I did migrate the project manually and you know what? It still doesn't work.
But I found this interesting thing:
![](https://i.snag.gy/7vCl3S.jpg)

It seems the **fastJSON** itself is the problem. I will contact them on the matter.
However, the Costura should not throw exceptions left and right just because some lame nuget package acts weird. Or should it?

P.S. By the way, this means that "mixing mixing the old .csproj format with new nodes" is actually supported. There are no exceptions when I use new package system and old csproj format. The libraries are packaged naturally and the executables work like a charm.

**Comment by SimonCropp** [comment]
mixing mixing the old .csproj format with new is not supported since msbuild does not surface adequate version information to fody about what packages you are using. it is most likely only working for you as a side effect of some pacakges existing in your cache, and will likely fail for you in the future

> However, the Costura should not throw exceptions left and right just because some lame nuget package acts weird. Or should it?

as i am still not sure what the issue is i cant really answer that

**Comment by AgentFire** [comment]
The issue is the **fastJSON.dll** is being referenced twice. Look at the last screenshot.
It seems weird to me. But it works fine, without Costura.
With it, however, it doesn't. It throws an exception, with the message "An item with the same key has already been added".
Now look at the very first screenshot. You can see that Fody's generated code is repeated and redundant. More over, it is the very reason this exception is thrown.

**Comment by SimonCropp** [comment]
Ok I understand. Can u submit a PR that detects this and throws a better exception

**Comment by AgentFire** [comment]
I'm not quite sure how do I do that. What is a PR?

**Comment by SimonCropp** [comment]
https://help.github.com/articles/about-pull-requests/

**Comment by SimonCropp** [comment]
let me know if you ever get around to that PR

**Comment by AgentFire** [comment]
The thing is, I'm still not sure if it **should** be fixed on your side, as opposed to the microsoft's codebase, which produces that weird referenced-library-duplication. On one hand, that's clearly their mistake or at least - an unintended behaviour, on the other hand, you may want to protect yourself against bugs here and there, and the question is - are we really have to spend our time doing so in every possible place?
