### ISSUE TITLE
Embedding dll makes anti-virus detect .exe as malware (Gen:Variant.Ursu)

### ISSUE THREAD

**Issue by evildog1** [Fody/Costura#294]
When I embed 2 dlls Microsoft.WindowsAPICodePack.dll and Microsoft.WindowsAPICodePack.Shell.dll into my project using Costura, anti-virus detected it as malware (Gen:Variant.Ursu) even i created new WinForm protect. My friend used BitDefender told me that.

Those dll i used are scanned and clean, removing Costura makes my tool clean again. I don't understand why anti-virus have to detect it as malware. Is embedding dll too abused by criminals/hackers or what?

https://www.virustotal.com/#/file/5b75aa57433e2d0b7ff2ecaba8fe39b278d99638f10479b9cf71a3502bad133b/detection

**Comment by SimonCropp** [comment]
@evildog1 sorry but you need to raise this with the virus scanning vendor. there is nothing i can do in costura to mitigate this

**Comment by evildog1** [comment]
Ok, I will try to contact them because Gen:Variant.Ursu makes non-sense. Someone said they flag some tools as malware for money. You can at least warn users who are using Costura

**Comment by SimonCropp** [comment]
> You can at least warn users who are using Costura

Good idea. send us a PR that adds that information to the readme

**Comment by imPRAGMA** [comment]
This is definitely happening, even with a simple assembly resolver that just checks by resolve name and feeds it the dll via stream from a resource causes it

**Comment by ltrzesniewski** [comment]
Well, then your anti-virus is obviously broken ¯\\\_(ツ)\_/¯

**Comment by SimonCropp** [comment]
Is this your home computer  virus scanner or your employers

**Comment by imPRAGMA** [comment]
> Is this your home computer virus scanner or your employers

VirusTotal m8

**Comment by SimonCropp** [comment]
So personal computer or work computer?

**Comment by SimonCropp** [comment]
Does it still happen if u disable compression? 
https://github.com/Fody/Costura/blob/master/readme.md#disablecompression

**Comment by bp2008** [comment]
For what its worth, one of my apps still gets detected by two engines on VirusTotal when DLLs are embedded with Costura.  I tried with version 1.6.2 and again with 4.1.0, but there's no difference.

![image](https://user-images.githubusercontent.com/5639911/94621371-5b37b380-026d-11eb-8c90-32782612c42a.png)

If I disable compression using Costura 4.1.0, one of the detections goes away and one remains.

![image](https://user-images.githubusercontent.com/5639911/94621465-94702380-026d-11eb-8771-c184ba46a07e.png)

All detections go away if I uninstall Costura and upload the exe and each dll individually, or all together in a zip file :(

**Comment by SimonCropp** [comment]
@bp2008 if you want someone to troubleshoot this your virus vendor, please let us know so we can quote you an hourly rate

**Comment by bp2008** [comment]
LOL no but since you offered maybe I'll forward to you the next guy who complains about a virus detection in an app I release.

**Comment by adubry75** [comment]
> Does it still happen if u disable compression?
> https://github.com/Fody/Costura/blob/master/readme.md#disablecompression

This fixed my issue, thank you! I will look into other Costura settings too, I didn't know it had all those settings available. That just shows how great your package works *most* of the time, normally I just install and poof it works! Only had issues on 2 projects, one intermittently and one every time (hence googling tonight) and this setting fixed the issue on the project that was constantly being detected as a virus. Thanks!
