### ISSUE TITLE
Failing to run on mono

### ISSUE THREAD

**Issue by clragon** [Fody/Costura#296]
![monembedflaws](https://user-images.githubusercontent.com/11785085/44159320-5298b900-a0b7-11e8-96f0-8c1566583b37.png)

#### Trying to run a project that has dlls embedded with costura on mono fails.

I have included `CosturaUtility.Initialize();` in the constructor of my class. 
The dll is embedded and Costura did work as seen in the [**build log**](https://hastebin.com/upakibaniw.sql) and I also checked it with [**ILSpy**](https://github.com/icsharpcode/ILSpy/releases).

It will **always** work when running on windows.

#### The projectfiles to reproduce the issue are attached in this zip file: [MonoEmbedFlaws.zip](https://github.com/Fody/Costura/files/2290899/MonoEmbedFlaws.zip)
_(comes precompiled; to recompile, run `make.sh` in a linux environment that has [**mono-complete**](https://www.mono-project.com/download/stable/#download-lin) installed **or** build the csproj files in the correct order found in `make.sh`)_

I'm not sure whether this is an issue with my setup configuration or with costura itself.

kind regards

**Comment by SimonCropp** [comment]
does it work if u embed and load the reference manually?

**Comment by clragon** [comment]
Can you explain what you mean?

**Comment by SimonCropp** [comment]
so costura does two things. embeds references as a resource, and adds some helper code to extract those resources. if you manually perform those two actions (using explicit code and not fody) does it work on mono?

**Comment by clragon** [comment]
I will try that out as soon as I can. Do you have any references regarding doing that?

**Comment by SimonCropp** [comment]
Your best path forward is to use ilspy to look at the generated assembly

**Comment by SimonCropp** [comment]
some more context https://blogs.msdn.microsoft.com/microsoft_press/2010/02/03/jeffrey-richter-excerpt-2-from-clr-via-c-third-edition/

**Comment by SimonCropp** [comment]
happy to re-open once you have done some more research

**Comment by Aaron1011** [comment]
Fixed in https://github.com/mono/mono/pull/13242
