### ISSUE TITLE
Add FodyWeavers.xml to Project on install

### ISSUE THREAD

**Issue by dba78** [Fody/Costura#298]
Hi, 

every time I install the package (resp. any Fody-Packages) in a new Project, I have to place the FodyWeavers.xml manually. 
Couldn't the installer do this for me? Would be huge ease.
On installing Fody-Packages the installer could check for the existence of the file itself and generate and/or edit accordingly.

Is this doable, or is it implemented already and my environment lacks somewhere?
BR,
Daniel

**Comment by SimonCropp** [comment]
Sorry but Microsoft removed the feature that allows this to happen.
