### ISSUE TITLE
Embedding Cross-Language Project references

### ISSUE THREAD

**Issue by dba78** [Fody/Costura#299]
Hi,

in one of my C#-Projects I need to reference a VB-Project ('xy'). Normal build is fine, as soon as I use Costura, the  project fails on runtime: 'could nor load xy, the file or one of its components missing' (free translation from german :) ).
Referencing in a VB-Project and applying costura is fine.
So I guess this is somehow related to cross-Language referencing.
Any hints/workarounds are appreciated!
BR,
Daniel

**Comment by SimonCropp** [comment]
I would suggest adding this scenario as a test to this solution (as a pr) and debug further into it

**Comment by SimonCropp** [comment]
please re-raise if u ever get around to that PR
