### ISSUE TITLE
An Unhandled Exception Occurred: Failed To Execute Weaver

### ISSUE THREAD

**Issue by protegesolutions** [Fody/Costura#301]
This error occurs consistently in a medium-sized, multi-project VB.NET 4.5.2 VS 2017 solution. I have Costura (2.0.1 with Fody 3.0.3) working fine in a smaller C# project (with Obfusca obfuscation as well).

I installed Costura (using VS NuGet) into the two target projects. (And tried a reinstall after the two expected `FodyWeavers.xml` files failed to appear in the projects. I ended up creating them manually.)

```
Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver E:\VS\Projects\ProjectName\ProjectName\packages\Costura.Fody.2.0.1\netclassicweaver\Costura.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Could not find 'System.Void'.
Type:
Fody.WeavingException
StackTrace:
   at TypeCache.FindType(String typeName)
   at ModuleWeaver.FindMsCoreReferences()
   at ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers()
Source:
FodyHelpers
TargetSite:
Mono.Cecil.TypeDefinition FindType(System.String)
```

The two main projects are of different types and are in the solution together only because they share some common code; one is a class library/plug-in while the other is a Windows desktop app with similar functionality. The error is identical for each target project.

After the automatic/default "Copy Local" functionality failed, I tried setting individual assemblies for inclusion (which I've done in another project successfully, and prefer):

```
  <Costura>
    <IncludeAssemblies>
      Newtonsoft.Json
      ...
    </IncludeAssemblies>
  </Costura>
```

Same error. **NOTE**: I'm artificially just embedding a single assembly here; normally there would be several, including project assemblies such as `Common`, `Api`, etc.

I've hunted around the forums and Issues here to no avail.

**Comment by SimonCropp** [comment]
can u try with the newest version of costura and fody

**Comment by dallinbeutler** [comment]
Mine failed in the same situation. Updated to the latest Nuget this morning and it wasn't failing in the past. my exception is similar but different: 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver {...}\packages\Costura.Fody.3.1.0\netclassicweaver\Costura.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Method not found: 'Fody.TypeSystem Fody.BaseModuleWeaver.get_TypeSystem()'.
Type:
System.MissingMethodException
StackTrace:
   at ModuleWeaver.FindMsCoreReferences()
   at ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers()
Source:
Costura.Fody
TargetSite:
Void FindMsCoreReferences()	DallinUtils			
```
It's failing on the library project with costura that builds before my program tries to compile

**Comment by protegesolutions** [comment]
@SimonCropp Not really; I'm using the last version that targets .NET 4.5.2. I need to stick with that target due to library compatibility. Normally I would use the latest stable, tho, yes.

**Comment by SimonCropp** [comment]
can someone share a repro?

**Comment by protegesolutions** [comment]
Closed? Is this issue fixed?

**Comment by SimonCropp** [comment]
i waited 3 weeks for someone to share a repro. 

happy to reopen if more information becomes available

**Comment by protegesolutions** [comment]
Not easy to share a repro as simple projects seem to be ok, complex ones, not and the solution we have is proprietary so I can't share it. I think the symptom is fairly specific, tho.

**Comment by protegesolutions** [comment]
Sure. Perhaps just leave this issue closed and we'll revert to our previous embedding method.

**Comment by r43gr** [comment]
Quick fyi: Had same issue.  Resolved by shortening the project name just a tad.  The issue is from generated files (inside obj/debug/costura) have super long file names. 

Example of one filename: DBE8B2FE9557110981412629C0D23C346A42A563.costura.system.runtime.interopservices.runtimeinformation.dll.compressed

PS. Great extension!

**Comment by derekantrican** [comment]
To chime in - I just had this same issue and I think long file names was the problem for me as well. Had my repo many folders deep (copied from a backup of another computer) and copied it up many levels. Problem solved.

**Comment by Krolik555** [comment]
> Quick fyi: Had same issue. Resolved by shortening the project name just a tad. The issue is from generated files (inside obj/debug/costura) having super long file names.
> 
> Example of one filename: DBE8B2FE9557110981412629C0D23C346A42A563.costura.system.runtime.interopservices.runtimeinformation.dll.compressed
> 
> PS. Great extension!

This solved my issue in version 5.3.0. Thank you, that would have taken forever to figure out!

**Comment by Edwardhehe** [comment]
I use lower version and this problem solved!
.net version 4.5

**Comment by Pr0xyblade** [comment]
Solved the issue by uninstalling Costura and reinstalling, then building again.
