### ISSUE TITLE
Add developmentDependency="true" in packages.config

### ISSUE THREAD

**Issue by ChristopherStamm** [Fody/Costura#303]
I am using cotura in our Projects.
We build nuget-Packages form our assemblys.
In current version of costura is then shown as dependency in our packages.

Could you please add the attribute developmentDependency="true" to the entry in packages.config
like fody does.
`<package id="Costura.Fody" version="3.1.0" targetFramework="net452" developmentDependency="true" />`

**Comment by SimonCropp** [comment]
unfortunately i need to revert this in 3.1.2, since nuget does not consume the ref lib when developmentDependency=true
