### ISSUE TITLE
FSharp.Core still copied at build process

### ISSUE THREAD

**Issue by FoggyFinder** [Fody/Costura#304]
Steps to reproduce:

1. Create F# library
2. Add Costura there
3. Create C# project 
4. Add reference to the library
5. Build

**Result:**

FSharp.Core exists on bin folder.

**Expected result:**

Absence of FSharp.Core the same as the rest dependencies of the F# library.

[MCVE.zip](https://github.com/Fody/Costura/files/2374356/MCVE.zip)

**Comment by SimonCropp** [comment]
as per the issue template 

#### Submit a PR that fixes the bug

Submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice. If you prefer someone else fix this bug for you, please donate to the [Fody OpenCollective](https://opencollective.com/fody/donate) and include a note to that effect in this issue.
