### ISSUE TITLE
Fody Costura doesn't work with linux-arm (Raspberry) dotnet compilation

### ISSUE THREAD

**Issue by juandrn** [Fody/Costura#305]
A simple console "hello world" application compiled with:
` dotnet publish -r linux-arm `

Doesn't work as expected in raspberry OS system (stretch), It need System* and Microsoft* assemblies to works, Is there a solution for linux-arm compilation?

Runtime was download from wget [wget https://download.microsoft.com/download/1/f/7/1f7755c5-934d-4638-b89f-1f4ffa5afe89/dotnet-runtime-2.1.2-linux-arm.tar.gz](https://download.microsoft.com/download/1/f/7/1f7755c5-934d-4638-b89f-1f4ffa5afe89/dotnet-runtime-2.1.2-linux-arm.tar.gz)

**Comment by SimonCropp** [comment]
does it work without fody? ie using the the raw embedded assembly approach https://blogs.msdn.microsoft.com/microsoft_press/2010/02/03/jeffrey-richter-excerpt-2-from-clr-via-c-third-edition/  ?

**Comment by SimonCropp** [comment]
will reopen when the response comes back

**Comment by juandrn** [comment]
Sorry I can't test that example for now,  but It exe depends of libs with .so extensions.

libclrjit.so
libcoreclr.so
libcoreclrtraceptprovider.so
libdbgshim.so

etc...
And I don't know if it could work in this way, but any way I'm thinking to zip all dll, so, and a files and make an .sh to execute .
