### ISSUE TITLE
Costura.Fody Nuget package doesn't bring in Fody package

### ISSUE THREAD

**Issue by birbilis** [Fody/Costura#313]
Using the Manage NuGet Packages dialog (available when right clicking a project name) in Visual Studio Community 2017, I see Costura.Fody package doesn't install Fody one, although it lists it in dependencies there. It shows a .NET Framework dependency in bold btw in that dialog and the Fody (>= 3.2.6) is shown in non-bold, so I wonder if that is related to some syntax error (and/or bug in NuGet) in the .nuspec file

* Also, once a user has installed the Costura.Fody without also having manually installed Fody themselves, at build they just see a failed message for that project with no other explanation to be easily found

* btw, installing the packages via Package Manager console instead ended-up in the package landing at the wrong project in the solution, guess documentation should explain how to select the project PM will act upon first.

**Comment by SimonCropp** [comment]
In the new package syntax nuget no longer automatically installed related packages. The dependency tree is derived at build time. U should talk to the nuget team if u want more information on that behaviour 

Did u follow the installation https://github.com/Fody/Costura/issues/313

The nuget package manager console does not install to the currently selected project in the solution explorer. It has its own drop down for target project. If it still installs in the wrong project that is a bug with nuget and u should raise it with the nuget team

I beleive the bold of the target framework is just nugets way of highlighting important information 

If you have a build error please upload a repro

**Comment by birbilis** [comment]
Another interesting thing I see is that if I install via the Package Manager Console the Costura.Fody package instead of via the Manage NuGet Packages dialog, only then I get a verbose error at build (instead of failure with no error text):

Error		The target "FodyTarget" does not exist in the project.	MyProject			

Compared to when I had added Fody package by hand, I see packages.config at Team Explorer showing the following line as having been removed:

> <package id="Fody" version="3.2.9" targetFramework="net45" developmentDependency="true" />

and at my .csproj file those are missing:

>   <Import Project="..\..\packages\Fody.3.2.9\build\Fody.targets" Condition="Exists('..\..\packages\Fody.3.2.9\build\Fody.targets')" />
> ...
>     <Error Condition="!Exists('..\..\packages\Fody.3.2.9\build\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\Fody.3.2.9\build\Fody.targets'))" />

as I said will try with new project too, this inconsistent behavior might be a NuGet issue indeed

**Comment by birbilis** [comment]
So, I just tried with a .NET 4.5 Console application new project in a new solution:

1) using the Package Manager console

----------
PM> install-package Costura.Fody

Attempting to gather dependency information for package 'Costura.Fody.3.1.4' with respect to project 'ConsoleApp1', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 0,22 ms
Attempting to resolve dependencies for package 'Costura.Fody.3.1.4' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Costura.Fody.3.1.4'
Resolved actions to install package 'Costura.Fody.3.1.4'
Retrieving package 'Costura.Fody 3.1.4' from 'nuget.org'.
Adding package 'Costura.Fody.3.1.4' to folder 'C:\Users\user\Desktop\ConsoleApp1\packages'
Added package 'Costura.Fody.3.1.4' to folder 'C:\Users\user\Desktop\ConsoleApp1\packages'
Added package 'Costura.Fody.3.1.4' to 'packages.config'
Successfully installed 'Costura.Fody 3.1.4' to ConsoleApp1
Executing nuget actions took 995,12 ms
Time Elapsed: 00:00:01.1515961

PM> update-package Fody

Update-Package : 'Fody' was not installed in any project. Update failed.
At line:1 char:15
+ update-package <<<<  Fody
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
Time Elapsed: 00:00:00.5878443
----------

and building gives:
Severity	Code	Description	Project	File	Line	Suppression State
Error		The target "FodyTarget" does not exist in the project.	ConsoleApp1			

2) Using the Manage NuGet Packages dialog at a separate new Console2 project (.NET 4.5 console app) at that same new solution as above

the Preview changes dialog says
ConsoleApp2
Installing:
  Costura.Fody 3.1.4
(don't see any mention on dependencies here)

PM seems to show output but then when that process finishes its display is cleared. Luckily at Output pane if one picks Package Manager they get the output:

Attempting to gather dependency information for package 'Costura.Fody.3.1.4' with respect to project 'ConsoleApp2', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 6,48 ms
Attempting to resolve dependencies for package 'Costura.Fody.3.1.4' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Costura.Fody.3.1.4'
Resolved actions to install package 'Costura.Fody.3.1.4'
Found package 'Costura.Fody 3.1.4' in 'C:\Users\user\Desktop\ConsoleApp1\packages'.
Package 'Costura.Fody.3.1.4' already exists in folder 'C:\Users\user\Desktop\ConsoleApp1\packages'
Added package 'Costura.Fody.3.1.4' to 'packages.config'
Successfully installed 'Costura.Fody 3.1.4' to ConsoleApp2
Executing nuget actions took 426,57 ms
Time Elapsed: 00:00:01.2854287
========== Finished ==========

build now says about 2 projects failed
1>------ Build started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
2>------ Build started: Project: ConsoleApp2, Configuration: Debug Any CPU ------
1>C:\Users\user\Desktop\ConsoleApp1\packages\Costura.Fody.3.1.4\build\Costura.Fody.targets(21,134): error MSB4057: The target "FodyTarget" does not exist in the project.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

but the error pane shows error only for ConsoleApp1

Severity	Code	Description	Project	File	Line	Suppression State
Error		The target "FodyTarget" does not exist in the project.	ConsoleApp1			

and not for ConsoleApp2 (where I used the Manage NuGet packages dialog instead of the PM)

--------------

Which leaves me scratching my head... 
have made my own packages in the past (https://www.nuget.org/profiles/birbilis) and haven't seen this occur before, so if no one can pinpoint an issue with your nuget configuration and NuGet is really broken here, my suggestion is to just change the instructions page to suggest doing instead of:

install-package costura.fody
update-package fody

the following:

install-package fody
install-package costura.fody

this will solve such issue, plus will always bring in the latest fody and costura.fody versions even if some older version of them was already installed in the project (seems the install-package does an update if it finds older version of package installed)

And same goes if one uses the Manage NuGet packages dialog (better not assume all people use command-line). They're safer to install (or update if existing) both Fody and Costura.Fody packages instead of just the Costura.Fody one

**Comment by birbilis** [comment]
here's the above test solution in case it helps (temporary link): https://we.tl/t-as9y40ZiuA

Another funny thing I just noticed regarding the Build Error message is with this new test solution if I Build or Rebuild (even if I manually do Clean solution) in between I get almost a perfect cycle of error messages, where sometimes the one for ConsoleApp1 is shown, other times the ConsoleApp2 error, other times both errors and other times none

A) none:

1>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: ConsoleApp2, Configuration: Debug Any CPU ------
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========

B) Console1 only

1>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: ConsoleApp2, Configuration: Debug Any CPU ------
1>C:\Users\user\Desktop\FodyCostua_NuGet_notBringingFody\packages\Costura.Fody.3.1.4\build\Costura.Fody.targets(21,134): error MSB4057: The target "FodyTarget" does not exist in the project.
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========

C) Console2 only

1>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: ConsoleApp2, Configuration: Debug Any CPU ------
2>C:\Users\user\Desktop\FodyCostua_NuGet_notBringingFody\packages\Costura.Fody.3.1.4\build\Costura.Fody.targets(21,134): error MSB4057: The target "FodyTarget" does not exist in the project.
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========

D) Both:

1>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: ConsoleApp2, Configuration: Debug Any CPU ------
2>C:\Users\user\Desktop\FodyCostua_NuGet_notBringingFody\packages\Costura.Fody.3.1.4\build\Costura.Fody.targets(21,134): error MSB4057: The target "FodyTarget" does not exist in the project.
1>C:\Users\user\Desktop\FodyCostua_NuGet_notBringingFody\packages\Costura.Fody.3.1.4\build\Costura.Fody.targets(21,134): error MSB4057: The target "FodyTarget" does not exist in the project.
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========

**Comment by SimonCropp** [comment]
costura only supports net46 and up

![image](https://user-images.githubusercontent.com/122666/47144997-6f01dd80-d314-11e8-8848-e7394be1924a.png)

**Comment by birbilis** [comment]
That explains why it was showing that line in bold, however it installs without complaining and then works fine (at least for console apps that I've tried) as long as one has Fody package installed too.

Any particular reason it asks for that high version of  .NET? Fody package itself doesn't seem to have any dependencies. If I understand correctly the technique used by Costura.Fody have been documented for some time now, so it should work in various older .NET versions too

**Comment by SimonCropp** [comment]
> That explains why it was showing that line in bold, however it installs without complaining and then works fine (at least for console apps that I've tried) as long as one has Fody package installed too.

if it lets u install on a lower .net framework, i would consider that a bug in nuget

> Any particular reason it asks for that high version of .NET

because i dont like spending my time supporting people who can be bothered to keep their software reasonably up to date.

**Comment by birbilis** [comment]
Given that logic, could just target the latest .NET Standard instead.

**Comment by birbilis** [comment]
So the dev has to force their own users in turn to upgrade Windows, install service packs and latest .NET (and exclude XP clients too). Sounds a bit of a "viral" policy to me

**Comment by SimonCropp** [comment]
* you dont have to update to newer versions of costura and fody. u can use older versions that target older  runtimes
 * 4.6 was released 3 years ago, i think that is a reasonable period of time to expect people to have updated.
 * i support this in my personal time. if you want older versions of .net supported i am happy to help with that though a monetary support contract.

can u move this thread over to gitter https://gitter.im/Fody/Fody we are well off tract from the orriginal issue

**Comment by birbilis** [comment]
Don't get me wrong, I appreciate your hard work to provide this in such an easy to use way.

- Fody doesn't ask itself for some .NET version (understandable since the weaves do any specific work)
- Regarding Costura it's just that I'd use a dependency for the minimum .NET runtime for which the technique works, which should be 2.x I think (assuming it's the one Jeffrey Richter had mentioned back in 2010: https://blogs.msdn.microsoft.com/microsoft_press/2010/02/03/jeffrey-richter-excerpt-2-from-clr-via-c-third-edition/ )

just my 2c, thanks again for your time
