### ISSUE TITLE
Issue installing nuget fody and costura.fody packages on visual studio 2015

### ISSUE THREAD

**Issue by Red5goahead** [Fody/Costura#324]
I got an error when try to add Fody and/or Costura packages

**This project refers to one or more NuGet packages that are not present on this computer. Use the NuGet package recovery tool to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.**

[![image.png](https://i.postimg.cc/tRsJdDTw/image.png)](https://postimg.cc/nMtnp4qG)

I take a [video][1] to explain better starting a new project

  [1]: https://streamable.com/m31cg

If I try to install other packages as ClosedXML there are no issue at all 

I'm using Visual Studio 2015 (italian version) updated to last version and Windows 10 Pro 1803

Any ideas?

**Comment by SimonCropp** [comment]
Did you read the issue template? https://github.com/Fody/Costura/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Red5goahead** [comment]
The package works. There is a problem with installation but creating FodyWeavers.xml and editing manually csproj it works
