### ISSUE TITLE
Cannot generate/embed referenced dll's

### ISSUE THREAD

**Issue by NitinM3** [Fody/Costura#327]
Hi,
I'm using fody 2.5.0 and Costura.Fody 1.6.2 in my application. Below is FodyWeavers.xml 

```
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <Costura IncludeDebugSymbols="false" />
</Weavers>
```
I'm able create single exe successfully on my local machine and referenced dll's are embedded. But on TFS build machine referenced dll's are not embedding. Dont know why this is happening? Only difference i could see the output directory paths are different. On local machine its bin/debug and on build machine it's different.

Any help would be appreciated.

**Comment by SimonCropp** [comment]
have u contributed to the fody collective? https://github.com/Fody/Fody#preamble

**Comment by SimonCropp** [comment]
please re-read the issue template and raise a new issue https://github.com/Fody/Costura/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
