### ISSUE TITLE
Costura 3.2.1

### ISSUE THREAD

**Issue by dogbrain** [Fody/Costura#341]
#### Describe the issue

A description of what the issue is and, if relevant, the expected behavior.

Costura 3.2.1 automatically cleans the output dir and ignores  DisableCleanup="true"

Expected behavior: It should respect the setting.

#### Minimal Repro

Ensure you have replicated the bug in a minimal solution with the fewest moving parts. Often this will help point to the true cause of the problem. Upload this repro as part of the issue, preferably a public GitHub repository or a downloadable zip. The repro will allow the maintainers of this project to smoke test the any fix.

Create a wpf app 
add costura, 
add random nuget package (Newtonsoft.Json for example)
edit fodyweavers and add DisableCleanup="true" to config.
build

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
