### ISSUE TITLE
Embedded assemblies don't get deleted when building to non-default directory

### ISSUE THREAD

**Issue by Abagneele** [Fody/Costura#346]
#### You should already be a Patron

I am currently NOT a Patron, but I would like to contribute by making a pull request. Just need a little starter...

#### Describe the issue

When building to a non-default output directory, the embedded assemblies don't get deleted from the output directory.

#### Minimal Repro

Just build any costura-enabled project to a non-default output folder, for example by 
`
msbuild /p:OutDir=Some\Other\OutputDir`

#### Submit a PR that fixes the bug

I really would like to do so, but I don't even have a clue as to where to get started. I couldn't even find anything where the assemblies are deleted. Do you have a hint for me?

**Comment by SimonCropp** [comment]
@Abagneele 

> To be using Fody you should be a Patron.

so u r saying you are not using fody, but still want to submit a PR?

**Comment by SimonCropp** [comment]
> I would like to contribute by making a pull request.

unfortunately this is usually as costly for the maintainers as it is for the person creating the PR https://github.com/Fody/Fody#do-i-need-to-be-a-patron-to-contribute-a-pull-request 
so a PR does not negate the fact that you should be a patron.

**Comment by anionDev** [comment]
Ok sir @SimonCropp .
Unfortunately @Abagneele and me, we are no patrons.
But is there still any solution for this issue?

**Comment by SimonCropp** [comment]
@Abagneele  the code that achieves this is here 
 https://github.com/fody/Costura/blob/master/Costura.Fody/ResourceEmbedder.cs#L170

@Abagneele @anionDev as for not being patrons, in what context are you using fody (company/OSS/charity)? Do you think the 3$ a month is too high?

**Comment by anionDev** [comment]
assuming the changes in costura 3.2.2 are not related to this issue (because i still have this problem) i try to find the bug and submit a pull request soon.

**Comment by SimonCropp** [comment]
Yeah the current release does not fix this

**Comment by GeertvanHorrik** [comment]
We are always building to a non-default directory, yet the output dependencies are cleared. You didn't enable the `DisableCleanup` flag, did you?

https://github.com/Fody/Costura/issues/352

**Comment by SimonCropp** [comment]
any update on that PR?

**Comment by darvell** [comment]
This might seem like a silly answer but have you tried also setting `OutputPath`? It is supposed to be deprecated but I think anyone who's spent enough time working with msbuild knows that half the things that are supposed to be deprecated and unused, well, aren't. After taking a quick review over the Costura codebase I didn't personally see anything that seemed out of place.
