### ISSUE TITLE
Costura is case-sensitive, but does not warn non explicitly included assemblies

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Costura#353]
As a follow-up on #352 , I think the cause was a case-sensitive comparison of the assembly names.

I believe it's caused by this code:

https://github.com/Fody/Costura/blob/master/Costura.Fody/ResourceEmbedder.cs#L90

So if I would add `catel.Core` instead of `Catel.Core`, the assembly would be ignored yet no warning is raised.

Are you open to a PR that throws a warning (or even an error) when explicitly included or excluded references are not found? In that case it looks like a configuration issue to me.

**Comment by SimonCropp** [comment]
@GeertvanHorrik open to a PR. although u now have direct commit access ;)
