### ISSUE TITLE
a bug System.InvalidOperationException for C# 

### ISSUE THREAD

**Issue by zhfly0816** [Fody/Costura#355]
hi，
   everyone， develop tools vs2017, my appliction demo  have a bug,follow 

应用程序: mysqlentityconnetction.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.InvalidOperationException
   在 System.Data.Entity.Internal.LazyInternalConnection.Initialize()
   在 System.Data.Entity.Internal.LazyInternalConnection.get_Connection()
   在 System.Data.Entity.Internal.LazyInternalContext.get_Connection()
   在 System.Data.Entity.Database.get_Connection()
   在 mysqlentityconnetction.MyModel.Model1..ctor()
   在 mysqlentityconnetction.Form1..ctor()
   在 mysqlentityconnetction.Program.Main()

in my project appconfig:
![image](https://user-images.githubusercontent.com/46883877/51458288-a0fd6280-1d8f-11e9-8e90-6adc0c8b62b5.png)

but use Costura build project,throw a exception the "Model1" is not exist or invalid

of course,if i cp the file of appconfig to the  mysqlentityconnetction.exe  same path，the application run ok！

everyone known how to do .

**Comment by SimonCropp** [comment]
@zhfly0816 can u re-read through the issue template, and ensure u have taken all appropriate actions  https://github.com/Fody/Costura/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by zhfly0816** [comment]
i'm very sorry, i just try the no action or embedded resource!but if define 
![image](https://user-images.githubusercontent.com/46883877/51460466-88447b00-1d96-11e9-966f-408a29765aa8.png)
,it can find by application in program and run ok!

**Comment by tom-englert** [comment]
> of course,if i cp the file of appconfig to the mysqlentityconnetction.exe same path，the application run ok！

Costura embedds assemblies, not configuration files! You will always need the app.config, with or without using Costura!
