### ISSUE TITLE
Costura 3.3.1 doesn't work on .NET Core

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Costura#357]
We are using this in Orc.Controls. Version 3.2.0 works fine, but whenever I upgrade to 3.3.1, it starts complaining about not being able to find assemblies.

Will investigate further soon.

**Comment by GeertvanHorrik** [comment]
I implemented this bug myself, will take full responsibility ;-)

**Comment by GeertvanHorrik** [comment]
Pushed directly to master, sorry for any inconvenience.

**Comment by SimonCropp** [comment]
want me to push this to nuget?

**Comment by GeertvanHorrik** [comment]
Would be nice, but can wait if you have other plans in the near future.

**Comment by SimonCropp** [comment]
deployed
