### ISSUE TITLE
.exe file fails when my project contains a reference as solution of another project - winform c#

### ISSUE THREAD

**Issue by DivyaZolio** [Fody/Costura#360]
My winform application contains a lot of references which is installed from NUGetpackages. I was able to create it's single executable file by installing Fody and Costura. Now my app need to add solution of another project as a reference to it. Now when creating a new exe , 
it is not working. It means that this newly added external reference is not including in the exe. Can you help how to create an exe which should include an external project solution as reference?

![stack](https://user-images.githubusercontent.com/20222431/52397921-39f4e300-2add-11e9-8814-c2224cb3a597.PNG)

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by baimengyuan** [comment]
Hello author! I also encountered, how to deal with it?

**Comment by SimonCropp** [comment]
@baimengyuan did u read this https://github.com/Fody/Costura/issues/360#issuecomment-461336509  ?

**Comment by SimonCropp** [comment]
feel free to re-raise this once you read the issue template https://github.com/Fody/Costura/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
