### ISSUE TITLE
Existing DLLs in current directory being loaded

### ISSUE THREAD

**Issue by billwjo** [Fody/Costura#370]
I have a program that updates the dlls in the local directory and I am using costura to include the references into the exe so it does not need to load the local dlls.  Costura appears to be working because now the program can run without any of the reference dlls being present, but when they are present the program appears to be loading the local dlls.  I know this because when running the program in a directory with old dlls, these dlls are being loaded and either causing issues (like MissingMethodException due to changes to the dll api or blocking the overwrite of dll).  Is there a way to ignore all local dlls on runtime?

I've looked at #230 and #334 but they do not appear to address my exact issue.  Thanks.

**Comment by tom-englert** [comment]
Assembly-loading is controlled by the system, not by Costura. Costura can only hook into the loading process.
If the system thinks it already has found a proper assembly, it will bypass any hooks and just use this assembly, so Costura has no chance to fix this.
To ensure the system does not load outdated assembly from disk, sign your assemblies with a strong name, and version them properly.
