### ISSUE TITLE
StackOverflowException with SQLite

### ISSUE THREAD

**Issue by venugopalsjce** [Fody/Costura#403]
Hello,

We are using Costura 3.3.2 version which is throwing StackOverflowException, occuring in a particular machine during development. 

We faced this issue in the same machine with the latest version of Costura as well.

How can this be get rid off? Any clues?

Let me know if you need more info in debugging this issue.

Regards,
Venu

**Comment by SimonCropp** [comment]
“We are using Costura”

How many people are in your team?

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
