### ISSUE TITLE
Startup exception in WPF apps built with MahApps.Metro package

### ISSUE THREAD

**Issue by alekdavis** [Fody/Costura#406]
After I added Costura to my WPF app, I noticed that the app would not always start: sometimes it would, sometimes it would not. I was able to trace it down to the initialization logic that raises XamlParseException with message: 

_Could not load file or assembly 'MahApps.Metro.IconPacks, PublicKeyToken=0c0d510f9915137a' or one of its dependencies. An attempt was made to load a program with an incorrect format._

![CosturaException ong](https://user-images.githubusercontent.com/2113681/59222479-7402ee00-8b7e-11e9-9c82-82c0e8538fb1.PNG)

Here is the exception details for the sample app that I am attaching:

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=Could not load file or assembly 'MahApps.Metro.IconPacks, PublicKeyToken=0c0d510f9915137a' or one of its dependencies. An attempt was made to load a program with an incorrect format.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at MahAppsCostura.MainWindow.InitializeComponent() in D:\Projects\TEST\MahAppsCostura\MahAppsCostura\MainWindow.xaml:line 1
   at MahAppsCostura.MainWindow..ctor() in D:\Projects\TEST\MahAppsCostura\MahAppsCostura\MainWindow.xaml.cs:line 27

Inner Exception 1:
BadImageFormatException: Could not load file or assembly '14666259 bytes loaded from MahAppsCostura, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Inner Exception 2:
BadImageFormatException: Bad IL format.
```

Here is my environment:

- Windows 10 (x64)
- Visual Studio 2017
- Costura.Fody v3.3.3
- Fody v4.2.1
- Fody Weavers: Costura

To duplicate the issue, open the attached solution in Visual Studio, run the `Update-Package -reinstall` command from the Package Manager Console, build the solution and run the `Debug - Start Debugging` command (or press `F5`). Since this exception happen sporadically, there is a good chance that it will work fine for a few (possibly, many) tries, but if you keep banging it, it will eventually happen (took me about 10 tries for the sample app, while my app fails once every 3-4 runs or so).

P.S. I thought that it may be a timing issue and added a 0.5 sec delay before calling `InitializeComponents` (inside of the `try-catch` block), and it caused a BSOD on my machine. Could be a coincidence, but I have not seen a BSOD in a few years. :-)

[MahAppsCostura.zip](https://github.com/Fody/Costura/files/3273599/MahAppsCostura.zip)

**Comment by SimonCropp** [comment]
can you read the issue template https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by alekdavis** [comment]
I did read the template. What have I missed?

**Comment by SimonCropp** [comment]
* are you a patron? https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md
 * only msbuild 16 and above is supported, hence you need to be on VS2019
 * u need to supply a stand alone repro, not a "steps to reproduce" https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#minimal-repro
 * you are not using the latest version of fody
 * you are not using the latest version of costura
 * have you attempted to fix the bug?

**Comment by alekdavis** [comment]
Okay, sorry for wasting your time.

**Comment by SimonCropp** [comment]
is that "Okay, sorry for wasting your time. we should close the issue"?

**Comment by alekdavis** [comment]
I do not use Costura anymore, so it's no longer a problem for me. If you or anyone is curious to find out why Costura causes exceptions in WPF apps, I provided the sample project and instructions on how to duplicate it. If you do not think it is worth your time, feel free to "close" the issue.
