### ISSUE TITLE
Avoid copying the reference to dependent projects

### ISSUE THREAD

**Issue by Logerfo** [Fody/Costura#415]
My Solution structure looks like this:
```
ProjectA
|-> ProjectB
    |-> ProjectC
```
**ProjectB** is embedding **ProjectA** using Costura. This works fine and `ProjectA.dll` is not deployed.
**ProjectC** is referencing **ProjectA** _without_ embedding, which deploys `ProjectB.dll`.

The problem is: `ProjectA.dll` is being deployed with **ProjectC**, even with no direct reference to it.
I fixed the problem by adding the **ProjectA** reference to **ProjectC** and `ExcludeAssets='runtime'`.
The second problem is: I only run Costura in Release builds, not Debug. Because of this solution, my Debug builds stopped working, since there was not `DLL` file in the folder.
I tried using `Condition="'$(Configuration)' == 'Debug'"` and `Condition="'$(Configuration)' == 'Release'"`, but it does not seem to work (seems like the first one is always used, since it goes back to deploying the unwanted file even in Release builds again).

Is there a known way to fix this? Thanks.

**Comment by SimonCropp** [comment]
this project is being deprecated https://github.com/Fody/Costura/issues/442
