### ISSUE TITLE
The expression "[System.Version]::Parse('')" cannot be evaluated.

### ISSUE THREAD

**Issue by Maelou04** [Fody/Costura#417]
Hi,

I have an error when im trying to install costura.fody v4.0.0 (latest stable), i've try to change package version but i still have the same error how can i correct this ? 11 dll need to be merged in one executable two days on this error still no solution...

Full error string : The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.  C:\Users\Maël\Documents\Visual Studio 2015\Projects\software\packages\Fody.5.0.0\build\Fody.targets

Maël

**Comment by ltrzesniewski** [comment]
Hi,

Fody v5 requires VS2019. You may try v4.2.1 instead (and downgrade Costura to v3.3.3), but as you seem to be using VS2015 it's not guaranteed to work either. Consider updating your IDE.

**Comment by Maelou04** [comment]
Everything work great thank you so much !
