### ISSUE TITLE
Execute obfuscar before fody-costura merge files

### ISSUE THREAD

**Issue by juandrn** [Fody/Costura#418]
Hi all,

Good job for this project,

Could you guide me to solve this problem reported in stackoverflow please

https://stackoverflow.com/questions/56977866/execute-obfuscar-before-fody-costura-merge-files

Best regards
Thanks

**Comment by SimonCropp** [comment]
Can u read and follow the issue template https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by juandrn** [comment]
Sorry I don't understand, You suggest I should write I wrote in stackoverflow?

**Comment by SimonCropp** [comment]
* [you are not a patron](https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#you-should-already-be-a-patron)
 * [you have not shared a downloadable+runnable repro](https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#minimal-repro)
 * [you have not shown how you tried to fix the issue](https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#submit-a-pr-that-fixes-the-bug)
