### ISSUE TITLE
How to packing referenced dll referenced other dll

### ISSUE THREAD

**Issue by ColdCodeHah** [Fody/Costura#424]
My project,referenced a dll. But the dll referenced other dll more.The final generated exe does not seem to be packaged those "other dll".

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
