### ISSUE TITLE
Microsoft.Extensions libs are not embedded into .NET framework console app, meanwhile working fine on .NET core

### ISSUE THREAD

**Issue by Naxaliav** [Fody/Costura#433]
Hi, 
i'm using Microsoft.Extensions.Configuration and Microsoft.Extensions.json nuggets on my .NET framework console app. Using costura it doesnt embed both libs and their dependencies.
Can see in [output](http://prntscr.com/oyrj6n).
Meanwhile using .NET core it embeds them correctly.
Is that suppose to work like this? 
Regards,
Naxaliav

**Comment by SimonCropp** [comment]
can u re-read the issue template and ensure you have ticked off all the required steps https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
