### ISSUE TITLE
Net core 3.0. Wpf Net core

### ISSUE THREAD

**Issue by lobster2012-user** [Fody/Costura#453]
VS output
The target processsexited without raising coreclr started event
App closed immediatly.
0x8000808c

Costura 4.1.0
Fody 6.0.2

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by SimonCropp** [comment]
this project is being deprecated https://github.com/Fody/Costura/issues/442
