### ISSUE TITLE
not working with windows services

### ISSUE THREAD

**Issue by ispysoftware** [Fody/Costura#454]
Costura isn't creating executables that can be installed as a windows service and there are no instructions I can find to tell me how it's supposed to work - the service i've created installs fine pre-costura and fails post-costura with the error message:

**"Unable to get installer types"**

Does anyone have any links to more information or work-arounds?

@SimonCropp  if you can't be bothered to help people out at least leave bug reports open so other people can respond. Only offering help for people who have "donated" through patreon is pretty cheeky - lots of us work for free on open source projects - that's what the community is for. Anything you create these days is standing on the shoulders of thousands of hours of other people's work.

**Comment by SimonCropp** [comment]
https://github.com/Fody/Costura#costurautility

**Comment by SimonCropp** [comment]
either way this project is going to be deprecated. https://github.com/Fody/Costura/issues/442 so i suggest you dont use it

**Comment by ispysoftware** [comment]
i'm not using core 3 and i've seen that link and it doesn't help

**Comment by SimonCropp** [comment]
in that case. try ilmerge or ilrepack
