### ISSUE TITLE
Migrate to new project structure (similar to LoadAssembliesOnStartup)

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Costura#470]
Since I'll be maintaining Costura in the near future, I'll consolidate the project structure so it matches our other Fody weavers we are maintaining. This way we can easily patch different weavers at the same time.

**Comment by SimonCropp** [comment]
u still working on this? the appveyor build has been broken since https://github.com/Fody/Costura/commit/404a6fa70ae1a7890d1b51ee162449fd241aeee0 just wondering how a release would be done if we needed to

**Comment by GeertvanHorrik** [comment]
Yes, I am working on this (with a long pause in the middle ;-) ).

**Comment by GeertvanHorrik** [comment]
Done.
