### ISSUE TITLE
using costura to embed SevenZipSharp.dll 7z.dll(x86) 7z.dll(x64) find trouble

### ISSUE THREAD

**Issue by ice0030** [Fody/Costura#482]
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)

i really did want to buy the coffee,but i am chinese guy.....,very sorry,i did really want help
using costura to embed SevenZipSharp.dll 7z.dll(x86) 7z.dll(x64) find trouble

I use costura to embed sevenzipsharp find 2 problems
i use the following config

>  <Costura >
>     <Unmanaged32Assemblies>
>       7z
>       SQLite.Interop
>     </Unmanaged32Assemblies>
>     <Unmanaged64Assemblies>
>       7z
>       SQLite.Interop
>     </Unmanaged64Assemblies>
>   </Costura>

it did work ,
SevenZipSharp.dll  7z.dll(x86) 7z.dll(x64) did embeded in
but SevenZipSharp call interface need to set 7z dll path like
SevenZip.SevenZipExtractor.SetLibraryPath(@"./7z.dll");

problem1:SevenZipSharp.dll must physically exist in the same dir with exe,if not,exception like this:
:“SevenZip.SevenZipLibraryManager”的类型初始值设定项引发异常

problem2:even if SevenZipSharp.dll physically exist in the same dir with exe, exception like this:
Can not load 7-zip library or internal COM error! Message: can not change the library path because the file "./7z.dll" does not exist.(how do i write the path string)

although costura did embed in all the dll,but not work,why?

**Comment by ice0030** [comment]
**<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <Costura >
    <Unmanaged32Assemblies>
      7z
      SQLite.Interop
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      7z
      SQLite.Interop
    </Unmanaged64Assemblies>
  </Costura>
</Weavers>
**

**Comment by ice0030** [comment]
<Weavers>
  <Costura >
    <Unmanaged32Assemblies>
      7z
      SQLite.Interop
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      7z
      SQLite.Interop
    </Unmanaged64Assemblies>
  </Costura>
</Weavers>

**Comment by ice0030** [comment]
- <Weavers>
-   <Costura >
-     <Unmanaged32Assemblies>
-       7z
-       SQLite.Interop
-     </Unmanaged32Assemblies>
-     <Unmanaged64Assemblies>
-       7z
-       SQLite.Interop
-     </Unmanaged64Assemblies>
-   </Costura>
- </Weavers>

**Comment by GeertvanHorrik** [comment]
I have no idea why it doesn't work. As you mention, it's correctly embedded, and that's about where Costura stops and your own queste starts.

As explained by the issue templates, you either need to be a contributor to other OSS libs (but didn't see contribution activity in your GH profile) OR support the Fody open collective. I think both are not the case so I will close this ticket as explained by the template.

**Comment by ice0030** [comment]
i made a really simple project,just install fody.costura and sevenzipsharp,it did embeded in



but if sevenzipsharp not exist with exe,i would throw exception



please help me


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Geert van Horrik"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月8日(星期天) 晚上8:53
收件人:&nbsp;"Fody/Costura"<Costura@noreply.github.com&gt;;
抄送:&nbsp;"asura"<20089029@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Fody/Costura] using costura to embed SevenZipSharp.dll 7z.dll(x86) 7z.dll(x64) find trouble (#482)




Closed #482.
