### ISSUE TITLE
ReadFromEmbeddedResources and de4dot

### ISSUE THREAD

**Issue by 0x4000** [Fody/Costura#483]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Hi, I'm lately working a lot with obfuscation and deobfuscation / unpacking.
I found that if I use Costura in my Assembly, I'm able to dump all assemblies loaded by costura.
There is a small fix if you zero out the byte array after the assembly gets loaded, .Net generic Unpacker won't be able to extract any of the embedded files.

## API Changes
ReadFromEmbeddedResources zero out the byte array before return.
			var assembly = Assembly.Load(rawAssembly);
			for(var i = 0; i != rawAssembly.Length; i++)
				rawAssembly[i] = 0;
			return assembly;

## Intended Use Case
.Net Generic Unpacker won't be able to extract the embedded resources anymore. 
Right now I'm editing the method after release with ilspy, i rarely use github, pardon me if I can't create a pull request.

**Comment by SimonCropp** [comment]
there is no way to achieve this with costura. i suggest you use a different tool
