### ISSUE TITLE
include assembly from folder

### ISSUE THREAD

**Issue by ghost1372** [Fody/Costura#486]
Hi I have installed the Microsoft AppCenter [analytics and Crash report] packages after building the project, two folders will be created named x86 and x64, each with an assembly called e_sqlite3.dll

Costura Merged all assemblies into Exe but cannot merge these two folders. how can i merge this 2 folder?
also i have a folder called en that contain MyApp.resources.dll, this assembly also cant be merged in exe. can i merge this assembly too?

**Comment by GeertvanHorrik** [comment]
If this is a bug report => please create a repro and failing unit test

If this is a support request => please show that you are a patreon of Fody so we can provide the neccessary support

**Comment by ghost1372** [comment]
@GeertvanHorrik  i dont know that this is a bug or not
im not a patreon

**Comment by GeertvanHorrik** [comment]
About the x86 / x64, you will need to embed them as native assemblies as described here:
https://github.com/Fody/Costura#native-libraries-and-preloadorder

If I recall correctly, Costura automatically handles satellite assemblies for you:
https://github.com/Fody/Costura#ignoresatelliteassemblies

**Comment by ghost1372** [comment]
@GeertvanHorrik  tnx native assemblies worked fine but i cant add sattellite assemblies

**Comment by GeertvanHorrik** [comment]
Maybe there is a bug in https://github.com/Fody/Costura/blob/develop/src/Costura.Fody/ResourceEmbedder.cs#L29

**Comment by ghost1372** [comment]
@GeertvanHorrik Will it be fixed in future releases?

**Comment by GeertvanHorrik** [comment]
> @GeertvanHorrik Will it be fixed in future releases?

Potentially
