### ISSUE TITLE
Costura can fall into recursive resource loading in non-English environment

### ISSUE THREAD

**Issue by triumlabs** [Fody/Costura#495]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?

## Version of Library
3.3.3

## Version of OS(s) listed above with issue
Windows 10 Pro 1903

## Steps to Reproduce
1. Create a WPF application
2. Set Thread Culture to other than en-US
3. Use IsolatedStorageFile.OpenFile to open a file, and make it to throw an exception, e.g. use invalid character in filename
4. Run the application from command line (if running in VS, problem cannot be reproduced)

## Expected Behavior
Exception can be handled in a normal try/catch block

## Actual Behavior
Exception cannot be handled as another internal exception occurs: "mscorlib recursive resource lookup", which pops up an error dialog before you can catch the real exception.
This issue is the same as the one reported earlier, but got closed: https://github.com/Fody/Costura/issues/138

**Comment by SimonCropp** [comment]
* does the problem occur with the current version?
 * can you share a repro?
 * what steps have you taken to attempt to fix it yourself?

**Comment by molekm** [comment]
It is still a valid issue. Just add costura to non en-US (GB in this case) and it will fail to load mscorlib

Setting culture to en-US is for most apps a big blocker, so this is a critical bug.

**Comment by tom-englert** [comment]
See last comment of Simon above

**Comment by triumlabs** [comment]
See simple console program below to reproduce issue. It sets current thread's culture to anything else than en-US and than tries to create a file -with an invalid character in file name- in isolated storage (operation has to fail to reproduce the issue).
Costura version: 5.7.0
IDE: VS 2022 x64

using System;
using System.IO.IsolatedStorage;

namespace CosturaRecursiveResourceLoadingIssue
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var ciHu = System.Globalization.CultureInfo.GetCultureInfo("hu-HU");
            System.Threading.Thread.CurrentThread.CurrentCulture = ciHu;
            System.Threading.Thread.CurrentThread.CurrentUICulture = ciHu;

            try
            {
                var storage = IsolatedStorageFile.GetUserStoreForAssembly();
                using (var s = storage.CreateFile("tempfile*.txt"))
                {

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"ERROR: {ex}");
            }
        }
    }
}
