### ISSUE TITLE
directory.build.props conflicting by case

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Costura#496]
![image](https://user-images.githubusercontent.com/122666/72401791-37951180-37a1-11ea-8f5c-d816da8d41e2.png)
  
@GeertvanHorrik which one is correct?

**Comment by GeertvanHorrik** [comment]
Interesting. GHS is the latest, but I use the same thing everywhere. Will investigate what went wrong here, but it should be the lowercase one.

**Comment by ltrzesniewski** [comment]
It should be `Directory.Build.props` if you want it to work on Linux.

**Comment by GeertvanHorrik** [comment]
Aaargh, thanks for letting me know @ltrzesniewski . Will try to fix in the repository template...

**Comment by GeertvanHorrik** [comment]
Fixed in the repository template, thanks for the extra information!

**Comment by GeertvanHorrik** [comment]
Fixed the synchronizer so it supports `.deleteme` suffixes. Sync is now running, has to go through 120 repositories so can take a while...

**Comment by SimonCropp** [comment]
@GeertvanHorrik thanks :)
