### ISSUE TITLE
Missing a using directive or an assembly reference

### ISSUE THREAD

**Issue by armin-azar** [Fody/Costura#50]
There is a problem with using StimulSoft report assemblies in a windows project.
It's thrown an Unhandled Exception with following error:
"The type or namespace name 'Stimulsoft' could not be found (are you missing a using directive or an assembly reference?)"
All of required assemblies are attached and program work fine when they are located in executable directory.
Required Assemblies:
Stimulsoft.Base.dll
Stimulsoft.Controls.dll
Stimulsoft.Controls.Win.dll
Stimulsoft.Report.dll
Stimulsoft.Report.Win.dll
Stimulsoft.Report.Wpf.dll

**Comment by agunduz88** [comment]
I just stumbled into the same problem, I'm using winforms, where do I add 
<Weavers>
  <Costura CreateTemporaryAssemblies='true' />
</Weavers> this?

**Comment by SimonCropp** [comment]
@agunduz88 please raise a new issue and follow the issue template
