### ISSUE TITLE
Referencing a ResourceDictionary of a project ending in ".Resources" causes an exception

### ISSUE THREAD

**Issue by Ignas-Bradauskas** [Fody/Costura#519]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component
Costura

## Version of Library
4.1.0

## Version of OS(s) listed above with issue
Windows 10 10.0.17134 Build 17134

## Steps to Reproduce
1. Create a Wpf project.
2. Create a library project that has ".Resources" at the end of the name and reference it in the Wpf project.
3. Create a xaml ResourceDictionary in the library project.
4. Add the library project's ResourceDictionary to the Wpf project's MergedDictionaries collection, by referencing it by its uri.
5. Create the FodyWeavers.xml file, configure it to use Costura with the default settings.
6. Run the Wpf project.

## Expected Behavior
The project should run and the resulting exe should have the required dll weaved in.

## Actual Behavior
An error occurs.
![image](https://user-images.githubusercontent.com/55683104/75627372-321c4b00-5bd8-11ea-9d88-b1953d3a2375.png)

I've prepared a demo project: [https://github.com/Ignas-Bradauskas/CosturaBugDemo](https://github.com/Ignas-Bradauskas/CosturaBugDemo)

This happens because [ModuleWeaver.EmbedResources](https://github.com/Fody/Costura/blob/develop/src/Costura.Fody/ResourceEmbedder.cs) line 35 has a hard coded file name check. 
`if (dependency.EndsWith(".resources.dll", StringComparison.OrdinalIgnoreCase))`
The library project name containing ".Resources" at the end triggers a false positive.

Setting `<Costura IgnoreSatelliteAssemblies='true' />` fixes it, but it took some time to figure out the problem. This project name limitation should at least be more explicitly mentioned in the documentation, if not fixed.

**Comment by GeertvanHorrik** [comment]
The reason is indeed that satellite assemblies, generated by .net, are also named `*.resources.dll`.

I see 3 solutions in your power:

1. Rename your project assembly
2. Use the ignore satellite assemblies option (but can have side-effects)
3. Somehow create a PR that solves this in a non-breaking manner

**Comment by Ignas-Bradauskas** [comment]
We could add a warning of some sort to the readme. At least this would be documented. For example, in the "IgnoreSatelliteAssemblies" section. 

This way we would partly solve this in a non-breaking manner.

**Comment by GeertvanHorrik** [comment]
Great idea. Interested in doing a PR with these suggestions?

**Comment by Ignas-Bradauskas** [comment]
Yeah, why not. I'll do it later today then.
