### ISSUE TITLE
Load issue in Mono

### ISSUE THREAD

**Issue by distantcam** [Fody/Costura#57]
As reported by @phillip-haydon on Twitter.

Costura doesn't work with Sandra/Sandra.Snow on mono. CreateTemporaryAssemblies might be the culprit.

**Comment by ananthonline** [comment]
I'm looking at writing some bindings to native APIs and this would make it so incredible simple! I use Costura on Windows and it's perfect. Please reopen.

**Comment by SirusDoma** [comment]
Please reopen issue, I need embedding unmanaged assemblies under Mono in order to work across multiple platforms (e.g: Linux and OSX)

**Comment by icedream** [comment]
I'm still wanting this as well as I want to ship native libraries with my portable tool and I want to keep it all in one executable. Would be nice if this gets picked up again!

**Comment by distantcam** [comment]
I will happily accept a PR for this. But I am not a mono developer.
