### ISSUE TITLE
Issue with report viewer

### ISSUE THREAD

**Issue by helperman** [Fody/Costura#677]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component

Not sure

## Version of Library
4.1.0

## Version of OS(s) listed above with issue
Windows 8.1
dotnet --version: 5.0.102
Visual Studio 2019 v16.8.4

## Steps to Reproduce
1. install nuget package Microsoft.ReportingServices.ReportViewerControl.Winforms
2. install Costura Fody
3. add report-file: Add new item -> Report
3. add reportViewer control to a form
4. bind reportViewer with your report-file

## Expected Behavior
An error occured during local report processing. The definition of the report " is invalid. An unexpected error occured in Report Processing. The type initializer for "Microsoft.Reporting.Services.ReportIntermediateFormat.Persistence.IntermediateFormatVersion" threw an exception. The path is not a legal form.

## Actual Behavior
No errors expected

There is a post about the issue here:
https://stackoverflow.com/questions/57483850/error-when-embedding-report-viewer-dll-using-costura

**Comment by GeertvanHorrik** [comment]
1. Can you show that you are supporting Fody on Open Collective?
2. The solution in the SO post does not work for you?
3. Have you tried any other reporting lib (e.g. Stimulsoft, which we have great experiences with, even with embedding assemblies).

**Comment by helperman** [comment]
1. Probably not. I've used It once and I am not sure about using It in feature. 
2. It Works But it's not a solution since the asembly can't being injected into exe file
3. No. But Maybe I have to think about It.

**Comment by GeertvanHorrik** [comment]
Please try Costura 5.1.
