### ISSUE TITLE
The target process has exited, but no CoreCLR startup event has been raised. 

### ISSUE THREAD

**Issue by ljpass6754** [Fody/Costura#692]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
.NET5 WPF + Costura.Fody 5.1.0 + Fody 6.4.0

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. .NET5 WPF
2. Costura.Fody 5.1.0 with no reference dll；  OK；
![1](https://user-images.githubusercontent.com/16814432/114044537-e4cddb00-98b9-11eb-81bb-23573d59baf1.png)

3. Reference dlls with no Costura.Fody 5.1.0;   OK;
![2](https://user-images.githubusercontent.com/16814432/114044566-eb5c5280-98b9-11eb-9a4b-e7c77f874f05.png)

4. Costura.Fody 5.1.0 with reference dlls；  NG: The target process has exited, but no CoreCLR startup event has been raised. 
![3](https://user-images.githubusercontent.com/16814432/114044617-f616e780-98b9-11eb-9e14-452a019ef3b4.png)

**Comment by GeertvanHorrik** [comment]
We use Costura with WPF a lot, and that's working fine. Could you provide more info / a real repro?

**Comment by ljpass6754** [comment]
I updated the “Steps to Reproduce”， please have a try.

**Comment by GeertvanHorrik** [comment]
Please create a repro repository (open source) so we simply can clone. I am not getting paid for this support so want to make it as easy as possible for me.

**Comment by ljpass6754** [comment]
I created a repo "https://github.com/ljpass6754/CosturaDemo",  please clone it and have a try. Thanks.

**Comment by ljpass6754** [comment]
This issue is over.
