### ISSUE TITLE
Mono support?

### ISSUE THREAD

**Issue by cocowalla** [Fody/Costura#70]
I've just tried Costura on my project, and deployed it to a Linux box running Mono. When I run it I immediately get:

Missing method GetAppPath in assembly /home/user/product/test-x64/lib/Company.Product.exe, type 'Company.Product.Assembly.FileUtils

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Company.Product.Assembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3f14179a3bb5a6c6' or one of its dependencies.
File name: 'Company.Product.Assembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3f14179a3bb5a6c6'
```

Is the embedding method used by Costura just not compatible with the Mono runtime?

**Comment by optical** [comment]
For anyone who stumbles upon this in the future, I managed to workaround this issue on Mono 4.4.0 with my console application.

What I changed was to ensure the file that contained my entrypoint simply invoked a static method on a separate class in a separate file within the same assembly. I suspect this allows Costura to register the event handler prior to Mono attempting to load any further assemblies. Whenever I added a reference to a type not defined within my entrypoint assembly within the Main method, this would fail under Mono.

**Comment by nuclearpsyche** [comment]
I'm having the same problem with Mono and GtkSharp. One way to get around this is to add code at that start of your program: [https://blogs.msdn.microsoft.com/microsoft_press/2010/02/03/jeffrey-richter-excerpt-2-from-clr-via-c-third-edition](https://blogs.msdn.microsoft.com/microsoft_press/2010/02/03/jeffrey-richter-excerpt-2-from-clr-via-c-third-edition/)

**Comment by yurislav** [comment]
Alternatively, you can use [ILMerge.Fody](https://github.com/tom-englert/ILMerge.Fody) which merges multiple assemblies into single one (you can exclude external nuget dependencies and only merge your referenced projects with the main assembly). This approach works on mono.
