### ISSUE TITLE
Support for multi-targeted projects

### ISSUE THREAD

**Issue by lorinkundert** [Fody/Costura#710]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Is it possible for Costura to work on a target for net48 and ignore other compilation targets.

## API Changes
I dont think much of an API change would be needed, all that would be required is a way to differentiate the target platform, Net Framework and Netcore

## Intended Use Case
Often it is required to set multiple framework targets in a project, costura is great for net48 projects, but the problem comes when netcore is included as a target, I expect it could be as easy as a property in the project file or even in the FodyWeavers file.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
