### ISSUE TITLE
How to process manifest file in program

### ISSUE THREAD

**Issue by hxf3751** [Fody/Costura#720]
I want to merge my files in one single exe. file list is as below:
Form.exe (C# winform)
ness.dll (C++ ActiveX)
Form.exe.manifest (manifest file for Form.exe)
ness.sxs.manifest (manifest file for ness.dll)

The problem is how to process the two manifest files?  Should I add them to FodyWeavers.xml? or embed them in to Form.exe?

**Comment by GeertvanHorrik** [comment]
As far as I know, Costura does not embed manifests. Therefore you will need to embed them yourself as embedded resources and extract them to the temporary directory that Costura uses.

**Comment by hxf3751** [comment]
OK, Thank you!
