### ISSUE TITLE
Costura.Fody not working for my C# code

### ISSUE THREAD

**Issue by hunt8tw** [Fody/Costura#724]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [v ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [v ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?

## Version of Library
net5.0-windows

## Version of OS(s) listed above with issue
win 10

## Steps to Reproduce
1.
2.
3.

## Expected Behavior
I wish to get a runnable Exe after "build solution"

## Actual Behavior
I have read tutorial from google and watched tutorial from youtube for couple of days, but still can not make it work as expected.
[wpf01.zip](https://github.com/Fody/Costura/files/6810589/wpf01.zip)

**Comment by SimonCropp** [comment]
Can you confirm you are supporting Fody on open collective. https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md

**Comment by tom-englert** [comment]
Closed as stale
