### ISSUE TITLE
Debug: stepping through the imported Costura.Template code does not work

### ISSUE THREAD

**Issue by tom-englert** [Fody/Costura#738]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component

Costura

## Version of Library

https://github.com/Fody/Costura/commit/db4231289a9a84e091e5c81409ea3ff39698b8bc

## Steps to Reproduce

- Use `CosturaUtility.Initialize();` in your weaved application
- Put a breakpoint there
- Try to step inside code

## Expected Behavior

It's possible to debug-step through all the ILTemplate code

## Actual Behavior

You can step only to the beginning of the methods, next step will just leave the method.

**Comment by GeertvanHorrik** [comment]
Have published a new alpha that contains the fix: https://www.nuget.org/packages/Costura.Fody/5.5.0-alpha0074
