### ISSUE TITLE
Support for LoadLibrary calls?

### ISSUE THREAD

**Issue by gharpur** [Fody/Costura#75]
Costura is working well for me (thanks!), but I call a 3rd party .NET (mixed mode) DLL, which in turn uses LoadLibrary (I assume) to load a native DLL. That call is not finding the native DLL in the temp folder because it's not on the path.  I thought of adding a call to  SetDllDirectory in my own code, but I don't have access to the hashed directory name.

Would it be feasible to add a call to SetDllDirectory into Costura at the point the native DLLs are extracted to handle this type of situation?

**Comment by Darkvater** [comment]
I've experienced the same. The path that is added is not the \32, \64 subpath, but the root, as thus I am unable to load the 64-bit DLL into my assembly.

**Comment by SimonCropp** [comment]
if this issue still occurs in v2 please upload a small solution that reproduces the problem

**Comment by froque** [comment]
[Costura75.zip](https://github.com/Fody/Costura/files/1915040/Costura75.zip)

I had this issue when trying to use SevenZipSharp. I work around this with: 
```
var name = typeof(SevenZip.ArchiveFileInfo).Assembly.GetFile("sevenzipsharp.dll").Name;
SevenZip.SevenZipBase.SetLibraryPath(Path.Combine(Path.GetDirectoryName(name), @"32\7z.dll"));
```

It would be nice for Costura to support this without any workaround. This still occurs in v2 @SimonCropp. I have uploaded a small project.

**Comment by Monns** [comment]
> [Costura75.zip](https://github.com/Fody/Costura/files/1915040/Costura75.zip)
> 
> I had this issue when trying to use SevenZipSharp. I work around this with:
> 
> ```
> var name = typeof(SevenZip.ArchiveFileInfo).Assembly.GetFile("sevenzipsharp.dll").Name;
> SevenZip.SevenZipBase.SetLibraryPath(Path.Combine(Path.GetDirectoryName(name), @"32\7z.dll"));
> ```
> 
> It would be nice for Costura to support this without any workaround. This still occurs in v2 @SimonCropp. I have uploaded a small project.

thanks
