### ISSUE TITLE
Thanks and Inquiries

### ISSUE THREAD

**Issue by YJ15** [Fody/Costura#752]
Leave Your Message Below (don't delete this line though)

Thanks to Costura, I was able to keep my project's dll files neatly organized. Thank you.
When the exe file contains dlls, the size of the exe file grows naturally. Maybe it also increases the process memory of the exe file?

**Comment by GeertvanHorrik** [comment]
I am 99% sure that the assemblies will be extracted at startup (but streams are being disposed). Then assemblies are only loaded when required by .NET, so it should not affect the process memory (only execution size because files are being embedded).
