### ISSUE TITLE
Can you guide me how to use Crypto Obfuscator For .Net for obfuscated encryption? Before Costura.Fody works ?

### ISSUE THREAD

**Issue by AtlantisDe** [Fody/Costura#755]
# How to perform obfuscation before packaging

## Crypto Obfuscator For .Net
- [I use this software for obfuscation and encryption](http://www.ssware.com/cryptoobfuscator/download.htm)
 
## I have searched a lot of information and it seems that I have not found a suitable solution

- [Skipping target "FodyTarget" because all output files are up-to-date with respect to the input files.](https://github.com/Fody/Fody/issues/351)
- [Execute Obfuscar Before Fody.Costura Merge Files](https://stackoverflow.com/questions/56977866/execute-obfuscar-before-fody-costura-merge-files)

## Can you guide me how to use Crypto Obfuscator For .Net for obfuscated encryption? Before Costura.Fody works
- ths very much....

**Comment by SimonCropp** [comment]
Cecil, and hence fody, does not support obfuscated assemblies
