### ISSUE TITLE
Investigate how to support different target frameworks (e.g. .NET 4.x vs .NET 5 / 6)

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Costura#764]
Copied from initial discussion here: https://github.com/Fody/Costura/pull/763

By @0xced

The `NetStandardAssemblyResolver` was introduced in #701 in order to fix #697 (`System.ArgumentNullException` deep inside Cecil) and as a bonus adds support for .NET Framework 4.7 and lower.

Do we really want to revert both #696 (Use the assembly resolver from the module definition) and #701? This will drop .NET Framework 4.7 and lower and we are back at the undecipherable `System.ArgumentNullException`. 🙁
```
   at Mono.Cecil.Mixin.CheckType(Object type) in D:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 1258
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context) in D:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 859
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type) in D:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 854
   at ModuleWeaver.Resolve(TypeReference baseType)
   at ModuleWeaver.ImportAssemblyLoader(Boolean createTemporaryAssemblies)
   at ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 185
```

=====================================

By @SimonCropp 

embedding and loading the net48 version of netstandard is strange. the problem is cause since Costura.Template targets netstandard2 but costura support frameworks that do no support netstandard. ie version 471 and lower of .net has known incompatibilism with netstandard2.0 that MS has no intention of fixing 

> ✔️ CONSIDER adding a target for net461 when you're offering a netstandard2.0 target.
>Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. You can improve the experience for developers that are still on .NET Framework 4.6.1 - 4.7.1 by offering them a binary that is built for .NET Framework 4.6.1.

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

IMO the correct implementation would be to have multiple targets for Costura.Template, ie one that also targets the lowest version that costura supports

So the options here are

 * drop support for frameworks that MS has stopped supporting. (yes i know MS is still officially supporting back to 4.5.2, but the number of workarounds required to make it work is IMO untenable for non paid projects)
 * roll this back
 * experiment multiple targets for Costura.Template

thoughts?

**Comment by 0xced** [comment]
I assume [Costura 5.8.0-alpha0094](https://www.nuget.org/packages/Costura.Fody/5.8.0-alpha0094) includes the changes introduced in #763. Am I correct? Should we revert #763 to avoid the regressions I described above before releasing a new stable version?

**Comment by GeertvanHorrik** [comment]
I think you are correct. I'll try to put it on my list for this week to look at.

**Comment by GeertvanHorrik** [comment]
Added back the net standard resolver. Releasing new version now.

@0xced / @tom-englert , please keep this ticket updated for the new release, then we have all information in 1 place.

**Comment by tom-englert** [comment]
@GeertvanHorrik 5.8.0-alpha0098 works

**Comment by GeertvanHorrik** [comment]
@0xced , can you verify it's working for you as well?

**Comment by 0xced** [comment]
Sorry, I'm away from computer this week, so I won't be able to check before next Monday.

**Comment by GeertvanHorrik** [comment]
No problem, we will wait, we want to make sure it all keeps working.

**Comment by GeertvanHorrik** [comment]
@0xced I don't want to put any pressure on you, but do you have an ETA when you can test this behavior?

**Comment by tom-englert** [comment]
About the original issue: one option could be to inject the code as source via code generator instead off merging the IL. This way references would always be correct.

**Comment by SimonCropp** [comment]
side note. i helped build this as an alternative to Costura https://blog.sentry.io/2022/02/24/alias-an-approach-to-net-assembly-conflict-resolution/

**Comment by GeertvanHorrik** [comment]
Closing this ticket. We added #990 , #989 and #992
