### ISSUE TITLE
Autodesk Revit Plugin project don't load commands by AddinManager

### ISSUE THREAD

**Issue by kelicto** [Fody/Costura#780]
-  [x] .NET Framework
 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
Don't load any command
![image](https://user-images.githubusercontent.com/23723575/143676238-b56e4a92-b266-4cc2-8d7a-ec1e6aa36a20.png)

## Version of Library
5.7

## Version of OS(s) listed above with issue
Windows 11

## Steps to Reproduce
1. using the package.
2. to build the project.
3. open Autodesk Revit(BIM Software) to test target commands.

## Expected Behavior
Can load some commands.

## Actual Behavior
Cannot load any command.

**Comment by kelicto** [comment]
If you don't know how to build the demo, please tell me. I will send the demo.zip.

**Comment by tom-englert** [comment]
What makes you think this is an issue with Costura and not Autodesk?

**Comment by kelicto** [comment]
Sorry. I will also submit Autodesk Revit Forum. When merged dll, The `AddinManager` don't find them by target folder. If Autodesk tell me any message, I will update here. 

Year. I think plugin project should not use it.

**Comment by kelicto** [comment]
I think this is a interesting question. So, I want to update here. I need to do more test and thinking.

**Comment by tom-englert** [comment]
It sound like complaining about "if I hide my assemblies, no one can see them"

**Comment by kelicto** [comment]
But that test project does not need to have some necessary dlls. I will test it today. I forgot something yesterday.

**Comment by GeertvanHorrik** [comment]
Are you sure the app domain has a reason to load the embedded assemblies? Check if they are being loaded into your appdomain. If not, consider using [Fody.LoadAssembliesOnStartup](https://github.com/Fody/LoadAssembliesOnStartup).

**Comment by kelicto** [comment]
Thank you! I will test it.

**Comment by kelicto** [comment]
> Are you sure the app domain has a reason to load the embedded assemblies? Check if they are being loaded into your appdomain. If not, consider using [Fody.LoadAssembliesOnStartup](https://github.com/Fody/LoadAssembliesOnStartup).

I don’t know the operating mechanism of this plugin manager to load plugins. For safety, don’t merge dlls in projects involving plugins. Because the manager may not give me any information prompts, so I don't know how to deal with it.

I think this is a RevitAPI problem, I will feedback the bug to Autodesk forum.

**Comment by kelicto** [comment]
![Uploading image.png…]()
