### ISSUE TITLE
Costura doesn't handle non-english resource loading

### ISSUE THREAD

**Issue by molekm** [Fody/Costura#782]
This is another re-open of a bug that was never fixed.

Steps.

Create a new project in non en-US region, add costura, and anything using mscorlib and Costura will fail to pack it properly.

Setting a culture to en-US is a blocker to probably most of apps as there is a reason why that exists, so it is not a valid hack.

Would be nice to see a fix for that as I can see that this bug was never solved for number of years and someone keeps closing the ticket without a fix or even a commit proving a fix.

**Comment by tom-englert** [comment]
How do you "Create a new project in non en-US region"

**Comment by molekm** [comment]
> How do you "Create a new project in non en-US region"

When app culture is not en-US => when is automatically set to other region. 

Here is a talk but it was closed without a fix. Bug still exists in newest version
https://github.com/Fody/Costura/issues/138

**Comment by tom-englert** [comment]
Always the same: no one follows the issue template, no one shares a repo.

Are you patron?

**Comment by molekm** [comment]
> Always the same: no one follows the issue template, no one shares a repo.
> 
> Are you patron?

1. Create unit tests
2. Set culture to anything else than en-US and include dependences as for examples from #138.

I assume you are using unit tests and this case shouldn't be even a 2 minutes work to add additional test to see what is happening.

So as soon you start using unit tests, you will suddenly see why you do not need example codes to see the edge-case (in this case it is not an edge case).

**Comment by tom-englert** [comment]
OK, if it's only two minutes just submit a PR with the tests

**Comment by tom-englert** [comment]
BTW are you patron?

**Comment by molekm** [comment]
> OK, if it's only two minutes just submit a PR with the tests

No, it is 2 minutes as long you have done those tests in a first place.

If you dev without unit tests then well....  Perhaps you should read why it is crucial to use them... I cannot imagine writing anything of quality without automated tests... It is simply not possible, as if you do not have 100% coverage of a code, you will never know about most of edge cases (or even just simple stuff).

Writing tests for a project that was written without those will take some good amount of time. 

Aren't you using unit/integration tests at work ?
