### ISSUE TITLE
win32 dll  [DllImport("helloword.dll")] OR [DllImport("helloword.so")] 

### ISSUE THREAD

**Issue by EnhWeb** [Fody/Costura#801]
win32 dll  [DllImport("helloword.dll")] OR [DllImport("helloword.so")]
helloword.dll OR helloword.so 能否也一起打包进单文件中？
helloword.dll OR helloword.so  Can they also be packaged into a single file?

**Comment by GeertvanHorrik** [comment]
A few questions upfront (since everyone's time is very valuable):

1. What did you try yourself, is there a repo?
2. Did you look at the unit tests (that should contain unmanaged libraries)?

**Comment by GeertvanHorrik** [comment]
Closing due to age of ticket.
