### ISSUE TITLE
Files not merging - "Package reference missing 'compile' part in IncludeAssets"

### ISSUE THREAD

**Issue by 64ZooLane** [Fody/Costura#820]
## Files not merging when building.
* Output Window Messages
MSBUILD : warning FodyPackageReference: Fody: The package reference for Costura.Fody is missing the 'compile' part in the IncludeAssets setting; it's recommended to completely remove IncludeAssets
* Your Code (small reproducible sample)
I haven't added anything to the code
* If there is an exception/crash - provide the full stack trace
Doesn't crash.

### Steps to reproduce

1. Build

Platform: Windows 10
.NET version: 3.1

### Expected behaviour

Tell us what should happen:
Build with all files combined into 1

### Actual behaviour

Tell us what happens instead:
Shows that message in the build output and all the files are still scattered.
![image](https://user-images.githubusercontent.com/64433470/174264248-5858550a-6e8a-421c-b1b8-e3e0e3d3fcdd.png)
![image](https://user-images.githubusercontent.com/64433470/174264363-1d0e8788-181d-4449-bd5c-019fbf9131f2.png)

**Comment by GeertvanHorrik** [comment]
I think it should work with this:

```
<PackageReference Include="Costura.Fody" Version="5.7.0" PrivateAssets="all" />
```

**Comment by alpha-xdream** [comment]
![image](https://github.com/user-attachments/assets/102721f5-3618-477b-8376-f7487b9b632c)
This is because you created a console application instead of a .net framework application.

**Comment by GeertvanHorrik** [comment]
Closing because of age.
