### ISSUE TITLE
Once i install Costura.Fody to my project and then build.. windows defender catches my app.exe as a Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by BluntlySurreal** [Fody/Costura#822]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please provide as much detail as possible
* Output Window Messages
* Your Code (small reproducible sample)
* If there is an exception/crash - provide the full stack trace

*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1.
2.
3.

Platform:
.NET version:

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by tom-englert** [comment]
There's nothing Fody can do about this.
Please report false positives to the Defender team.
