### ISSUE TITLE
Unable to switch languages according to regional settings

### ISSUE THREAD

**Issue by ghost** [Fody/Costura#853]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WinForm
 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
Don't know.

## Version of Library
v5.7

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. Run a program with using fody.
2. UI display cannot be changed according to settings.

## Expected Behavior
Can do this.

## Actual Behavior
Cannot do this.

Does it support Resx multilingual system? Because, I find that supported list does not contain this.

**Comment by GeertvanHorrik** [comment]
Yes, Costura does embed language resources. But there is not enough information (as in: please provide a repro) to even look into this.

**Comment by kelilife** [comment]
I found that after our users packaged with it, there was an unbootable situation and the error message was related to KernelBase.dll and the operating system was Windows 7.

I wonder if it has something to do with its level of support, and whether to consider enhancing this aspect.

**Comment by kelilife** [comment]
[FodyDemo.zip](https://github.com/Fody/Costura/files/10040399/FodyDemo.zip)

**Comment by GeertvanHorrik** [comment]
Closing because of age.
