### ISSUE TITLE
Creating instance via Assembly.CreateInstance

### ISSUE THREAD

**Issue by drd00m** [Fody/Costura#86]
Hi there!
First of all let me say that I am quite impressed about Costura at all. Thanks a lot for your work.

Nevertheless I got a problem which I could not solve yet.
I am loading my assembly with merged assemblies by using reflection. Now I want to load my main class in this DLL by using "Assembly.CreateInstance".
That is where my problem starts. I am just getting "null" when I use the combined Costura DLL. Putting all assmblies in that directory everything works just fine.

Do you know any fix for that issue?

Thanks in advance and best regards.

drd00m

**Comment by qmfrederik** [comment]
Hi, 

I hit this issue and found bits of clues in the issues section but no straightforward code sample I could copy paste.

So to help the next person who's hitting this:

#### Summary
You can use Costura.Fody to inject the dependencies of your class libraries in the assembly itself. However, if you load the assembly using reflection yourself (e.g. using `Assembly.Load` or using any dependency injection framework), the Costura AssemblyLoader is not initialized and the dependencies of your class library fail to load.

#### Workaround
Load the class library yourself, and invoke the `Costura.AssemblyLoader.Attach()` method manually. Here's how you would go about and do that:

```
var assembly = Assembly.LoadFile(@"<path to your dll>");
var assemblyLoaderType = assembly.GetType("Costura.AssemblyLoader", false);
var attachMethod = assemblyLoaderType.GetMethod("Attach", BindingFlags.Static | BindingFlags.Public);
attach.Invoke(null, new object[] { });
```

**Comment by Nelladel** [comment]
Hi, 

I was having the same problem when loading through `Reflection` a bundled Costura assembly containing [FluentValidation](https://github.com/FluentValidation/FluentValidation). The code above worked, but unfortunately, I am not allowed to modify the `Reflection` bit on the loading application. Is there a way to embed this behaviour in my bundled DLL so the calling application needs not be modified? 

`Calling Application snippet`: 
```csharp
Assembly assembly = Assembly.LoadFile(item);
var types = assembly.GetTypes() // <-- Exception thrown here 
```
ideally would change to: 
```csharp
Assembly assembly = Assembly.LoadFile(item);

var assemblyLoaderType = assembly.GetType("Costura.AssemblyLoader", false);
var attachMethod = assemblyLoaderType?.GetMethod("Attach", BindingFlags.Static | BindingFlags.Public);
attachMethod?.Invoke(null, new object[] { });

var types = assembly.GetTypes() // <-- No exception thrown
```

But since it's impossible, is there a way to include those 3 magical lines in my `dll`, and leave the loading code as in the first snippet?

**Comment by GeertvanHorrik** [comment]
Costura works at the same level as ModuleInit. Howevever... I am not entirely sure whether the assembly will be loaded into the app domain for reflection (I think not). So in that case, LoadAssembliesOnStartup (in the actual app!) should work.

**Comment by Nelladel** [comment]
Hi @GeertvanHorrik : 

Thanks for the reply! However, I can't add/modify a single line of code in the calling app, so no chance of adding a weaver there :(

**Comment by GeertvanHorrik** [comment]
Unfortunately it's impossible to execute code before your assembly is being loaded (at least I am not aware of such possibilities).
