### ISSUE TITLE
AutoCAD plug-in packaging is not supported

### ISSUE THREAD

**Issue by ghost** [Fody/Costura#872]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

-  [x] Class Library(.NET Framework)
 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
Testing found that the AutoCAD plug-in is not recognized by the command after it is packaged with the dependency library.

## Version of Library
v5.7

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. Create a class library on .NET Framework for AutoCAD plugin
2. Reference to some dependent libraries
3. After loading the netload command in autocad

## Expected Behavior
The command should be recognized properly

## Actual Behavior
 we found that the command we defined (CommandMethod) was not recognized

## NOTE
If you are not familiar with AutoCAD plug-in development and operation methods, you can check from the Internet. I believe that as long as you can write Helloworld programs, you will easily be able to find out this problem.

**Comment by igorpooh1978** [comment]
try to use
```
 CreateTemporaryAssemblies='true'
```

**Comment by kelilife** [comment]
Is it equivalent to disabling Fody?

**Comment by GeertvanHorrik** [comment]
Closing because of age.
