### ISSUE TITLE
Language Resources Not Being Included

### ISSUE THREAD

**Issue by foohyfooh** [Fody/Costura#876]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x] .NET Core

## Component

What component is this issue occurring in?

## Version of Library
- net7.0-windows
- Fody 6.6.4
- Costura.Fody 5.7.0

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
01. Clone https://github.com/foohyfooh/PKHeXPluginPile
02. Open in Visual Studio
03. Open InsertionPlugin>PositionForm in the form designer
04. On the Form object, Change Design>Language from (Default) to Spanish
05. Change any of the labels text and save it
06. Build the solution
07. Download and extract [PKHeX (23.02.27)a-es.zip](https://github.com/Fody/Costura/files/11069630/PKHeX.23.02.27.a-es.zip)
08. Copy the bin\Release\net7.0-windows\InsertionPlugin.dll to the plugins folder where you extracted PKHeX
09. Run PKHeX and click on Herramientas>Insertion Plugin and you will notice the text hasn't changed
10. Close PKHeX
11. Copy bin\Release\net7.0-windows\es\InsertionPlugin.resources.dll to the plugins folder
12. Run PKHeX and click Herramientas>Insertion Plugin and you will notice that the text has changed

## Expected Behavior
The resources dll shouldn't need to be copied and all the language files would be bundled in the InsertionPlugin.dll like what is done with the PackageReferences which will allows switching of languages with one dll.

## Actual Behavior
The resources dll needs to be copied for the language to change.

**Comment by tom-englert** [comment]
Did you check if the resources are properly embedded, e.g. with ilspy?

**Comment by foohyfooh** [comment]
This is what is iLSpy is showing me as the resources
![iLSpy Resources](https://user-images.githubusercontent.com/3344332/227742037-6083172b-15f7-40d9-868b-3377534a96bb.png)

And with `CosturaUtility.Initialize()`  I still get the same issue.

**Comment by JiuLing-zhang** [comment]
Any updates?

**Comment by GeertvanHorrik** [comment]
It's on our to-do list, but probably similar as you, we have other responsibilities (and families and hobbies). There are several ways to speed things up:

1. Investigate and provide a fix yourself
2. Pay for support (because every hour we put into this is not billable to the people putting in the work (for free, for you))

If none of these are valid options, then you'll have to wait in line until we find time and energy to fix this.

**Comment by GeertvanHorrik** [comment]
We made some improvements to loading resource assemblies. Assuming this is fixed (in v6), otherwise please re-open.
