### ISSUE TITLE
The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception

### ISSUE THREAD

**Issue by ZedZipDev** [Fody/Costura#901]
NET Framework 4.8
Costura.Fody 5.7.0
Windows 10

My application starts and connects to SQL Server, then open a Forms etc
It worked fine.
I have replaced System.Data.SqlClient with recommended Microsoft.Data.SqlClient.
I have built the app with Costura.Fody and run it.
During the SqlCnnection.Open(str)
The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception

How to fix it?
What should I include to Costura files?

**Comment by GeertvanHorrik** [comment]
We have no fodyweavers.xml contents, so we can only guess. But I think you should include Microsoft.Data.Sql* in your fodyweavers and all should work.

**Comment by ZedZipDev** [comment]
My fodyweavers.xml
```
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura>
  </Costura>
</Weavers>

```

**Comment by ZedZipDev** [comment]
I have made 
```
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura>
       <IncludeAssemblies>
		  Microsoft.Data.SqlClient
	</IncludeAssemblies>
  </Costura>
</Weavers>

```

and rebuilt the app (Release). The bin\Release\net48 contains large set of assemblies. it seems not packed by costura

**Comment by GeertvanHorrik** [comment]
You need more than "just" Microsoft.Data.SqlClient. You can use wildcards.

**Comment by ZedZipDev** [comment]
Thank you, but little bit more details
If I use default file
```
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura>
  </Costura>
</Weavers>
```

after VS2022 build I have a 15MB exe..
But when I use 
```
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura>
       <IncludeAssemblies>
		  Microsoft.Data.SqlClient
	</IncludeAssemblies>
  </Costura>
</Weavers>

```

then i have a large file set .
Could you please write me: what is incorrect?

**Comment by GeertvanHorrik** [comment]
If you use the 2nd one: only Microsoft.Data.SqlClient will be embedded, the rest will not be embedded. I think you also need to embeded the native runtime assemblies. Please check the example apps on how to do this, because officially there is no support for Costura anymore.

**Comment by 0xced** [comment]
I wrote [How to package a single-file executable using the SQLite EF Core Database Provider on .NET Framework?](https://stackoverflow.com/questions/63887709/how-to-package-a-single-file-executable-using-the-sqlite-ef-core-database-provid/63887710#63887710) for SQLite but you can probably adapt it for `Microsoft.Data.SqlClient`. Sorry I can't help more from my phone.

**Comment by ZedZipDev** [comment]
> If you use the 2nd one: only Microsoft.Data.SqlClient will be embedded, the rest will not be embedded. I think you also need to embeded the native runtime assemblies. Please check the example apps on how to do this, because officially there is no support for Costura anymore.

"no support for Costura anymore" - why?
Where can I find examples?

**Comment by ZedZipDev** [comment]
> I wrote [How to package a single-file executable using the SQLite EF Core Database Provider on .NET Framework?](https://stackoverflow.com/questions/63887709/how-to-package-a-single-file-executable-using-the-sqlite-ef-core-database-provid/63887710#63887710) for SQLite but you can probably adapt it for `Microsoft.Data.SqlClient`. Sorry I can't help more from my phone.

Microsoft.Data.SqlClient is NuGet package. How to include NuGet dlls + all referenced dlls to fodyweavers.xml?

**Comment by ZedZipDev** [comment]
> If you use the 2nd one: only Microsoft.Data.SqlClient will be embedded, the rest will not be embedded. I think you also need to embeded the native runtime assemblies. Please check the example apps on how to do this, because officially there is no support for Costura anymore.

I have checked the exe:  it contains microsoft.data.sqlclient.dll in Resources
// 0x001F42AA: costura.microsoft.data.sqlclient.dll.compressed‎ (628010 bytes, Embedded, Private)

What can I do else?

**Comment by GeertvanHorrik** [comment]
As stated in the readme, Costura is no longer actively supported, closing this issue. 

Please look for another solution to create single file executables.
