### ISSUE TITLE
NET Framework 4.8 project: the bin\Release contains37 files.

### ISSUE THREAD

**Issue by ZedZipDev** [Fody/Costura#902]
Here is my small NET 4.8 project. I build Release and see 37 files in the Bin\Release.
Is it ok? Or there should be 1 single exe?
[WFormsCostura.zip](https://github.com/Fody/Costura/files/12122793/WFormsCostura.zip)

**Comment by GeertvanHorrik** [comment]
As stated in the readme, Costura is no longer actively supported, closing this issue.
