### ISSUE TITLE
i think    <Costura IncludeDebugSymbols='false' /> disables the disable cleanup

### ISSUE THREAD

**Issue by Mrgaton** [Fody/Costura#903]
when i tried disabling IncludeDebugSymbols then i got no final output of my NuGet packages dlls on my bin path

**Comment by Mrgaton** [comment]
Im using net framework 4.8 with windows forms

**Comment by GeertvanHorrik** [comment]
Can you prepare a unit test so we know what to fix?

**Comment by Mrgaton** [comment]
oh the problem is that I was defining the costura multiple times  with different options

instead of doing this
`<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura DisableCleanup='true' IncludeRuntimeReferences='false' IncludeDebugSymbols='false' CreateTemporaryAssemblies='false' IgnoreSatelliteAssemblies='true'/>
</Weavers>`

I was doing this 

`<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura DisableCleanup='true'/>
  <Costura IncludeDebugSymbols='false' />
  <Costura IncludeRuntimeReferences='false' />
</Weavers>`

my bad I've never used XLM before
