### ISSUE TITLE
Multiple versions of the same assembly does not function correctly because AssemblyVersion is not included in the resource name

### ISSUE THREAD

**Issue by jonreis** [Fody/Costura#91]
Here is the scenario I came across

Library 1 - 3rd Party library out of our control - Has a dependency on Ionic.Zip.dll v1.9.1.8 (This version is signed)
Library 2 - Has dependency on Ionic.Zip.dll v1.9.3.0 (This version is not signed. It is the latest one on nuget.)

The issue is that since the ILTemplate.cs does not take version into account, whenever Library 1 requests Ionic.Zip.dll v1.9.1.8, it gets v1.9.3.0. The exception thrown is that the required assembly needs to be signed (so Constura is pulling the wrong version). In this case, since the required version is not embedded, Cunstura should return null from it's AssemblyResolve event handler.

To fix this scenario Costura should do the following (this is similar to what the GAC does for resolving assemblies).

1) Store the resource stream with a name that contains the version of the assembly. For example, instead of costura.ionic.zip.dll.zip, the name should be something like: costura.ionic.zip.1.9.1.8.dll.zip
2) When resolving the name, the assembly version should be included in the name. For example, instead of:

 var name = requestedAssemblyName.Name.ToLowerInvariant(); 

include the version in the name of the resource being resolved.

 var name = string.Format("{0}.{1}.dll", assemblyName.Name, assemblyName.Version);

On a separate, or possibly related request, would be to allow the developer to override the behavior of the ILTemplate.cs. Perhaps a OnResolvingAssembly event that has a bool Handled, that tells the framework that the user has overridden the default behavior.

**Comment by eugeneflim** [comment]
Any progress here please? I have that exact same issue, and stuck now - two versions of the same dll have to be loaded, but only the 1st one is. Thanks!

**Comment by DBlackburn** [comment]
You can add another to the list of users needing a similar solution. We would like it if Costura could support the Specific Version property of the references. When this property is True and in the event that the assembly load didn't fail, it should verify that it is the correct version of the assembly. If it is not, then Costura would load the correct version of the assembly from the embedded resources instead.

**Comment by jokyjoey** [comment]
Any news regarding this topic? I'm having the same problem at the moment. I like the ease of using costura and hope you guys find a solution for this "limitation". Thanks in advance!

**Comment by robertmuehsig** [comment]
I discovered Fody Costura a few days ago and the usage is pretty simple and seems to be doing fine with WPF apps, but with this issue in place the posibilties are limited. 
Is there a hope to resolve this issue - I saw your ( @distantcam ) comment here https://github.com/aspnet/dnx/issues/819#issuecomment-61914231 and would love to hear if there might be a solution incomming.

And of course: I would love to help (as far as I can of course ;))

**Comment by HaGGi13** [comment]
@jonreis as far as I can see, there is nothing that would bind a specific version of an assembly.
We need this feature too. :/

1. [call to resolve an assembly](https://github.com/Fody/Costura/blob/d910b4f38bd54b243941b7008dc57bb896a66908/Costura.Template/ILTemplate.cs#L39)
2. [where it will be resolved if it was already loaded](https://github.com/Fody/Costura/blob/832da628d6c7ef1899a241122dd4bd7ddf868545/Costura.Template/Common.cs#L71)
3. [otherwise it will be loaded from embedded resources](https://github.com/Fody/Costura/blob/832da628d6c7ef1899a241122dd4bd7ddf868545/Costura.Template/Common.cs#L132)

**Comment by SimonCropp** [comment]
@HaGGi13 raise a new issue to spec out how u think it should work. And please don’t ignore the issue template
