### ISSUE TITLE
Migrate to netStandart

### ISSUE THREAD

**Issue by Mrgaton** [Fody/Costura#935]
When using costura fody it downloads a bunch of dependencies 

![image](https://github.com/Fody/Costura/assets/68958481/5b63cc2b-ff9c-4705-bb4d-92e07205ac59)

and increase a lot the exe final size, why cant not just use the current framework built in libraries

**Comment by Mrgaton** [comment]
the more I research the more im realizing that this issue doesnt make sense

**Comment by GeertvanHorrik** [comment]
Did you set PrivateAssets? Then it should not have any dependencies. These are only required during the **build**, not during **runtime.**
