### ISSUE TITLE
I used Costura.Fody in my project to package it as a class library for others to call

### ISSUE THREAD

**Issue by Zhx-Chenailuoding** [Fody/Costura#946]
I used Costura.Fody in my project to package it as a class library for others to call. In the FodyWeavers.xml file, I used:
`<Costura>
    <Unmanaged64Assemblies>
        libiomp5md
    </Unmanaged64Assemblies>
</Costura>`

    
Then, when referencing the DLL I packaged in another project, an error occurred stating that the file could not be found: System.DllNotFoundException: Unable to load DLL 'dll\x64\libiomp5md.dll': The specified module could not be found.

**Comment by tom-englert** [comment]
Hard to say without seeing any context. However costura is in maintenance mode and no longer actively developed, so don't expect too much here.

To pack and load unmanaged assemblies, it's sometimes easier to do it by your own rather than using costura, so you have full control.

**Comment by Zhx-Chenailuoding** [comment]
So, I can only manually package the dll using Visual Studio?

**Comment by GeertvanHorrik** [comment]
Closing because of age.
