### ISSUE TITLE
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Project.exe

### ISSUE THREAD

**Issue by telemat** [Fody/Costura#95]
Costura does not seem to handle loading a DLL like a plugin. Or maybe I just got it wrong.

```
var domain = AppDomain.CreateDomain("Aloha");
var pathToDll = @"C:\TestApp1.dll";
var instance = domain.CreateInstanceFromAndUnwrap(pathToDll, "TestApp1.Class1") as IApp;
if (instance != null)
    MessageBox.Show(instance.Name);
```

**Comment by goldshtn** [comment]
@distantcam Having hit this problem myself just recently, I'm wondering if there is any way Costura could make it easier for secondary AppDomains to implement their own assembly resolution (without having to spill assemblies to disk with CreateTemporaryAssemblies="true" and then setting the AppDomain base to the Costura temp folder). For example, maybe you could provide a public hook that can be passed to AppDomain.AssemblyResolve and will use the same algorithm for resolving dependencies that is used in the primary AppDomain?
