### ISSUE TITLE
Assemblies excluded from processing by Costura still deleted by the output folder cleanup step

### ISSUE THREAD

**Issue by konste** [Fody/Costura#98]
First of all, thank you for a great piece of Software! It does amazing things amazingly well!

I'm trying to exclude a few referenced assemblies from processing by Costura and indeed corresponding flag in Fody.Weavers.xml does the job and assemblies got skipped. 

The problem is with the output folder cleanup target you recommended:
<Target 
    AfterTargets="AfterBuild;NonWinFodyTarget"
    Name="CleanReferenceCopyLocalPaths" >
     <Delete Files="@(ReferenceCopyLocalPaths->'$(OutDir)%(DestinationSubDirectory)%(Filename)%(Extension)')" />
</Target>

It removes all references, including those excluded from Costura processing.
Could you please recommend how to update cleanup script to leave excluded assemblies intact?
May be Costura Target implementation can provide msbuild variable with the list of files processed by Costura, so that cleanup step could be made more specific?

Thank you!
Konstantin

**Comment by distantcam** [comment]
@konste Do you have an example project I can use to reproduce this issue?

**Comment by distantcam** [comment]
Also, I think you might have been using the old version of the cleanup script that was part of the readme. The recommended way now is to use the `Install-CleanReferencesTarget` command to include a better script.

**Comment by konste** [comment]
Well, readme says: "Note that this does not handle ExcludeAssemblies or IncludeAssemblies options mentioned above. You will have to handle these explicitly.", so it is by design (or at least documented), but frankly it is not obvious or convenient.

**Comment by SimonCropp** [comment]
@konste if this is still an issue and u have a alternative approach perhaps submit a PR to illustrate your idea. until then i will close this
