### ISSUE TITLE
Configure Costura Fody for Release Only and Disable for Debug Builds

### ISSUE THREAD

**Issue by avoitenko** [Fody/Costura#994]
I need to configure the Costura Fody weaver to be enabled only for Release builds and disabled for Debug builds in my C# project. Currently, Costura runs in all configurations, but I would like to restrict it to Release mode to improve build times and facilitate easier debugging. Please provide a solution or documentation on how to achieve this setup.

**Comment by GeertvanHorrik** [comment]
> Please provide a solution or documentation on how to achieve this setup.

I expect this to take approx. 8 hours to implement. Are you or your company willing to financially support this feature?

**Comment by avoitenko** [comment]
I represent an individual, not a company. I can donate an amount equal to 10 cups of coffee, no more.

**Comment by avoitenko** [comment]
> I expect this to take approx. 8 hours to implement. Are you or your company willing to financially support this feature?
I represent an individual, not a company. I can donate an amount equal to 10 cups of coffee, no more.

**Comment by tom-englert** [comment]
https://github.com/Fody/Home/blob/master/pages%2Fconfiguration.md

If you use Ms build property you should be able to configure this

**Comment by avoitenko** [comment]
@tom-englert 
Thanks for your advice.
This configuration has been added to the project file:
```
<ItemGroup Condition="'$(Configuration)' == 'Release'">
    <PackageReference Include="Costura.Fody" Version="5.7.0" />
</ItemGroup>
```
It works for me.
